### ISSUE TITLE
publishToConfluence: Add possibility to set the page version comment 

### ISSUE THREAD

**Issue by anchialas** [docToolchain/docToolchain#1002]
While updating the Confluence page, I want to set the page revision comment. 

According [1] this can be achieved by adding a `message` property to `version` for the page insert and update request.

Example:
```
{
    ...
    "version": {
        ...
        "message": "Page update message",
        "number": 1
    }
}
```

References.
[1] https://developer.atlassian.com/server/confluence/confluence-rest-api-examples/#create-a-new-page

**Comment by rdmueller** [comment]
thanx for the PR - these are the best issues :-)
