### ISSUE TITLE
Docs: Feedback for 'Installing docToolchain' 👍

### ISSUE THREAD

**Issue by apparatchick** [docToolchain/docToolchain#1004]
Adding instruction for Mac: hint: they are the same as for Linux. I've tested the instructions on an M1 Mac. All works fine. If you add a comment to the .ps1 commands that they are for PowerShell, that would be clearer.

---
#page:010_manual/20_install.adoc

**Comment by rdmueller** [comment]
thanx for the Feedback.

* regarding the Mac instratuctions - would it help to rename the tab "Linux / WSL2 with bash" to "Linux / MacOS / WSL2 with bash"?

* regarding `.ps1` commands - can you suggest the comment and where to put it?

**Comment by apparatchick** [comment]
Hi Ralf,

Thank you for making docToolchain! I am trying it out right now, but running into some image  issues that I am trying to solve first while following your instructions+Youtube tutorial. To answer your questions:
1. Yes, I think that's fine.
2. Under "Running your First Command ", below the tabs in that section, are two commands. /dtcw downloadTemplate
./dtcw.ps1 downloadTemplate. I now think maybe you can do it like this. 
" For Linux/MacOS, type:
/dtcw downloadTemplate
 For Powershell, type:
./dtcw.ps1 downloadTemplate." You could do the same for the section === Building and Creating Templates.

**Comment by mh182** [comment]
Closing since those tabs were integrated
