### ISSUE TITLE
Docs: Feedback for 'Installing docToolchain' 👎

### ISSUE THREAD

**Issue by tkleiber** [docToolchain/docToolchain#1008]
Hi!

Calling the wrapper gives syntax errors on SLES 12.5 does not work:

```
curl -Lo dtcw doctoolchain.github.io/dtcw
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0   3306      0 --:--:-- --:--:-- --:--:--  3306
100  3063  100  3063    0     0  17403      0 --:--:-- --:--:-- --:--:-- 17403

./dtcw tasks --group=doctoolchain
./dtcw: line 1: syntax error near unexpected token `newline'
./dtcw: line 1: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'

bash --version
GNU bash, version 4.3.48(1)-release (x86_64-suse-linux-gnu)
```

Kind regards
Torsten

---
#page:010_manual/20_install.adoc

**Comment by tkleiber** [comment]
McAfee Web Gateway has blocked the file and changed the content on download.

**Comment by rdmueller** [comment]
Thanx for reporting this.
I wonder if there is a way to catch such a problem... Maybe an additional curl option I am not aware of?

**Comment by tkleiber** [comment]
My only idea would be some checksum checks. Unfortunatly I find no such parameter in curl. So the checksum has to be put in a separate file. 

Oracle does similar things to check separetely downloadable installation files in checksumPackages function here:
https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh
