### ISSUE TITLE
Wrapper script doctoolchain.github.io/dtcw still uses v.2.1.0

### ISSUE THREAD

**Issue by mh182** [docToolchain/docToolchain#1030]
Following the installation instructions as described in [Install docToolchain](http://doctoolchain.org/docToolchain/v2.0.x/010_manual/20_install.html).

**To Reproduce**
1. Install `docToolchain` wrapper
```
➜  curl -Lo dtcw doctoolchain.github.io/dtcw
➜  chmod +x dtcw
```
2. Check environment by calling the wrapper script
```
➜ ./dtcw 

dtcw - docToolchain wrapper V0.36
docToolchain V2.1.0
docToolchain as CLI available
docker available
home folder exists
No valid argument(s) supplied
```

**Expected behavior**
I would have expected the current release [v2.2.0](https://github.com/docToolchain/docToolchain/releases/tag/v2.2.0).

**Comment by rdmueller** [comment]
yes, it is still on v2.1.0 because I wanted to wait one week to see if those who upgrade their scripts run into problems.
Do you think we should already by now change it?

**Comment by mh182** [comment]
If this was meant to be a delayed release of the wrapper script we may close the issue.

I was just surprised that after the installation of `dctw` it didn't use the latest release. I understand your reasoning but maybe other users will also be surprised as I was.

IMHO delaying the release of the wrapper script has more disadvantages than advantages:
* It confused new users and the tracker may get similar bug reports like mine
* What do we do if the new release fixes some bugs in the `dctw`?  
* It shows that the people working on the project do not have the confidence in the software quality they produce.

I would rather suggest to focus for fast bug-fix release in case a "paper bag error" (Papiersackerl Fehler) shows up.
