### ISSUE TITLE
Calling the wrapper script without any argument does not provide helpful output

### ISSUE THREAD

**Issue by mh182** [docToolchain/docToolchain#1045]
This is a regression already reported in #1043.

Calling the wrapper script without any argument does not provide helpful output. The the wrapper script of version v2.1.0 provided a good description what the user should do next. 

**To Reproduce**
1. Install the wrapper script
```
~/tmp 
➜ mkdir test && cd test

~/tmp/test 
➜ curl -sLo dtcw doctoolchain.github.io/dtcw

~/tmp/test 
➜ chmod +x dtcw 
```
2. Call the wrapper script with no arguments
```
~/tmp/test 
➜ ./dtcw

dtcw - docToolchain wrapper V0.36
docToolchain V2.2.0
docToolchain as CLI available
No valid argument(s) supplied
```

**Expected behavior**
The user is provided with helpful information what they should do next. In previous releases we had following output.
```
./dtcw 

dtcw - docToolchain wrapper V0.36
docToolchain V2.1.0
docToolchain as CLI available
local java JDK found
use /home/max/.doctoolchain/jdk as JDK

Usage: ./dtcw [option...] [task...]

You can use the same options and tasks as in underlying gradle.
Use "./dtcw tasks --group doctoolchain" to see available tasks.
Use "local", "sdk" or "docker" as first argument to force the use of a local, sdkman or docker install.

Examples:

  Download and install arc42 Template:
    ./dtcw downloadTemplate

  Generate PDF:
    ./dtcw generatePDF

  Generate HTML:
    ./dtcw generateHTML

  Publish HTML to Confluence:
    ./dtcw publishToConfluence

  get more documentation at https://doctoolchain.github.io
```

**Screenshots**

**Configuration**
 - docToolchain version: v2.20
 - OS: Linux
 - Relevant SDK Versions: the one provided with `getJava`

**Comment by rdmueller** [comment]
? what happened here. I will try to fix this immediatly

**Comment by rdmueller** [comment]
So, this was the PR which introduced the problem: https://github.com/docToolchain/docToolchain/pull/993
trying to revert the checks
