### ISSUE TITLE
v2.2.0 breaks code blocks in Confluence

### ISSUE THREAD

**Issue by tafli** [docToolchain/docToolchain#1048]
With version 2.2.0 the task `publishToConfluence` seems to have problem with publishing the code markup.

As example, following snippet

```asciidoc
[source,json]
----
{
   "result": "true",
   "message": "Hello"
}
----
```

leads to be published in confluence as:
![Confluence 1](https://user-images.githubusercontent.com/15720039/220642925-d8d20b40-fb90-4dc0-ad0b-ce19e671c94d.png)

What's strange is, that the code has no newlines but additional whitespaces:

![Confluence 2](https://user-images.githubusercontent.com/15720039/220643183-a37e7caa-409d-4e2d-8066-dd47107febb0.png)

The generated html5 build looks correct.

Publishing with DTC v2.1.0 worked fine.

**Comment by PacoVK** [comment]
cannot reproduce neither with `2.2.1` nor with `latest`. 
Could you please upgrade to `2.2.1` and check if the error still exists? 
If the error persists, please provide more context, eg. which Confluence/ Java version you have been using? 

Using Java 11 and docToolchain `2.2.1`/`latest` i get the following result on Confluence Cloud: 
<img width="784" alt="grafik" src="https://user-images.githubusercontent.com/27785614/236699261-4f3f0283-8c7f-4221-b4f8-def5f46e7895.png">

**Comment by tafli** [comment]
Meanwhile on `2.2.1` the problem is not reproducable anymore.
