### ISSUE TITLE
PlantUML and DITAA generation to PDF broken

### ISSUE THREAD

**Issue by jakubjab** [docToolchain/docToolchain#105]
## Expected behavior and actual behavior.

PlantUML and DITAA diagrams are generated into PDF.
Actual behavior is that the source code is visible in PDF instead of generated image.

## Steps to reproduce the problem.

Add PDF backend for manual.adoc.
Checkout 9e2e4bf version of docToolchain and run ./gradlew - chapter 3.2.1 contains diagrams
Checkout 5523c56 version of docToolchain and run ./gradlew - chapter 3.2.1 contains source code

## Specifications like the version of the project, operating system, or hardware.
5523c56 and later version of docToolchain
MacOS
Java 1.8.0_77

**Comment by rdmueller** [comment]
I guess it was a mistake to upgrade to 1.5.6 - we shouldrevert back to
asciidoctor 1.5.3 ...

jakubjab <notifications@github.com> schrieb am Mi., 25. Okt. 2017 14:12:

**Comment by rdmueller** [comment]
I will first implement a test which verifies that it is broken and then change the versions back...

**Comment by whiskerz** [comment]
As far as I can see HTML is also affected. When trying to include your example plantUML I always get an error message: 

invalid style for listing block: plantuml

Reverting to 1.5.3 fixes this and prints the diagram as expected.

**Comment by rdmueller** [comment]
@whiskerz yes, it seems that the whole asciidoctor-diagram module does not work :-/
