### ISSUE TITLE
publishToConfluence: hash is displayed at end of some pages

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#1053]
the hash should be hidden behind an html comment, but it is shown on some pages.

hash not visible: https://arc42-template.atlassian.net/wiki/spaces/v8sde/pages/2054553601/1.+Einf+hrung+und+Ziele

hash visible: https://arc42-template.atlassian.net/wiki/spaces/v8sde/pages/2054619137/2.+Randbedingungen

**Comment by PacoVK** [comment]
solution provided in #1189 using the <ac:placeholder> tag

**Comment by PacoVK** [comment]
Fixed by #1189
