### ISSUE TITLE
Upgrade Asciidoctor Gradle Plugin v4

### ISSUE THREAD

**Issue by mh182** [docToolchain/docToolchain#1105]
Created due to the discussion in #1102.

docToolchain uses Asciidoctor Gradle Plugin v3.*, which is in maintenance mode only. We can not upgrade to a newer Gradle version which supports Java 17 due to [asciidoctor-gradle-plugin/issues/626](https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/626). 

With this issue, we want to test the maturity of Asciidoctor Gradle Plugin v4.

**Comment by PacoVK** [comment]
see #1108 

@mh182  sorry, messed it a bit up i was not aware that i could not create a PR for another open PR, hence #1108 also contains all changes of #1104  

Do you think we should do the evaluation based on Gradle 6.x (current ng-branch) if possible? Not sure what is best here

**Comment by mh182** [comment]
> @mh182 sorry, messed it a bit up i was not aware that i could not create a PR for another open PR, hence #1108 also contains all changes of #1104

Thanks a lot. 

To make life easier for integrating the code, could you squash all commits of #1104 into a single commit?
It would not only make #1108 easier to integrate, but also make it easier for me to rebase #1077 on top of #1104.

> Do you think we should do the evaluation based on Gradle 6.x (current ng-branch) if possible? Not sure what is best here

I have no idea how @rdmueller tested the correctness of all the different features of docToolchain. That's we have to discuss when he is back from vacation.

Is there a reason you upgraded to Gradle 7.5.1 and not the latest 7 version, which would be 7.6.1?

**Comment by PacoVK** [comment]
Sure I will do that.

Concerning Gradle version unfortunately there is an incompatibility from 7.6 onwards with the Asciidoctor Gradle plugin see [issue](https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/655) I would not suggest to try some of the mentioned workarounds but rather wait for the Gradle 8 support and just skip 7.6 then

**Comment by mh182** [comment]
OK, good to know.

This means - assuming the result with the plugin are OK - we could upgrade to Gradle 7.5, which supports Java 17, the current LTS. 

This way we would have time until September 2023 when [Java 21, the next LTS](https://en.wikipedia.org/wiki/Java_version_history) is released.

**Comment by PacoVK** [comment]
That's a plan 😊 I check for Java 17 if there are issues and will then enable it in the CI

**Comment by mh182** [comment]
We upgraded the plugin with commit 618bf71815953147916f80bd449fb1cb9f7dea41.
