### ISSUE TITLE
docToolchain PlantUML diagram.png HTML5 rendering mismatch with native PlantUML diagram.png

### ISSUE THREAD

**Issue by c835722** [docToolchain/docToolchain#111]
Thank you for your efforts on this project. I think its great and I am attempting to use it on a real project.
This issue is more a query.

## Expected behavior and actual behavior.
I am using PlantUML blocks inside a document.
I find that at what appears to be a certain size/complexity of plantuml source code the docToolchain HTML5 generated rendering of the diagram is smaller (when viewed in the browser) and of a different (unpredicted) layout than that native plantuml rendering of the same source document.
Is there any technique to override the docToolchain/asciidoctor-diagram generation such that it always matches the size of the native plantuml rendering?

## Specifications like the version of the project, operating system, or hardware.
Name:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A405
docToolchain. latest.
PlantUML. 1.2017.18

**Comment by Wallaby1999** [comment]
Did you try SVG as output format for your diagrams?
This should at least solve the scaling problem, as it is a vector format and scales to whatever size is needed.

**Comment by c835722** [comment]
Yes I did try both png and svg without success. Both produce the same result (different layouts of PlantUML sprites) in the Browser.

**Comment by rdmueller** [comment]
can you upload an example of two different renderings? docToolchain uses Asciidoctor-diagram which uses the native plantUML library. So I am a bit surprised about the behaviour you describe and would like to solve it.

**Comment by c835722** [comment]
ok let me first obfuscate a little of the content and get back to you.

**Comment by c835722** [comment]
I attach a screen capture with "native" rendering on the left and the docToolChain on the right to display the visual difference that I am seeking to remove.
![doctoolchain111](https://user-images.githubusercontent.com/1875669/32471772-bc6dc86a-c3aa-11e7-944d-6aa04ad5826c.png)
The left side image was produced with the command
```bash
asciidoctor -r asciidoctor-diagram -b html5 ./src/docs/app/04_integration.adoc
```
The right side image was produced with the command
```bash
./gradlew generateHTML
```

**Comment by c835722** [comment]
This may be a .svg vs .png rendering issue.
When I am using docToolchain for diagrams I am rendering using .svg via a local plantuml-server to iterate diagram change with less lag.
This technique seems to respect the plantuml associations more accurately leading to improved diagram structure (IMHO).
I will hunt around to see if this is a known issue wider than this docToolchain project. Will keep issue open here for convenience if that is ok.

**Comment by rdmueller** [comment]
what do you mean by 

> via a local plantuml-server

?

In docToolchain, you usually use plantUML via Asciidoctor-Diagram as described here: https://rdmueller.github.io/plantuml-gradle/ or here https://doctoolchain.github.io/docToolchain/#_text_based_diagrams

Do you just reference an external image from the local plantUML server?

**Comment by c835722** [comment]
My personal workflow when diagraming/modelling in vscode in my docToolchain project is to use further plugins to render changes immediately in the right-hand window to validate the change.
To achieve this I utilise a either [PlantUML](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml) || [PlantUML NG](https://marketplace.visualstudio.com/items?itemName=jkeys089.plantuml#overview) plugin calling a local [PlantuML server](https://github.com/bitjourney/plantuml-service).
The plantuml-service plugin renders in SVG nicely and allows the nice positioning show in the screen print above which is great for layering models.
The issue comes when I then build final changes to the architecture documentation website where the PlantUML rendering changes to something different and the designated layering is lost.
I assume this may be because it may be being rendered as a PNG.
If this is indeed the issue then I pose the question whether it is possible to have docToolChain generate an SVG instead (or behind a switch perhaps) and thus improve the general outcome for other people whom may have a similar workflow for larger models. That is, better-structured models published faster.

**Comment by rdmueller** [comment]
thanx for the update. until now, I can't reproduce the problem. I use IntelliJ or Atom to pre-view my diagrams while editing and docToolchain renders them the same way. As far as I know, all tools in my toolchain use png to render - at least, I instruct them to do so.

So, I now have to try to come up with a diagram which does not layout in a nice way...

**Comment by c835722** [comment]
Perhaps I can assist.
Here is an adoc snippet with a small nonsense model embedded within it.
When rendered locally it has a single layer.
When rendered via docToolChain [generateHTML] the model has two layers in my browser.
Its that change in formatting I am trying to determine whether we can remove.
My desire is to have the Browser HTML model markup render identically to the IDE(in my case vscode) model markup.
``` 
=== Models
.Systems Context diagram
[plantuml, "{plantUMLDir}SystemsContextdocToolschain", png] 
---- 
@startuml SystemsContext

cloud Corporate #pink {
  Actor Finance_User
  Actor Engineering_User
  component Browser
}
cloud Internet #pink {
  Actor FooManChoo
  Actor BarManChoo
  component Browser2
}
cloud DMZ #pink {
  Actor AAAAAAAAAAAAA
  Actor BBBBBBBBBBBBB
  Actor CBBBBBBBBBBBB
  Actor DBBBBBBBBBBBB
  component Browser3
}
Finance_User       -> Browser 
Engineering_User   -> Browser 
FooManChoo         -> Browser2 
BarManChoo         -> Browser2 
AAAAAAAAAAAAA          -> Browser2 
BBBBBBBBBBBBB          -> Browser3 

@enduml
----
```

**Comment by rdmueller** [comment]
This seems to me like the docToolchain version of plantuml has some kind of max width set.
But with your first example the difference is even uglier...

I guess I found something...

you can render some plantuml infos by just rendering this simple diagram:

```
[plantuml, "{plantUMLDir}version", png]
----
@startuml
version
@enduml
----
```

This should show you the plantuml.jar used, the version of this jar and the graphviz version used. This could give you a hint about the difference.

I also noticed that I can switch between a two-layer version and a single-layer version of your diagram by switching my Graphviz dot version to jdot. You can do this by writing `!pragma graphviz_dot jdot` as your first plantUML statement:

```
[plantuml, "{plantUMLDir}SystemsContextdocToolschain", png]
----
!pragma graphviz_dot jdot
cloud Corporate #pink {
  Actor Finance_User
  Actor Engineering_User
...
```

let's see if we can find the problem this way.

btw: you can omit the `@startuml` and `@enduml` if you use the inline syntax for the diagrams.

**Comment by c835722** [comment]
Omitting the @startuml and @enduml actually creates a non docToolchain issue for me.
These tags facilitate my IDE(vscode) from being able to auto-preview the UML in the adoc which is very convenient for my workflow. (i.e. Change doc and model in the same place at same time).

However, moving to the good news.
1. Your pragma suggestion works as a technique for achieving the desired objective of consistent markup in the test case. Thanks! 👌 🥇 (when I remove the @startuml and @enduml tags)
2. It almost works for the original document (still one level type issue). Big improvement though so it looks like the suggestion is in the right place.

Observations:
1. When I follow the docToolchain plantuml version down to its implementation the -checkversion returned is
PlantUML version 8053 (Thu Dec 22 04:51:33 AEDT 2016)
There would appear some opportunity to upgrade this dependency. :zap:

**Comment by c835722** [comment]
So perhaps the backlog item for docToolchain might be.
1. Apply pragma as part of the build process to provide consistent local and HTML markup. ❔

**Comment by rdmueller** [comment]
Argh. What I forgot to mention is that the jdot version (pragma) is in alpha state and doesn't render arrow heads. So it isn't a solution for everything.

Are both of your renderers using the same graphviz?

**Comment by c835722** [comment]
Yes. graphviz: stable 2.40.1

**Comment by rdmueller** [comment]
Hi @c835722 - what's you current view on this?
Can we close it or do we still need to work on it?

**Comment by c835722** [comment]
Hi @rdmueller , thanks for the question. I'm happy if this item gets closed to keep the project tidy. Im sure we can open or reference it again if needs be.
