### ISSUE TITLE
dtcw not backward compatible with docToolchain 2.* with Java 17: Unsupported class file major version 61

### ISSUE THREAD

**Issue by mh182** [docToolchain/docToolchain#1117]
**Describe the bug**
With #1071 we support Java 17. 

After integrating PR #1077 we still have the situation that `dtcw` may call docToolchain versions which do not support Java 17. We have to restrict the Java major versions based on the docToolchain version.

**To Reproduce**
1. Install Java 17
```
➜ sdk install java 17.0.6-tem
➜ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
```
2. Create a project directory and install `dtcw` from PR #1077 
```
➜ mkdir test && cd test
➜ curl -LO https://raw.githubusercontent.com/docToolchain/docToolchain/1b08ce2ddffc184731153e8f8d4852924b6d9800/dtcw
➜ chmod +x dtcw
```
3. Install docToolchain which doesn't support Java 17 (docToolchain 2.2.1 and before)
```
➜ DTC_VERSION=2.2.1 ./dtcw install doctoolchain
dtcw 0.50 - ##DTCW_GIT_HASH##
docToolchain 2.2.1
Available docToolchain environments: local sdk docker
Environments with docToolchain [2.2.1]: sdk docker
Using environment: local
Installed docToolchain successfully in '/home/max/.doctoolchain/docToolchain-2.2.1'.
Using Java 17.0.6 [/home/max/.local/share/sdkman/candidates/java/current/bin/java]

Use './dtcw tasks --group doctoolchain' to see docToolchain related tasks.
```
4. foo
```
➜ DTC_VERSION=2.2.1 ./dtcw tasks --group doctoolchain
dtcw 0.50 - ##DTCW_GIT_HASH##
docToolchain 2.2.1
Available docToolchain environments: local sdk docker
Environments with docToolchain [2.2.1]: local sdk docker
Using environment: local
Using Java 17.0.6 [/home/max/.local/share/sdkman/candidates/java/current/bin/java]
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.9.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

> Configure project :

Config file '/home/max/tmp/test/docToolchainConfig.groovy' does not exist' 
[ant:input] 
[ant:input] do you want me to create a default one for you? (y, n)
<-------------> 0% CONFIGURING [4s]

FAILURE: Build failed with an exception.

* Where:
Script '/home/max/.doctoolchain/docToolchain-2.2.1/scripts/AsciiDocBasics.gradle' line: 45

* What went wrong:
A problem occurred evaluating script.
> BUG! exception in phase 'semantic analysis' in source unit 'script16825089598541287665430.groovy' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
```

**Expected behavior**
`dtcw` provides an error messages telling that docToolchain 2.2.1 doesn't support Java 17.

**Configuration**
 - docToolchain version: not yet released (after PR #1077 is integrated)
 - OS: Linux, Debian unstable
 - Browser: not important
 - Relevant SDK Versions: JDK 17

**Comment by PacoVK** [comment]
So are you planing to release docToolchain 3.*? Asking because comparing semver is not trivial using plain bash 😊

**Comment by mh182** [comment]
I agree with you, semver with bash is not funny.

Let's list the most common use cases:
1. Fresh installation of docToolchain: easy-peasy, all works well
2. Someone would like to try out the new docToolchain 2.3.0 (or 3.0.0) with Java 11, using the existing (old) `dtcw`
    ```
    # This would download 2.3.0 and call generateHTML
    DTC_VERSION=2.3.0 dtcw generateHTML
    ```
    * Would `generateHTML` break if someone would use Java 8? This we have to test.
    * `generateDeck` would break - see #1118 
3. The user upgrades to the new `dtcw` (released with docToolchain 2.3.0)
    ```
    curl -Lo dtcw doctoolchain.github.io/dtcw
    chmod +x dtcw
    dtcw install doctoolchain
    dtcw generateHTML
    ```
4. The user upgraded as described in step 3 but after finding some bugs he would like to use the previous version
    ```
    # Use dtcw provided by docToolchain 2.3.0 but with an older version
    DTC_VERSION=2.2.1 dtcw generateHTML
    ```
    - Assuming she didn't upgrade to Java 17 this would work
    - Breaks if the user upgraded to Java 17 and tries to call the old docToolchain: the fix would be to provide the older Java version with JAVA_HOME.

So the fix for this issue is
```
JAVA_HOME=/path/to/java/11 DTC_VERSION=2.2.1 dtcw generateHTML
```

I think this is easy enough, and we don't have to code something. What di you think?

**Comment by PacoVK** [comment]
I like the approach, i think we introduced many changes which added quite some value, hence we should not waste too many effort to keep everything compatible. 

With the proposed "workaround" `dtcw` is backwards compatible which is the more important direction than having `dctw` forward compatible. The wrapper is essentially a convenience script for the user and should always be "upgradable" without relying on any DTC version.

Again we should have prominent documentation to avoid having users to search for a solution, once they run in a error related to that

**Comment by mh182** [comment]
Closing, since it is a corner case and a workaround is available.
