### ISSUE TITLE
generateSite: copyImages can't handle duplicate images

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#1119]
upgrade to the newer gradle version introduced this bug. 
The `generateSite` task invokes the `copyImages` task which then produces the error and displays a hint to resolve it:

https://docs.gradle.org/7.5.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy

To reproduce, use the test-project: https://github.com/rdmueller/latest-doctoolchain-test-project

**Comment by mh182** [comment]
Using your test repo the step `./dtcw generateHTML` failed. I created #1121
