### ISSUE TITLE
CI build: automated tests for dtcw.ps1

### ISSUE THREAD

**Issue by mh182** [docToolchain/docToolchain#1134]
Improve CI build introduced by #1073 for `dtcw.ps1`.

The existing tests should be executed on changes on
- `dtcws.ps1`
- the test code testing the script

I think it would make sense to run the CI build on a GHA MS Windows runner.

Note: we don't have the same test coverage as with `dtcw`. The goal is to improve the CI build.

**Comment by rdmueller** [comment]
see #1135 

runs on windows and linux. macOS currently excluded. Test reports are generated as artifacts for download
