### ISSUE TITLE
print_version_info called too early in powershell script

### ISSUE THREAD

**Issue by ambition-consulting** [docToolchain/docToolchain#1145]
print_version_info requires variables ($environment), that get defined further below. Unless I move it below the initialisation, I will get:

`You cannot call a method on a null-valued expression.`

**Comment by mh182** [comment]
Sorry, this was an error. I'm going to fix this.

**Comment by mh182** [comment]
This would have been caught if we had #1134 in place.

**Comment by mh182** [comment]
Thanks for testing out the upcoming release and to report this bug.

**Comment by ambition-consulting** [comment]
you're welcome - thanks for working on this great tool, which helps me every day. :)
