### ISSUE TITLE
upload to confluence breaks with embedded images

### ISSUE THREAD

**Issue by PacoVK** [docToolchain/docToolchain#1163]
**Describe the bug**
Due to the solution for #425 we introduced the `data-uri` setting for asciidoctor. 
This breaks now the `:publishToConfluence` task. 

**To Reproduce**
1. run `:generateHTML` task on a document with images
2. run `:publishToConfluence`
3. See error

**Expected behavior**
No error and document is published to Confluence

**Screenshots**

**Configuration**
 - docToolchain latest
 - OS: all
 - Relevant SDK Versions all supported

**Additional context**
We have two possible solutions:
1. we don't support the requirement of #425  - we cannot fail on missing images, optional you can set `data-uri` on your own, this will then support for failing images. You cannot use `:publishToConfluence` then. 
2. we implement changes in `:publishToConfluence` that can handle embedded images. This means embedded images need to be "unembedded" and uploaded to confluence, since confluence is not able to handle embedded images.

**Comment by PascalWillig** [comment]
I prefer solution one but rather like this:
data-uri option (true/false) in the generateHTML which is overwritten with false when publishToConfluence is called.

**Comment by PacoVK** [comment]
i think with the PR that implements option 2 we can have both, embedded images (a requirement for fail on missing images) and the same behaviour as it is as of now in v2.x
