### ISSUE TITLE
Execution failed for task ':publishToConfluence'. > java.io.FileNotFoundException: /project/build/html5/../images/X.png (No such file or directory)

### ISSUE THREAD

**Issue by stefanitsky** [docToolchain/docToolchain#1186]
**Describe the bug**

Can't publish docs to confluence.

**To Reproduce**
1. Download template (https://github.com/bitsmuggler/arc42-c4-software-architecture-documentation-example);
2. Configure project (confluence creds, namings etc.);
3. Execute publish (publishToConfluence);
4. See error: 
<img width="1000" alt="image" src="https://github.com/docToolchain/docToolchain/assets/22547214/45f2ff59-2c7b-47bd-84b3-f1c5c3ad6666">

**Expected behavior**

Documentation successfully publishes.

**Configuration**
 - docToolchain version: ng
 - OS: OSX + docker (custom image based on eclipse-temurin:11-jdk-jammy)

I fixed it by changing this line: https://github.com/docToolchain/docToolchain/blob/ng/scripts/asciidoc2confluence.groovy#L653
But i don't know, is it ok or not.

Project tree:
```
├── Config.groovy
├── Dockerfile
├── Makefile
├── README.md
├── build
│   └── html5
│       ├── projectX.html
│       └── images
│           └── auth_by_login_and_password.png
├── docs
│   ├── adrs
│   │   ├── 0001-record-architecture-decisions.adoc
│   │   ├── 0001-record-architecture-decisions.md
│   │   ├── 0002-auth-with-jwt.adoc
│   │   ├── 0002-auth-with-jwt.md
│   │   ├── 0003-arc-42-docs-format.adoc
│   │   └── 0003-arc-42-docs-format.md
│   ├── projectX.adoc
│   ├── arc42
│   │   ├── 01_introduction_and_goals.adoc
│   │   ├── 02_architecture_constraints.adoc
│   │   ├── 03_system_scope_and_context.adoc
│   │   ├── 04_solution_strategy.adoc
│   │   ├── 05_building_block_view.adoc
│   │   ├── 06_runtime_view.adoc
│   │   ├── 07_deployment_view.adoc
│   │   ├── 08_concepts.adoc
│   │   ├── 09_architecture_decisions.adoc
│   │   ├── 10_quality_requirements.adoc
│   │   ├── 11_technical_risks.adoc
│   │   ├── 12_glossary.adoc
│   │   ├── _about-arc42.adoc
│   │   └── _config.adoc
│   └── diagrams
│       ├── microservice_x
│       │   ├── v1
│       │   │   └── auth_by_login_and_password.puml
│       │   └── v2
│       │       ├── auth_by_login_and_password.puml
│       │       └── refresh_token.puml
├── environment.json
└── scripts
    ├── asciidoc2confluenceFixed.groovy
    └── convertAdrs.gradle
```

**Comment by PacoVK** [comment]
thanks for reporting this issue ❤️  i will provide a fix soon.

**Comment by PacoVK** [comment]
@stefanitsky  meanwhile you can simply fix the issue adding `-PfailOnMissingImages=false` to your command. 

like `./dtcw publishToConfluence -PfailOnMissingImages=false -PconfluenceUser=<<redacted>>...`

**Comment by stefanitsky** [comment]
> @stefanitsky meanwhile you can simply fix the issue adding `-PfailOnMissingImages=false` to your command.
> 
> like `./dtcw publishToConfluence -PfailOnMissingImages=false -PconfluenceUser=<<redacted>>...`

Thank you very much!

**Comment by PacoVK** [comment]
#1189 fixes this.
