### ISSUE TITLE
exportEA fails since v2.0.5 with an exception in line 106

### ISSUE THREAD

**Issue by PeterStange** [docToolchain/docToolchain#1193]
**Describe the bug**
Up to tag v2.0.3 of branch 'ng' there was no issue using exportEA to export diagrams and more from an EnterpriseArchitect project. 
With updating to the next available tag v2.0.5 issues are observed in task streamingExecute of exportEA.gradle. There was a change made to cover exportPPT issues with https://github.com/docToolchain/docToolchain/issues/420 exportEA encoding problem.

We get this error after applying this change:
FAILURE: Build failed with an exception.

* Where:
Script 'D:\repositories\docToolchain\scripts\exportEA.gradle' line: 106

* What went wrong:
Execution failed for task ':exportEA'.
> java.lang.Exception:
  sorry, this task currently needs needs windows as operation system
  if you started this task from WSL, please switch to powershell

**To Reproduce**
1. Clone docToolchain tag 'v2.0.5'
2. Step into the root folder and simply call 'gradle exportEA'
3. See error

**Expected behavior**
The model 'docToolchain\src\docs\Models.eap' is found by the exportEA task and all diagrams were exported.

**Screenshots**

**Configuration**
 - docToolchain v2.0.5
 - OS: Window
 - Browser Firefox
 - Relevant SDK Versions [e.g. JDK 1.8, ...] 
 - gradle 6.7.1, openjdk version "1.8.0_372"

**Additional context**
Problem is caused by line: 
'String commandUTF8 = new String(command.value, 'utf-8');'
message: is "No such property: value for class"

locally fixed by replacing erroneous line by 
'String commandUTF8 = new String(command.toString().getBytes(), 'utf-8');'
Advantage of doing it this way: it works also in case command is already a String as String.toString() works also.

Any help is appreciated to get the right fix here. Even the reason for placing this charset conversion is not clear to me. Maybe someone can explain.
@rdmueller : what is your suggestion to get it generally fixed. We would like to switch latest available version, but with this issue it is not possible.

**Comment by PacoVK** [comment]
Hey @PeterStange  could you please try v2.2.1 as this is the current latest release? Does the problem still persist?

**Comment by PeterStange** [comment]
Hey @PacoVK, yes the problem exists in latest version v2.2.1, too. 
I observed the issue in latest version and analysed for last working one, which is v2.0.3.

**Comment by PacoVK** [comment]
Thanks! I just recognized you are on a PR, which is awesome! I can checker later that day. Please note the latest version (beyond 2.2.1 will drop support for Java 8)
