### ISSUE TITLE
generateDeck on powershell-based dtcw forgets to download reveal.js if missing.

### ISSUE THREAD

**Issue by ambition-consulting** [docToolchain/docToolchain#1204]
**Describe the bug**
the linux dtcw script checks for reveal.js resources being available - the windows powershell script does not.

**Comment by mh182** [comment]
This was already adressed with the coming v3.0 release, where reveal.js has not to be downloaden separately.

This will not be fixed anymore in v2.

**Comment by mh182** [comment]
Closing this aß fixed with v3
