### ISSUE TITLE
Task: publishToConfluence - Too many requests

### ISSUE THREAD

**Issue by hjzimmer** [docToolchain/docToolchain#1241]
in doctoolchain v2.2.1 we encounter the following problem:
- Asciidoc document with 20 chapters as included files
- round about 100 images over all pages distributed
- UML diagrams included in asciidoc

Building HTML code works fine.
During puiblischToConcluence the following error is raised all the time based on HTML response 429 (Too many requests):
`
> Task :publishToConfluence FAILED
FAILURE: Build failed with an exception.
* Where:
Script '/doctoolchain/scripts/publishToConfluence.gradle' line: 30
* What went wrong:
Execution failed for task ':publishToConfluence'.
> groovyx.net.http.HttpResponseException: status code: 429
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.2/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 21s
`
Smaller documents work fine. Retries finish in the same problem.

In case the confluence REST API declines with 429 it needs a configurable wait cycle and retries to that operation.
Or the "requestRatePerSecond" needs to be configurable.

[log.txt](https://github.com/docToolchain/docToolchain/files/12366901/log.txt)

**Comment by rdmueller** [comment]
wow. thanx for reporting this. Never had the need to implement throttling. I guess we could add it to the `trythis`-block: https://github.com/docToolchain/docToolchain/blob/ng/scripts/asciidoc2confluence.groovy#L82

**Comment by hjzimmer** [comment]
I am not a java expert nor used groovy before, but might this be (a dirty) workaround to reduce at least the throttle risk?

```
// for getting better error message from the REST-API
// LuisMuniz: return the action's result, if successful.
def trythis(Closure action) {
    def count = 0
    def maxTries = 3
    while (count < maxTries) {
        try {
            action.call()
            count = maxTries    // don't retry anymore
        } catch (HttpResponseException error) {
            println "something went wrong - got an http response code "+error.response.status+":"
            switch (error.response.status) {
                case '401':
                    println (error.response.data.toString().replaceAll("^.*Reason","Reason"))
                    println "please check your confluence credentials in config file or passed parameters"
                    throw new Exception("missing authentication credentials")
                    count = maxTries
                    break
                case '400':
                    println error.response.data.message
                    println "please check the ancestorId in your config file"
                    throw new Exception("Parent does not exist")
                    count = maxTries
                    break
                case '429':
                    println error.response.data.message
                    count = count + 1
                    println "Throttling connection, doing another " + (maxTries-count) + "retries ..."
                    sleep(1000 * count)  // sleep 1, 2 or 3 seconds ...
                    break
                default:
                    println error.response.data
            }
            null
        }
    }
}
```

**Comment by rdmueller** [comment]
sorry, currently my time is limited.
yes, the code looks good. Did you have a chance to test it?

**Comment by hjzimmer** [comment]
Thanks for the feedback.
Unfortunatly I am not able to test, since the environment has changed a bit and the response 429 (Too many requests) is not reproducable anymore in my environment

**Comment by rdmueller** [comment]
thanx for the feedback. So I guess we can close this for now.
