### ISSUE TITLE
publishtoconfluence needs parameter confluenceApi for deploying to different confluence environments

### ISSUE THREAD

**Issue by tkleiber** [docToolchain/docToolchain#1254]
**Is your feature request related to a problem? Please describe.**
I have to deploy in CI automation server the documentation first to test server for acceptance test.

**Describe the solution you'd like**
api parameter is fix in Config.groovy for one environment. I need an additional parameter confluenceApi like confluenceUser and confluencePass.

**Describe alternatives you've considered**
- I could modify Config.groovy via sed before calling publishtoconfluence

**Comment by PacoVK** [comment]
@tkleiber thanks for your request! I think this is something we could consider in #1226

**Comment by PacoVK** [comment]
This has been released in 3.1.x
