### ISSUE TITLE
Drop-Down Lists in the Top Panel

### ISSUE THREAD

**Issue by timo-abele** [docToolchain/docToolchain#1266]
**Is your feature request related to a problem? Please describe.**
I want to use docToolchain to assemble several volumes of documentation. 5 topics (general, backend, anti-corruption-layer, client, legacy) with 3 documentation aspects each (arc42, business, how-to) result in 15 separate documentation volumes:
general-arc42, general-business, general-how-to, backend-arc42, ... legacy-how-to.
![grafik](https://github.com/docToolchain/docToolchain/assets/129042237/a1832684-e1d9-43ac-ae0f-ecaf60b3fc57)
They are too many to comfortably fit in the top panel. But they are too different to be in the same sidebar.

**Describe the solution you'd like**
Documentation folders can be grouped and each group displayed as a drop down menu.

![Screenshot 2023-10-19 115503](https://github.com/docToolchain/docToolchain/assets/129042237/0dc05582-eec8-4015-bd63-0c49addf81f6)

This display can be realized by arranging the folders hierarchically and putting a `menu.adoc` file (analogous to `index.adoc` used to structure the sidebar) inside a folder:
````
.
├── docToolchainConfig.groovy
├── dtcw
└── src
    └── docs
        ├── general
        │   ├── menu.adoc
        │   ├── arc42
        │   │   ├── page1.adoc
        │   │   ...
        │   ├── business
        │   └── how_to
        ├── backend
        │   ├── menu.adoc
        │   ├── arc42
        │   ├── business
        │   └── how_to
        ...
````

The `menu` field in `docToolchainConfig.groovy` can also be used for this by extending it somehow, e.g.
````
menu = [backend: ('backend', [arc42: 'arc42', business: 'business', how_to: 'how-to']),
        general: ('general', [arc42: 'arc42', business: 'business', how_to: 'how-to']), ... ]
```` 
or
````
menu = [backend: [null:'backend', arc42: 'arc42', business: 'business', how_to: 'how-to'],
        general: [null:'general', arc42: 'arc42', business: 'business', how_to: 'how-to'], ... ]
```` 
There is no further nesting, the items in the drop-down list do not expand further! Further nesting belongs into the sidebar. 

**Describe alternatives you've considered**
If the sidebar allowed collapsing chapters (I remember seeing an issue about this but can no longer find it) **and** if the sidebar was configured to started all collapsed, then it would also solve the problem.
But I think that would be less ergonomic. I prefer to make the selection while looking at the top panel. Also, selecting the desired element in the sidebar to uncollapse needs good aims and feels like an unneccessary extra step (even though it actually isn't). In my use case I also don't want to see the toc of other two volumes in the sidebar but only the one I need.

**Comment by timo-abele** [comment]
I found a way to create a dropdown just by fiddling with the theme, i.e. modifying the `site` folder. It looks like this:
<span id="85af93540870">![grafik][screenshot]</span>
Steps:

1. Arange your volumes flat under `docs` (as you normally would to create one menu item per volume). You can structure them with prefixes.
     ````
    .
    ├── docToolchainConfig.groovy
    ├── dtcw
    └── src
        └── docs
            ├── general_arc42
            │   ├── page1.adoc
            │   ...
            ├── general_business
            ├── general_how_to
            ├── backend_arc42
            ├── backend_business
            ├── backend_how_to
            ...
    ````
2. In the `menu` field in `docToolchainConfig.groovy` map the folder names to strings with a distinctive separator between topic and aspect, here `': '`. You can not use this separator in either topic or aspect! The separator will be visible in the left table of contents (see [picture above](#85af93540870)) so choose a separator that you are OK with seeing on the site. 
If you do not want an entry to open a drop down but just regularly open a page, choose a title without the separator. e.g.:

    ````
        menu = [
                general_arc42:    'general: arc42',
                general_business: 'general: business',
                general_how_to:   'general: how-to',
                backend_arc42:    'backend: arc42',
                backend_business: 'backend: business',
                backend_how_to:   'backend: how-to',
                ...
                blog:   'blog'
    ````

 3. In `menu.gsp` in the `site` folder (`dtcw copyThemes`) split the titles and group them by their topic. Add an inner loop, so a drop down is created for every topic. See [attachment](https://github.com/docToolchain/docToolchain/files/13532680/site_templates.zip) for a complete working file.

4. In the `header.gsp` add some css, see attachment for that as well.

Caveats:
 * There is no nesting in the `docs` folder, you have to use prefixes to keep everything sorted.
 * The name of the menu item is part of the top heading in the left sidebar    

(I can live very well with these caveats, just listing them for completeness sake.)

[screenshot]: https://github.com/docToolchain/docToolchain/assets/129042237/97bce31a-47c5-4319-b15b-35b3c533323b "preview"

**Comment by rdmueller** [comment]
Hi Timo,
these are great results! To great to hide them in this issue. Would you like to turn them into a tutorial for the website?
