### ISSUE TITLE
publishToConfluence broken when document contains internal links 

### ISSUE THREAD

**Issue by bkoziak** [docToolchain/docToolchain#1272]
**Describe the bug**
When document contains internal links (e.g. referencing other chapter in the same document) an error "No signature of method: asciidoc2confluence.realTitle() is applicable for argument types: (String) values: [XXXXX]" is returned when publishing to confluence.

It's most probably caused by this commit https://github.com/docToolchain/docToolchain/commit/0a49348096cf2a465583b8cce2f14a33107a66a9#diff-482888e721c9d1420e27180e496df331ec3ed087abba262c5b927e15b9fc312e where some of the closures where rewritten to functions.

**To Reproduce**
1. Create document with link from one chapter to another
2. Try to publish it to confluence
3. See error "No signature of method: asciidoc2confluence.realTitle() is applicable for argument types: (String) values: [XXXXX]"

**Expected behavior**
Successful publication to confluence

**Configuration**
 - docToolchain version: 3.0.2

**Comment by bkoziak** [comment]
I've opened a PR with a fix. Please review https://github.com/docToolchain/docToolchain/pull/1273

**Comment by PacoVK** [comment]
Thanks for your work :) #1205 contains a similar fix and we'll likely release that soonish. I'll check prior to the release whether we merge or addthe fix to the PR in #1205  since this is a whole rewrite
