### ISSUE TITLE
dtcw local tasks : error : running this gives ( Task '.encoding=UTF-8' not found)

### ISSUE THREAD

**Issue by jcralbino** [docToolchain/docToolchain#1276]
**Describe the bug**
when running the command ./dtcw local tasks we get this error
Task '.encoding=UTF-8' not found in root project 'docToolchain'.

![image](https://github.com/docToolchain/docToolchain/assets/44149262/9c527110-2a7a-458b-b329-7076b3658c28)

**To Reproduce**
1. Create a local offline copy using tips from here https://doctoolchain.org/docToolchain/v2.0.x/020_tutorial/120_self-contained-dtc.html
2. install a gradle binary as stated in point 1.
3. run .\dtcw local tasks
![image](https://github.com/docToolchain/docToolchain/assets/44149262/2a934cfd-70d7-40ba-be2c-f2ea7cff9825)

**Expected behavior**
No error are seen.
when running local ( From $HOME\.doctoolchain\doctoolchain-3.0.2\gradlew command this is working

**Screenshots**

**Configuration**
 - docToolchain version 3.0.2
 - OS: Windows server 2022
 - Relevant SDK Versions : Java 17

**Additional context**

**Comment by jcralbino** [comment]
doing the $HOME.doctoolchain\doctoolchain-3.0.2\gradlew tasks is working fine.

**Comment by TechiNikDev** [comment]
Same issue here:

Configuration:
- Relevant SDK Versions : Java 17.0.9
- docToolchain version 3.0.2
- OS: Windows 11 Pro

also this works:
doing the $HOME.doctoolchain\doctoolchain-3.0.2\gradlew tasks is working fine.

**Comment by fhsie** [comment]
Same issue ...
... works for $HOME.doctoolchain\doctoolchain-3.2.0\gradlew tasks
... gradlew generatePDF does not work with failure "Remote Asciidoctor process failed to complete successfully"
Does anyone know how to fix it.

I have also an additional question.
$HOME.doctoolchain\doctoolchain-3.2.0 is the location of the tool chain.
To have a project, I use the location "C:\Users\seiz.f\Documents\0_Tools\doctoolchain" where the batch file "dtcw.bat" is located.

Here the call "dtcw.bat local tasks" fails.
I copied the downloaded arc42 template from $HOME.doctoolchain\doctoolchain-3.2.0 to my project with adaption of the groovy configuration.

Can anybody help me do solve this.

Thank you in advance for your support!

**Comment by marcozwyssig** [comment]
When I removed the "-Dfile.encoding=UTF-8" parameter from line 31 in dtcw.ps1, the execution worked correctly.

**Comment by irkode** [comment]
This is a a problem of multiple evaluations of the used interpreters by chaining powershell and cmd which removes some string separators.

**SOLUTION:** add surrounding single quotes to the encoding option in line 31:

`$DTC_OPTS = "$env:DTC_OPTS -PmainConfigFile='$DTC_CONFIG_FILE' --warning-mode=none --no-daemon '-Dfile.encoding=UTF-8' "`

*more details*

* dtcw.ps1 line 31 sets:
  `$DTC_OPTS = "$env:DTC_OPTS -PmainConfigFile='$DTC_CONFIG_FILE' --warning-mode=none --no-daemon -Dfile.encoding=UTF-8 "`

* there is more than one place where dtcw.ps1 then sets $global:command to
  `...\doctoolchain.bat` adding argumens and finally adds `$DTC_OPTS.`
  * guess which command is actually set depend on OS, installed tools ... did't dive deeply in

* in line 136 it then calls:
  `Invoke-Expression "$global:command"`

  If you print the `$global:command` directly before that you will get:

  > `$env:USERPROFILE\.doctoolchain/docToolchain-3.2.2/bin/doctoolchain.bat . tasks --group=doctoolchain  -PmainConfigFile='docToolchainConfig.groovy' --warning-mode=none --no-daemon -Dfile.encoding=UTF-8`

* The real command is then executed in line 30 or 37 of `doctoolchain.bat`

  checking the command that is called after next shell evaluation shows:

  > "%USERPROFILE%\.doctoolchain\docToolchain-3.2.2\bin\..\gradlew.bat" --project-cache-dir %USERPROFILE%\docToolchain-3.2.2\bin\..\/.gradle "-PdocDir=." tasks --group=doctoolchain -PmainConfigFile=docToolchainConfig.groovy --warning-mode=none --no-daemon **-Dfile .encoding=UTF-8**

**ROOT-CAUSE:** looking closely you see the `-Dfile` is separated with **SPACE** from `.encoding=UTF-8`
So these become two options where the first just sets the file property and the latter is taken as _Task_ by _Gradle_

**Comment by rdmueller** [comment]
should we fix this with a PR?
