### ISSUE TITLE
publishToConfluence throws exception when uploading attachments in v3.1.0

### ISSUE THREAD

**Issue by sinkovec** [docToolchain/docToolchain#1281]
**Describe the bug**
When uploading attachments, e.g., images, using the new ConfluenceClient in 3.1.0 via the publicToConfluence task, the following error occurs. This affects the usage of v1 and the new v2 Api versions of the ConfluenceClient.
```
> Task :publishToConfluence FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/dtcuser/docToolchain/scripts/publishToConfluence.gradle' line: 43

* What went wrong:
Execution failed for task ':publishToConfluence'.
> No such property: MultipartEntityBuilder for class: groovyx.net.http.HTTPBuilder$RequestConfigDelegate

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
4 actionable tasks: 2 executed, 2 up-to-date
```

**To Reproduce**
1. Install 3.1.0 docToolChain Docker image
2. Download arc42 template using ./dtcw downloadTemplate
3. Run ./dtcw publishToConfluence ...

**Expected behavior**
The publishToConfluence task shouldn't throw an error when uploading attachments.

**Configuration**
 - docToolchain version: 3.1.0
 - OS: MacOS Sonoma
 - Relevant SDK Versions JDK 11
 - Atlassian Confluence: Confluence Cloud

Just an uneducated guess (after skimming the code): in the recent merge https://github.com/docToolchain/docToolchain/pull/1226, the ConfluenceClient seems to miss some import statements, e.g., for MultiPartEntityBuilder and HttpMultipartMode:

https://github.com/docToolchain/docToolchain/blob/cc78e99b0f920a0151e2c5650ebeb2b663908674/core/src/main/groovy/org/docToolchain/atlassian/clients/ConfluenceClient.groovy#L58-L59

**Comment by PacoVK** [comment]
@sinkovec thanks for reporting, that slipped through and will be released soon. You are absolutely right with the missing imports. i can reproduce and found the issue, there is also another bug that needs to be fixed

**Comment by PacoVK** [comment]
I already fixed the bugs, i will need to do some testing again and will build a better baseURL handling. Then we can release 3.1.1
