### ISSUE TITLE
generateSite not working on Mac M1

### ISSUE THREAD

**Issue by cgoguyer** [docToolchain/docToolchain#1289]
Hello,
generateSite is not working on Mac M1 although generatePDF and generateHTML works fine.
I'm using native openJDK:
```
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment Homebrew (build 17.0.9+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.9+0, mixed mode, sharing)
```

```
> Task :generateSite
> Task :bake FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bake'.
> A failure occurred while executing org.jbake.gradle.impl.JBakeWorkAction
   > /private/var/folders/nd/y6kkpjl13_gdb60t_mh24v600000gn/T/jna-1941716187/jna16761405974260304138.tmp: dlopen(/private/var/folders/nd/y6kkpjl13_gdb60t_mh24v600000gn/T/jna-1941716187/jna16761405974260304138.tmp, 0x0001): tried: '/private/var/folders/nd/y6kkpjl13_gdb60t_mh24v600000gn/T/jna-1941716187/jna16761405974260304138.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/nd/y6kkpjl13_gdb60t_mh24v600000gn/T/jna-1941716187/jna16761405974260304138.tmp' (no such file), '/private/var/folders/nd/y6kkpjl13_gdb60t_mh24v600000gn/T/jna-1941716187/jna16761405974260304138.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
5 actionable tasks: 3 executed, 2 up-to-date
```

**Comment by PacoVK** [comment]
Thanks for reporting! This is a known issue ([see](https://github.com/docToolchain/docToolchain/issues/1082)) I think we should try out either upgrade to latest release candidate of jbake or downgrade ([see](https://github.com/jbake-org/jbake/issues/709))

**Comment by PacoVK** [comment]
While revising the issue i came across https://github.com/docToolchain/docToolchain/issues/1082#issuecomment-1470095530 which is a bummer, because that literally means no fix as of now, because we would loose JDK11 support

**Comment by rdmueller** [comment]
So, the fix is to start the rosetta emulator via `arch -x86_64 /bin/bash` and install the doctoolchain jdk within the emulator `./dtcw local getJava` or with the new version of dtcw `./dtcw local install java`. After this you can exit the emulator bash and use docToolchain as usual.

docToolchain will detect and use the local JDK (installed to $USER/.doctoolchain). Since it is not the native apple silicon one, it will start rosetta in the background and run dtc with the x86 JDK. Within this JDK, jBake runs without flaw.

Hope this helps

**Comment by PacoVK** [comment]
thanks, i can confirm on my M1 it works with the steps outlined by @rdmueller 

Edit: I also verified that the latest Jbake-rc does not work. Hence, upgrade is currently no option and we need to use the aforementioned workaround

**Comment by cgoguyer** [comment]
Thx, it works with this tip.
