### ISSUE TITLE
Custom ruby extension for PDF generation

### ISSUE THREAD

**Issue by kneisslm** [docToolchain/docToolchain#1290]
I try to add a custom ruby extension to process a document in order to modify the title page of a PDF document.

I have added 
```
  rubyExtensions = ['asciidoctor-pdf-extensions.rb']
```
in docToolchainConfig.groovy .

With `docToolchain-3.0.2` I get

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/kneissl/.sdkman/candidates/doctoolchain/3.0.2/scripts/AsciiDocBasics.gradle' line: 246

* What went wrong:
A problem occurred evaluating script.
> Cannot set the value of read-only property 'requires' for task ':asciidoctor' of type org.asciidoctor.gradle.jvm.AsciidoctorTask.


```

This is very close to the issue posted by @davidschottel in https://github.com/docToolchain/docToolchain/issues/1239#issuecomment-1714126736_

I am really new to docToolchain so I am not yet able to apply his solution to my problem.

**Comment by cgoguyer** [comment]
I have the same issue (requires[] cannot be updated).
By the way, how to use an extension directly from ruby repository instead of copying it locally ?
```
dependencies {
  asciidoctorGems 'rubygems:asciidoctor-lists:1.0.9'
  asciidoctorGems 'rubygems:asciidoctor-bibliography:0.11.0'
}
...
asciidoctorj {
 ...
  requires 'asciidoctor-lists'
  requires 'asciidoctor-bibliography'
}
```

**Comment by cgoguyer** [comment]
Hi, any new for remote access to ruby repository?

**Comment by PacoVK** [comment]
Thanks for bringing this up, remote access will be targeted as extra feature, for now the functionality is limited to local custom extensions only. However, i do see value in this feature, but need to prioritize :)
