### ISSUE TITLE
Missing releases for SDKMAN! 

### ISSUE THREAD

**Issue by kneisslm** [docToolchain/docToolchain#1303]
**Describe the bug**
docToolchain releases >3.0.2 are not available via SDKMAN!

**To Reproduce**
1. sdk install doctoolchain 3.1.2
2. See error
```
Stop! doctoolchain 3.1.2 is not available. Possible causes:
 * 3.1.2 is an invalid version
 * doctoolchain binaries are incompatible with your platform
 * doctoolchain has not been released yet
```
**Expected behavior**
SDKMAN! should install docToolchain 3.1.2

**Configuration**
 - docToolchain version
 - OS: macOS 14.1.1 (Intel)
 - sdk version
```
SDKMAN!
script: 5.18.2
native: 0.4.3
```

**Comment by rdmueller** [comment]
thanx for the reminder. Yes, we first want to check the version before we release them on sdkman. Let's do a release now!

**Comment by rdmueller** [comment]
please recheck. v3.1.2 should be now availalbe via sdkman

**Comment by kneisslm** [comment]
That was fast! :)

Works for me.
