### ISSUE TITLE
doctoolchain.bat is missing in https://github.com/docToolchain/docToolchain.git

### ISSUE THREAD

**Issue by tkleiber** [docToolchain/docToolchain#131]
## Expected behavior and actual behavior.
In https://doctoolchain.github.io/docToolchain/#_build is stated that doctoolchain.bat has to be called on windows, but this does not exist in the cloned repository and so cannot be called.

## Steps to reproduce the problem.
Clone https://github.com/docToolchain/docToolchain.git or download and unzip https://github.com/docToolchain/docToolchain/archive/master.zip

Search for doctoolchain.bat, it is not found.

The found bash script bin\doctoolchain cannot be called on windows.

## Specifications like the version of the project, operating system, or hardware.
Commit: 1a025a0773930f523c98d9631eccf3dbd15cebaf [1a025a0]
Parents: b800cb68c7, 43e84d16ea
Author: Ralf D. Müller <ralf.d.mueller@gmail.com>
Date: Dienstag, 5. Dezember 2017 18:31:00
Windows 10

**Comment by rdmueller** [comment]
thanx for reporting this!

docToolchain was initially build as gradle script and this approach is still the default one. 
@jakubjab added a bash script to use docToolchain independently from gradle and the location of docToolchain, but a `.bat` or powershellscript is still missing. The documentation is already one step ahead :-|

On windows, it should still be possible to just `cd` to the docToolchain project folder and use `./gradlew.bat` with the corresponding commands, e.g.

    ./gradlew.bat generateHTML

I'll see what I can do to come up with a `.bat` file which will fix this.

**Comment by rdmueller** [comment]
I just added a `.bat` file which should do the trick. Can you give it a try?

**Comment by tkleiber** [comment]
This works fine when running in the <docDir>, but not when running from anywhere else, eg. from docToolchain\bin directory.

![image 1](https://user-images.githubusercontent.com/2185441/34627559-53f8f8f0-f261-11e7-9df0-979a28793b82.png)

**Comment by rdmueller** [comment]
Thank for testing.
I will try to fix this and cover it with a test

**Comment by rdmueller** [comment]
sorry, this took a while. The current version has already been tested by me.
please re-open if it doesn't work for you...

**Comment by rdmueller** [comment]
I'll try to reproduce it. Might be that I will come back to you to get it reproduced... :-)

**Comment by thokuest** [comment]
Same issue here! I'd like to generate documents that are placed outside of the docToolchain project directory.

`doctoolchain.bat` doesn't support absolute path at the moment. `%WORKINGDIR%%1` evaluates to a path underneath the working directory of the docToolchain project.

I *think* this can easily mitigated by replacing `%WORKINGDIR%%1` with `%~f1`, see [Resolve absolute path from relative path and/or file name](https://stackoverflow.com/questions/1645843/resolve-absolute-path-from-relative-path-and-or-file-name).

**Comment by rdmueller** [comment]
So, my solution is not as clean as the `%~f1` solution, but at least I undesand it better *g*

hope it works now and sorry for taking so long to resolve it...
