### ISSUE TITLE
initArc42: move init.gradle to main gradle file

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#132]
I really like the `doctoolchain` shell script and `init.gradle` tasks introduced by @jakubjab but I wonder if we shouldn't move the initTasks to the main gradle file. That would make them easier to handle...

@jakubjab what do you think?

**Comment by jakubjab** [comment]
I think I was trying that at first, but I found that when combined they also need a combination of plugins, and then initializing becomes heavy. But I can try to merge them.

**Comment by rdmueller** [comment]
ok. so if it is ok from your point of view, I'll take a look at it and see what I might come up with

**Comment by rdmueller** [comment]
I think I made progress with this. First draft is ready but it still needs tuning.

**Comment by rdmueller** [comment]
There are now two usecases which need to be fulfilled:

1) docToolchain installed as Tool as described in the manual: https://doctoolchain.github.io/docToolchain/#_how_to_install_doctoolchain

```
# get docToolchain
git clone --recursive https://github.com/docToolchain/docToolchain.git <docToolchain home>
rm -rf .git
rm -rf resources/asciidoctor-reveal.js/.git
rm -rf resources/reveal.js/.git

# add /bin to the path
...

# initialize new project
cd <docToolchain home>
./gradlew initArc42EN -PnewDocDir=<newDocDir>

# build project
doctoolchain <docDir> generateHTML
doctoolchain <docDir> generatePDF
```

2) docToolchain as stand-alone project

```
# get docToolchain
git clone --recursive https://github.com/docToolchain/docToolchain.git <docToolchain home>
rm -rf .git
rm -rf resources/asciidoctor-reveal.js/.git
rm -rf resources/reveal.js/.git

# remove all unneccesary stuff
...

# initialize new project
cd <clonedProject>
git init
./gradlew initArc42EN

# build project
./gradlew generateHTML
./gradlew generatePDF
```

2) should also work if you use docToolchain as add-on to an existing project.

My goal is now to get my new version https://github.com/rdmueller/forked_docToolchain up and running with those two scripts above, on Windows and Linux:

* Script 1) works on [ ] Windows and [ ] Linux
* Script 2) works on [ ] Windows and [ ] Linux

Do I have to add additional tests?

**Comment by rdmueller** [comment]
hm. I think I will remove the user input for missing properties again and replace them with exceptions which explain what to do. Feels to be more clean...

**Comment by rdmueller** [comment]
I think with the new downloadTemplate task, we have a solution for this. I will close this for now. Please reopen if you think this is wrong
