### ISSUE TITLE
publishToConfluence breaks with HTTP 404 response from Confluence in version 3.1.1 and 3.2.0 on creating an attachment

### ISSUE THREAD

**Issue by maksymgendin** [docToolchain/docToolchain#1332]
**Describe the bug**
The error happens on creating an attachment since DTC version 3.1.1, there is no error in version 3.0.2.

For some reasons the script executes a HTTP POST request on e.g. `/confluence/rest/api//confluence/rest/api/content/47260738/child/attachment` path. Notice the prefix duplication.

Checking if the attachment already exists before creating it (the step before) - works. And uses a correct path.

Before adding a diagram to my arc42 the publishToConfluence worked with all DTC versions. So it started to happen when I added a diagram, which becomes an attachment in Confluence.

**Configuration**
- Confluence Server Version (on-prem)
 - docToolchain version: 3.2.0 and 3.1.1
 - OS: macOS
 - SDK Versions: JDK 17

**Comment by PacoVK** [comment]
Thanks for the report :) 
Should work with 3.1.2 as this release has better support for the optional API contexts 
For 3.2.0 there is an issue see #1330  and there will be a fix soon. Once the fix for 3.2.0 is available i recommend to switch to the latest version, as the Confluence and Jira integration has big improvements.

**Comment by maksymgendin** [comment]
You're welcome 😊

Alright, I will try with 3.1.2 and the new 3.2.x version. Many thanks!

**Comment by maksymgendin** [comment]
3.1.2 works 🚀

**Comment by maksymgendin** [comment]
@PacoVK You could close my issue as duplicate to #1291

**Comment by PacoVK** [comment]
Thanks again for the report. I'll close this now as duplicate to #1291 :)
