### ISSUE TITLE
publishToConfluence - a source code block containing template parameters has formatting problems

### ISSUE THREAD

**Issue by stehlih** [docToolchain/docToolchain#1349]
docToolchain V3.2.0 tested with Confluence 8.6.2

Source code blocks containing template parameters are not correct transfered to Confluence.

The following AsciiDoc code block is formatted correct with HTML or PDF output.

```
[source, csharp]
----
public class ComplexModel : IModel
{
    private readonly ILoggerFactory loggerFactory;
    private readonly ILogger<ComplexModel> logger;

    ComplexModel( ILoggerFactory loggerFactory, ... )
    {
        this.loggerFactory = loggerFactory;
        logger = loggerFactory.CreateLogger<ComplexModel>();
        ...
    }
}
----
```

On Confluence the template parameters are all lowercase and at the end we can see some html statements.

```
public class ComplexModel : IModel
{
    private readonly ILoggerFactory loggerFactory;
    private readonly ILogger<complexmodel> logger;
 
    ComplexModel( ILoggerFactory loggerFactory, ... )
    {
        this.loggerFactory = loggerFactory;
        logger = loggerFactory.CreateLogger<complexmodel>();
        ...
    }
}</complexmodel></complexmodel>
```
![ConfluenceOutput](https://github.com/docToolchain/docToolchain/assets/43820014/cbd32a57-3aeb-4386-967d-06aba0c2791c)

**Comment by PacoVK** [comment]
Thanks for reporting, i did take a look and confirmed you found a bug. Thats awesome and i will provide a fix soon :)

**Comment by stehlih** [comment]
It works now with V3.3
