### ISSUE TITLE
publishToConfluence - some code blocks are generated as txt instead of requested language and loose linebreaks

### ISSUE THREAD

**Issue by tkleiber** [docToolchain/docToolchain#1355]
**Describe the bug**
We try to change from doctoolchain from 2.1.0 to 3.2.2.
We have some html code blocks, which are generated in 3.2.2 as txt block instead of the used markup.

**To Reproduce**
1. Use following code

```
[source, html]
----
<af:button id="_exc" icon="/adf/ikb.adf.basis.ui/images/excel.gif">
           <af:exportCollectionActionListener type="excelHTML"
                                               exportedId="_t1"
                                               exportedRows="all"
                                               filename="termine.xls"
                                               title="Kundenbezogene Termine"/>
</af:button>
----
```
2. Generate with 2.1.0 to Confluence, you see html output:

![2_1_0](https://github.com/docToolchain/docToolchain/assets/2185441/e6de99b6-1717-410e-9f09-ffcb779d96d4)

3. Generate with 2.1.0 to Confluence, you see txt output and removed linebreak:

![3_2_2](https://github.com/docToolchain/docToolchain/assets/2185441/1044106e-fd37-4b10-b849-3f9051ef3f0b)

**Expected behavior**
The code block should be formatted in the requested language definition and should show all linebreaks, which exists in the code.

**Screenshots**
See above

**Configuration**
 - docToolchain version: 3.2.2
 - OS: SuSE Enterprise Linux
 - Browser: Edge
 - Relevant SDK Versions: openjdk version "17.0.9" 2023-10-17

**Comment by PacoVK** [comment]
Thanks for reporting, i took a closer look and it relates to #1349 i will provide a fix soon for that :)
