### ISSUE TITLE
publishToConfluence: java.io.FileNotFoundException: /docToolchain-3.3/core/src/main/groovy/org/docToolchain/scripts/asciidoc2confluence.groovy

### ISSUE THREAD

**Issue by tkleiber** [docToolchain/docToolchain#1372]
**Describe the bug**
Execution failed for task ':publishToConfluence'.
> java.io.FileNotFoundException: /docToolchain-3.3/core/src/main/groovy/org/docToolchain/scripts/asciidoc2confluence.groovy (/docToolchain-3.3/core/src/main/groovy/org/docToolchain/scripts/asciidoc2confluence.groovy)

**To Reproduce**
1. Unzip [docToolchain-3.3.zip](https://github.com/docToolchain/docToolchain/releases/download/v3.3/docToolchain-3.3.zip)
2. There is no core directory below doctoolchain anymore, so the error seems to be correct

**Expected behavior**
doctoolchain should not reference this file if moved to somewhere else or it should not give this error.

**Screenshots**
-

**Configuration**
 - docToolchain version: 3.3
 - OS: SLES 15.4
 - Relevant SDK Versions [e.g. JDK 1.8, ...]: openjdk version "17.0.9" 2023-10-17

**Comment by PacoVK** [comment]
@tkleiber thanks for reporting. This is a bug and I will prepare a new release to fix that soon 👍
