### ISSUE TITLE
spaceKey not optional

### ISSUE THREAD

**Issue by tafli** [docToolchain/docToolchain#1374]
According to the [documentation](https://github.com/docToolchain/docToolchain/blob/ng/docToolchainConfig.groovy#L173), the option `spaceKey` is optional. As soon as I delete/comment the configuration key from the confluence configuration, the `publishToConfluence`-Task fails with following error

```
> Task :publishToConfluence FAILED


* Where:
Script '/home/dtcuser/docToolchain/scripts/publishToConfluence.gradle' line: 69

* What went wrong:
Execution failed for task ':publishToConfluence'.
> No signature of method: org.docToolchain.scripts.asciidoc2confluence$_run_closure3.call() is applicable for argument types: (ConfigObject) values: [[:]]4 actionable tasks: 2 executed, 2 up-to-date

  Possible solutions: any(), any(), doCall(java.lang.String), each(groovy.lang.Closure), tap(groovy.lang.Closure), any(groovy.lang.Closure)
```

When commenting out the optional option, `subpagesForSections` the task works as expected.

Using DTC Version 3.2.2. 

Any hints on that?

The whole confluence configuration looks as following (comments stripped):

```groovy
confluence.with {
    input = [
            [ file: "build/html5/main.html",  ancestorId: '1234567890' ],
    ]

    api = 'https://<path/to/confluence>/rest/api/'
   
    //spaceKey = '<spaceKey>'

    subpagesForSections = 1 

    pagePrefix = ''
    pageSuffix = ''

    pageVersionComment = ''
    extraPageContent = '<ac:structured-macro ac:name="info"><ac:parameter ac:name="title" /><ac:rich-text-body> Inhalt ist generiert, bitte nicht direkt editieren.</ac:rich-text-body></ac:structured-macro>'

    enableAttachments = false

    pageLimit = 100

    export = [
            srcDir: 'sample_data',
            destDir: 'src/docs'
    ]
}
```

**Comment by PacoVK** [comment]
Hey @tafli thanks for reporting. The reference in the docs you saw that spacekey is optional is within the input settings. You can specify a spacekey per input file, but that is optional. If no spacekey is defined on file level the global spacekey (the one you commented in the example) will be used. 
The global spacekey is always required and is used as default. 
Does it make sense? 😊

**Comment by tafli** [comment]
So I have misunderstood this comment. In that case, it makes absolutely sense. Thanks for clarifying.
