### ISSUE TITLE
publishToConfluence task erroneously replaces HTML special characters in code blocks

### ISSUE THREAD

**Issue by houserockr** [docToolchain/docToolchain#1377]
### Problem description

Whenever we use the `publishToConfluence` task to upload our document to our **self-hosted** confluence instance, special HTML characters within (C++) code blocks are replaced where they shouldn't be replaced.

Example code block in markdown:

```markdown
.Example
[source, cpp]
----
vector<string> read_until(const string& terminator)
{
    vector<string> res;
    for (string s; cin >> s && s != terminator; ) // read a word
        res.push_back(s);
    return res;
}
----
```

And here's a screenshot of the rendered result in confluence:

![Screenshot 2024-02-29 at 16 46 34](https://github.com/docToolchain/docToolchain/assets/8655705/1d62d85a-44ea-420b-8ed4-29fcf1193c94)

Is this a bug or is there any other way to tell the `publishToConfluence` task **not** to convert HTML special chars within code blocks?

**Note**: The HTML generated by the `generateHTML` task does not have this problem.

### Environment
- Confluence 8.5.6 self-hosted
- Doctoolchain 3.2.2 **local**
- OS: MacOS 14.3.1

**Comment by PacoVK** [comment]
@houserockr tganks for reporting. just to put it into context, did you use a docToolchain version like 2.x and it worked or did you just start working with docToolchain. That would help to find a starting point for the bug you discovered ☺️✌️

**Comment by houserockr** [comment]
@PacoVK thank you for getting back to me!
We've been using doctoolchain for 4 years, but only the `generatePDF` and `generateHTML` tasks.
Recently, we introduced confluence so we thought we'd give the `publishToConfluence` task a try.
So we don't have any positive or negative history with that unfortunately.

**Comment by PacoVK** [comment]
no worries :) i also did not recognize that you tried v3.2.2. The issue you see is related to #1349  which was fixed in v3.3 (i could also verify that) 
<img width="1055" alt="grafik" src="https://github.com/docToolchain/docToolchain/assets/27785614/48488031-698b-48d8-9158-761b8e1d41fd">

I will try to create another release soon, because unfortunately there was also some issues in v3.3. Stay tuned, i will let you know asap as the new release is there :)

**Comment by PacoVK** [comment]
Here it is @houserockr please give 3.3.1 a try and let me know if that solves your issue 🏥

**Comment by houserockr** [comment]
@PacoVK wow that was quick. Thank you very much. I will try it with 3.3.1 monday ... 🙏

**Comment by houserockr** [comment]
Works with 3.3.1
![Screenshot 2024-03-05 at 12 38 33](https://github.com/docToolchain/docToolchain/assets/8655705/1de338d8-c1e2-4ad0-8b5c-4ba81ab4b255)
