### ISSUE TITLE
generateHTML: All images are now embedded (starting with Release v3.0.1)

### ISSUE THREAD

**Issue by MichaelRossner** [docToolchain/docToolchain#1390]
**Describe the bug**
If I use images (local or remote) they used to be linked into the document - with version prior to v3.x.
Starting with [Release v3.0.1](https://doctoolchain.org/docToolchain/v2.0.x/030_news/2023/3.0.1-release.html) images are now embedded.

This leads to quite large documents that are - e.g. in GitLab - not readable anymore:

`This content could not be displayed because it is larger than 10.00 MiB. You can [download it](<document>?ref_type=heads) instead.`

**To Reproduce**
- create a simple document with 
```
image::ea/<model_name>/SW_Overview.png["Overview", title="Overview"]
image::https://<confluence>/confluence/download/attachments/1565356904/67eaded3b0443fef2b2e322166a421fb.png["Overview2"]
```
- run `./dtcw docker generateHTML`

- all images are now embedded - making the document quite large
```
<div class="imageblock">
<div class="content">
<img src="[data:image/png;base64,iVBORw........AAASUVORK5CYII=)" alt="Overview">
</div>
<div class="title">Figure 1. Overview</div>
</div>
</div>
<div class="imageblock">
<div class="content">
<img src="[data:image/png;base64,iVBOR...AAElFTkSuQmCC)" alt="Overview2">
</div>

````

**Expected behavior**
I would like to have the same generated result as with docToolchain v2.x again:

```
<div id="component_overview" class="imageblock">
<div class="content">
<img src="[/project/src/docs/images/ea/<model_name>/SW_Overview.png](view-source:file:///project/src/docs/images/ea/<model_name>/SW_Overview.png)" alt="Overview">
</div>
<div class="title">Figure 1. Overview</div>
</div>
<div class="imageblock">
<div class="content">
<img src="[https://<confluence>/confluence/download/attachments/1565356904/67eaded3b0443fef2b2e322166a421fb.png](view-source:https://<confluence>/confluence/download/attachments/1565356904/67eaded3b0443fef2b2e322166a421fb.png)" alt="Overview2">
</div>
```

**Configuration**
 - docToolchain version: tested with
   - v3.0.1
   - v3.1.0
   - v3.2.2
   - v3.3.1
 - OS: Ubuntu 20.04.6 LTS
 - Browser: Firefox
 - Relevant SDK Versions: use docker images

**Additional context**
- :data-uri: was not set or even sometimes explicitly not set (:!data-uri:)

**Comment by PacoVK** [comment]
Hey @MichaelRossner thanks for raising this issue. I think it clearly states that me miss some documentation here. Starting with `3.x` we introduced [`failOnMissingImages`](https://doctoolchain.org/docToolchain/v2.0.x/030_news/2023/3.0.0-rc1.html#_added) configuration. If you set this property to `false` the behaviour is the same as it was prior to `3.x` versions. Mind that missing images do not lead to build failures (unfortunately this is related to turning embedded images on). 

You could change the setting in your `docToolchainConfig.groovy` 
```
failOnMissingImages = false
```
alternatively you can set it via CLI using `-PfailOnMissingImages=false` 

This setting sets/ unsets :data-uri: for the asciidoc converter

**Comment by MichaelRossner** [comment]
Hello @PacoVK,

Thanks a lot for the explanation. That is a dependency I didn't realize.

I tried it and with `failOnMissingImages = false` I again get smaller files with images that are linked.

Thanks.
