### ISSUE TITLE
Generate a chapter based on Architecture Decision Record

### ISSUE THREAD

**Issue by jakubjab** [docToolchain/docToolchain#140]
In the spirit of living documentation, decisions are sometimes stored in a repository as a separate file per decision, see:
https://github.com/joelparkerhenderson/architecture_decision_record

I would like to tell doctoolchain where my decisions are stored, what is the format (or could be detected automatically), where they should end up. In case of arc42, for example in chapter 9.

**Comment by rdmueller** [comment]
what could be a solution?
Currently, you can write the decisions as separate docs and include them all in an overarching document.

So, would it be a solution to automatically add those documents to the overarching document?

Example: you have a manually edited document called `decisionlog.adoc` and several decisions in files called `decisionlog/decision[0-9].adoc`. The system could recognize that these docs belong together, could check if the subdocuments are already referenced from the main document and if not, append an `include::decisionlog/decision[0-9].adoc[]` statement. Problem would be the right level offset, but an offset of +1 could do the trick.

What do you think?

**Comment by rdmueller** [comment]
hm. I think the `collectIncludes` Task solves this old issue:
https://doctoolchain.github.io/docToolchain/#_collectincludes

@jakubjab what do you think?

**Comment by rdmueller** [comment]
let's close this as it seems that collectIncludes solves it.
