### ISSUE TITLE
Jira links substitution is not working after migrating from 2.1.0 to 3.3.1

### ISSUE THREAD

**Issue by ndaniskas** [docToolchain/docToolchain#1411]
**Describe the bug**
After migrating from v2.1.0 to v3.3.1 I noticed that the Jira link substitution stopped working.

**Expected behavior**
If we use for example `jira:ARC-102[]` in our adoc src file, when we run the task `generateHTML` the resulting HTML files should have the above part replaced with the Jira link pointing to our Jira server.

**Configuration**
 - docToolchain version: 3.3.1 Docker image

**Comment by rdmueller** [comment]
@PacoVK , do you know what could cause the problem?

**Comment by PacoVK** [comment]
Hm, so far there was no change to the code in that area, but upgrading from `2.1.0` to `3.3.1` has some major changes in many places. I need a bit of more context here: 
* Do you have any logs that warn/ error out?
* Could you show the diff of the (redacted) config you used in `2.1.0` and then migrated to `3.3.1` 
* Did you verify that switching back from `3.3.1` to `2.1.0` worked as expected again? 

Maybe we can dig from here then for the root cause :)

**Comment by ndaniskas** [comment]
Hi @PacoVK and thanks for the prompt reply.

There were no obvious warnings or errors related to this.
I will post a diff asap.
Switching back to my previous code version which is using 2.1.0 works just fine.

> Note: I was searching on the repository but I cannot find:
https://github.com/docToolchain/docToolchain/blob/2b57f5a43f0f682d00e6809cf27b073a3d1aad74/scripts/asciidoc2confluence.groovy#L450 in the v3.1.0. Could this be the case?

**Comment by ndaniskas** [comment]
A diff on the config produced nothing. The files are identical.

**Comment by PacoVK** [comment]
okay, thanks for the info. I prepared a reproducer and try to reproduce the issue as soon as i find a little time. I will update the issue with my findings :)

**Comment by ndaniskas** [comment]
Hello @PacoVK,
did you have any time to look at the issue? Can I assist somehow?

**Comment by PacoVK** [comment]
Hey @ndaniskas unfortunately I have been sick the whole week and still recovering. I hope to be able to work on this next week. 😊

**Comment by ndaniskas** [comment]
No issues @PacoVK. I hope that you get well soon. 🍀

**Comment by PacoVK** [comment]
UPDATE: i reproduced the bug, i found the bug (was introduced in `2.2.1`) and i found a solution. Now i am working on a proper implementation, that streamalignes the config that is needed to make this work, to further optimize and stabelize this functionality. Unfortunately i cannot give an estimate yet, but i will work on this, and hopefully finish soon.

**Comment by rdmueller** [comment]
great work! I guessed it was introduced with the core. So I was totally wrong 😲

**Comment by PacoVK** [comment]
it actually was introduced when we updated the ascidoctor gradle plugin, this was even before the core :P

**Comment by ndaniskas** [comment]
Thank you so much for all your efforts so far. I am looking forward for the fix!

**Comment by ndaniskas** [comment]
One last question. In which version will the fix be available?

**Comment by rdmueller** [comment]
if you build local, you can always specify "latest" as version. 
We could create a new version for this fix, but I can't say when I will find the time...
