### ISSUE TITLE
Tests fail for JDK 21

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#1419]
https://github.com/docToolchain/docToolchain/actions/runs/10004519491/job/27653356357

> Task :core:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileGroovy'.
> BUG! exception in phase 'semantic analysis' in source unit '/home/runner/work/docToolchain/docToolchain/core/src/main/groovy/org/docToolchain/atlassian/confluence/ConfluenceService.groovy' Unsupported class file major version 65

@PacoVK - do you already have an idea?

**Comment by PacoVK** [comment]
We use Gradle 8.1.1 but Java 21 is supported since [8.4](https://docs.gradle.org/8.4/release-notes.html) I started the upgrade on #1298 but this is a tricky one, and i am not sure if we can make due to dependency issues

**Comment by rdmueller** [comment]
ok, so if this is gradle releated, let's stop all efforts to upgrade
