### ISSUE TITLE
gradle dependencies not found

### ISSUE THREAD

**Issue by ambition-consulting** [docToolchain/docToolchain#1424]
**Describe the bug**
on any operation, I get:

dtcw 0.50 - ##DTCW_GIT_HASH##
docToolchain 3.1.1
OS/arch: Linux/x86_64
Available docToolchain environments: local
Environments with docToolchain [3.1.1]: local
Using environment: local
Using Java 17.0.9-ea [/usr/bin/java]
Using headless mode since there is no (terminal) interaction possible
Downloading https://services.gradle.org/distributions/gradle-8.1.1-bin.zip
...........10%............20%............30%............40%............50%............60%............70%............80%...........90%............100%
Welcome to Gradle 8.1.1!
Here are the highlights of this release:
 - Stable configuration cache
 - Experimental Kotlin DSL assignment syntax
 - Building with Java 20
For more details see https://docs.gradle.org/8.1.1/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
FAILURE: Build failed with an exception.
* Where:
Build file '/root/.doctoolchain/docToolchain-3.1.1/build.gradle' line: 101
* What went wrong:
A problem occurred evaluating root project 'docToolchain'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration 'classpath'.
      > Could not find org.ysb33r.gradle:grolifant:0.12.
        Searched in the following locations:
          - https://plugins.gradle.org/m2/org/ysb33r/gradle/grolifant/0.12/grolifant-0.12.pom
        If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
        Required by:
            unspecified:unspecified:unspecified > org.asciidoctor:asciidoctor-gradle-jvm-gems:4.0.0-alpha.1 > com.github.jruby-gradle:jruby-gradle-core-plugin:2.0.2
      > Could not find com.burgstaller:okhttp-digest:1.10.
        Searched in the following locations:
          - https://plugins.gradle.org/m2/com/burgstaller/okhttp-digest/1.10/okhttp-digest-1.10.pom
        If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
        Required by:
            unspecified:unspecified:unspecified > org.asciidoctor:asciidoctor-gradle-jvm-gems:4.0.0-alpha.1 > com.github.jruby-gradle:jruby-gradle-core-plugin:2.0.2 > io.github.http-builder-ng:http-builder-ng-okhttp:1.0.3

and sure enough, https://plugins.gradle.org/m2/org/ysb33r/gradle/grolifant/0.12/grolifant-0.12.pom and https://plugins.gradle.org/m2/com/burgstaller/okhttp-digest/1.10/okhttp-digest-1.10.pom
 returns a 404

**Comment by rdmueller** [comment]
please uograde to 3.4.0 - this should fix the problem

**Comment by ambition-consulting** [comment]
confirmed
