### ISSUE TITLE
Fetching `com.github.johnrengelman.shadow` plugin fails when running dtcw task on Linux-based Azure DevOps CI/CD Pipeline Agent

### ISSUE THREAD

**Issue by arnoan** [docToolchain/docToolchain#1432]
**Describe the bug**
I am working on setting up a docToolchain based documentation process for my team.

I am running into a "plugin xyz was not found" error, when trying to run any DTC Gradle task orchestrated by `./dtcw` on an Azure DevOps CI/CD Pipeline (which runs in an on-premise linux agent). 

The error I am getting is:

```
dtcw 0.51 - ##DTCW_GIT_HASH##
docToolchain 3.3.1
OS/arch: Linux/x86_64
Available docToolchain environments: local docker
Environments with docToolchain [3.3.1]: local docker
Using environment: local
Using Java 17.0.11 [<sensitive>/JDK/jdk-17/bin/java]
Using headless mode since there is no (terminal) interaction possible
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

* Where:
Build file '<sensitive>/.doctoolchain/docToolchain-3.3.1/core/build.gradle' line: 3

* What went wrong:
Plugin [id: 'com.github.johnrengelman.shadow', version: '8.1.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:8.1.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

I tried running the tasks with `--info` and `--debug` and `--scan` but the output somehow remains the same, no additional information ist shown. I am using a company-internal proxy repository, so I adjusted the `mavenRepository` and `depsMavenRepository` URLs in `gradle.properties`. Access to the internal proxy repositories is verified to work. 

When running locally (on a Windows 11 host) with the adjustments to target the internal proxy everything works as intended. 

I have spent many hours trying to debug this error but I am out of ideas, so I ask here in the hope that someone might have a pointer what could be going wrong. Alternatively, is there maybe a way to "pre-fetch the `'com.github.johnrengelman.shadow'` plugin" and make it available to DTC/Gradle manually?

**To Reproduce**
1. Install DTC on a Linux-based Azure DevOps agent
```
  - script: |
      # Install DTC Locally
      ./dtcw local install doctoolchain
    displayName: Install DTC Locally
```

-> This works

2. Try running `any` `./dtcw` command (can be display of tasks, generation of PDF, or any other task..)

```
  - script: |
      ./dtcw local tasks --info
    displayName: Display all available tasks
```
-> This will result in the error above that the `com.github.johnrengelman.shadow` plugin can't be obtained.

**Expected behavior**
I expect that DTC would obtain/find the relevant plugin via the URLs provided in `gradle.properties`

**Configuration**
 - docToolchain version: 3.3.1
 - OS: Linux
 - Java: 17.0.11

**Additional context**
I am primarily a Python-Developer/Data Engineer/MLOps person and not deeply knowledgeable about Java/Gradle/Maven so it could be I might be missing something obvious. Any pointers are highly appreciated.

Many thanks in advance 🙏 and also big kudos for this amazing project! 👏

**Comment by MatteoBenholz** [comment]
We have a similar issue, would be interesting if you have found a solution yet?

**Comment by rdmueller** [comment]
@PacoVK do we use the shadow plugin for the fat jar of the core module? Shouldn't it be already be as a fat jar in the distribution?

**Comment by rdmueller** [comment]
@arnoan have you already tried other versions? 2.2.1? 3.4.0?
I never experienced this problem

**Comment by arnoan** [comment]
@MatteoBenholz 
I haven't found a solution yet, no. But I will continue to dig deeper into this early next week and report back as soon as I identify the cause/manage to get it to work.

@rdmueller 
Thanks for your reply. So far I haven't tried with other versions, no. I will give it a go next week and report back. 
~~Is 3.4 considered "stable" for general use already?~~ Update: Just saw that 3.4 was released in July. Will definitely try the newer version then and see if it maybe directly fixes the issue.

**Comment by PacoVK** [comment]
> @PacoVK do we use the shadow plugin for the fat jar of the core module? Shouldn't it be already be as a fat jar in the distribution?

yes, i can confirm it should already be there as fat jar... 
@arnoan can you please confirm that after you installed docToolchain `<your-home-folder>/.doctoolchain/docToolchain-3.3.1/libs/org/docToolchain/core-3.3.1.jar` exists? If that file would be missing the `core` project will be build again, thus trying to download its dependencies, which the shadow plugin is one of them

With the steps you described i cannot reproduce it either unfortunately.

**Comment by arnoan** [comment]
@PacoVK 
You diagnosis seems correct. The `/.doctoolchain/docToolchain-3.3.1/libs/org/docToolchain/core-3.3.1.jar` file isn't present. In fact the whole `/.doctoolchain/docToolchain-3.3.1/libs/` folder is not present.

That said, I did get it working in the meantime.

The crucial part was setting 
```
repositories {
    maven { url = "https://<url-to-internal-repository>/gradle_plugins" }
}
```
explicitly in both `build.gradle` and `core/build.gradle`.

---

Now regarding _why_ the `libs` directory doesn't exist and thus the core project is being re-built which - as I understand now - is different in my case, than for most DTC users. 

This is likely because we work with a full local fork of the upstream DTC repo. Both as an internal backup and also as some company-specific modifications were required. (For example in `core/src/main/groovy/org/docToolchain/scripts/asciidoc2confluence.groovy` I made some tweaks to display the correct URL to the published page for our internal Confluence configuration.)

Thank you @rdmueller and @PacoVK for your support in identifying the cause.

For everyone that uses the "default/vanilla" installation of DTC that is already "pre-compiled" into a "fat jar" the issue I described in the begining should not arise.

**Comment by arnoan** [comment]
@MatteoBenholz 
Are you still facing a similar issue? If so, I'm happy to try and help trouble-shoot with the knowledge I gained in the past weeks. For us, docToolchain is working smoothly on an Azure DevOps Self-Hosted Agent now.

**Comment by arnoan** [comment]
I'm closing this issue, as my initial problem is solved and the issue I was facing isn't something that affects a default DTC install. Many thanks again to everyone for the support. And the valuable docToolchain project.

**Comment by ingomaas** [comment]
The Gradle Shadow plugin has a new home, new maintainers, and a new ID:

https://gradleup.com/shadow/
https://github.com/GradleUp/shadow
https://plugins.gradle.org/plugin/com.gradleup.shadow

`id("com.gradleup.shadow") version "9.1.0"`
