### ISSUE TITLE
'generateDock' picks up taskHistory.lock from gradle and fails with invalid byte sequence error 

### ISSUE THREAD

**Issue by egoexpress** [docToolchain/docToolchain#144]
## Expected behavior and actual behavior.

_generateDeck_ should, well, generate some sort of slide deck. However, it fails on the unchanged arc42 template as it picks up a `taskHistory.lock` file (supposedly from gradle, which is binary) when parsing the asciidoc files.

## Steps to reproduce the problem.

Jus run _generateDeck_ in a directory just initialized with _initArc42DE_ (should hold for EN as well).

```
$ ../doctoolchain/bin/doctoolchain . generateDeck

> Configure project :
compiling with Java 1.8.0_151 at 22:30:47
docDir: /home/wonder/Development/arc42
mainConfigFile: Config.groovy
inputPath: .
inputFiles: [[file:arc42-template.adoc, formats:[html, pdf, docbook]]]
outputPath: build
/home/wonder/Development/arc42/build/ppt/images

> Task :generateDeck
Converting /home/wonder/Development/arc42/src/08_concepts.adoc
[..]
Converting /home/wonder/Development/arc42/.gradle/4.3.1/taskHistory/taskHistory.lock
(ArgumentError) asciidoctor: FAILED: /home/wonder/Development/arc42/.gradle/4.3.1/taskHistory/taskHistory.lock: Failed to load AsciiDoc document - invalid byte sequence in UTF-8

```

## Specifications like the version of the project, operating system, or hardware.

Checked used the current Git version of Doctoolchain (bcbccca62e00ee78365fbbfa55339da16fb06e3f).

**Comment by jakubjab** [comment]
Indeed there is a problem, for me it's failing because it's trying to process some other files it shouldn't:

```
Converting /Users/jablonsj/tmp/arc42_2/Config.groovy
Converting /Users/jablonsj/tmp/arc42_2/images/05_building_blocks-EN.png
(ArgumentError) asciidoctor: FAILED: /Users/jablonsj/tmp/arc42_2/images/05_building_blocks-EN.png: Failed to load AsciiDoc document - invalid byte sequence in UTF-8
```

I don't know enough about revealjs, but I can have a look.

**Comment by jakubjab** [comment]
Seems the problem is when revealjs is not specified in the formats in the Config.groovy, but generateDeck is called. The same happens when I remove html and call generateHTML.
I have a test case reproducing that problem.

@egoexpress - as a workaround before it's fixed you can add revealjs to the list of formats, in addition to html, pdf and docbook.

**Comment by rdmueller** [comment]
Maybe we should add an example which can be used as slide deck...

**Comment by egoexpress** [comment]
@jakubjab Thanks for the workaround, at least now the build runs without errors.

@rdmueller I guess an example for the slide deck part would be a good addition. I see more people like me going through the documentation, running every command after each other to see what output is created. Currently everybody using this method will stumble at the _generateDeck_ part.

**Comment by rdmueller** [comment]
I think the `demo.pptx` already contains all data. I have to check this.

So, a `greadlew exportPPT generateDeck` could do the trick.

I will check how we can update the manual to reflect this.

**Comment by jakubjab** [comment]
See the proposed fix in #150 .

**Comment by jakubjab** [comment]
@egoexpress - can we close this bug now after #150? It's still not perfect, I would prefer some warning instead of just skipping task, but it's not trying to convert random files at least.

**Comment by egoexpress** [comment]
@jakubjab Yeah, I guess this bug can be closed.
