### ISSUE TITLE
publishToConfluence: Internal links broken with v3.4.1

### ISSUE THREAD

**Issue by MichaelRossner** [docToolchain/docToolchain#1447]
**Describe the bug**
When changing from version v3.3.1 to v3.4.1 the internal links (e.g. chapter names) are broken and are replaced by a "createpage" link.

example of correct link (with v3.3.1):
`https://<company>/confluence2/display/<spacename>/<page-title>#id-<section>`

example of broken link (with v3.4.1):
`https://<company>/confluence2/pages/createpage.action?spaceKey=<spacename>&title=<page-title>+&linkCreation=true&fromPageId=<page-id>`

The TOC is working though.

The links are correctly working in the generated HTML pages.
The links to external pages are also still working.

**To Reproduce**

- make use of links to page chapters
- create page internal references via [[makro]]

**Expected behavior**
Internal links work.

**Screenshots**

Working links:
![2024-09-24_09h29_56](https://github.com/user-attachments/assets/3fb521d4-19b0-4469-a1dc-395152e5d2bc)

Broken links:
![2024-09-24_09h29_47](https://github.com/user-attachments/assets/4d33844a-0f78-4b73-a9e4-42d52cdd8bc6)

**Configuration**
 - docToolchain version: v3.4.1
 - OS: [e.g. Windows, Linux, ...]: Linux - using dtcw container.
 - Browser [e.g. chrome, safari]: Edge
 - Relevant SDK Versions [e.g. JDK 1.8, ...] 

**Additional context**
Reverting the version back to 3.3.1 immediately solves the problem.

**Comment by rdmueller** [comment]
@PacoVK do you have any idea what could cause this?

**Comment by PacoVK** [comment]
I try to reproduce and check if I can find something. Not sure if I can make it already this week 😊

**Comment by MichaelRossner** [comment]
Thanks - let me know if I can support.

**Comment by PacoVK** [comment]
Quick update: Yet i could reproduce and also narrow it down to the code that causes the issue. However, i now need to understand why this behaves like it does on Confluence. Once i understood i can fix this :) 
The cause of the evil is exactly this [line of code](https://github.com/docToolchain/docToolchain/blob/v3.4.1/core/src/main/groovy/org/docToolchain/atlassian/transformer/LinkTransformer.groovy#L37)

**Comment by MichaelRossner** [comment]
Thanks for the progress update. Good to hear that you are closing in on it.
