### ISSUE TITLE
publishToConfluence: page search is unstable

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#146]
the search for existing pages is quite unstable which results in errors "page already exists"

Most problems I experience are the result of special charcters `:` or `-` within the page title.

Maybe we can drop the confluence search in favour of our own search by first fetching all pages under the given root?

**Comment by davidmc24** [comment]
I've also experienced this problem.  At least for my purposes, it looks to me like it works better when I replace the line
`        def cql = "space='${confluenceSpaceKey}' AND type=page AND title~'" + realTitle(pageTitle) + "'"
`
with
`        def cql = "space='${confluenceSpaceKey}' AND type=page AND title='" + realTitle(pageTitle) + "'"`
(tilde to equals sign in the title criteria).

**Comment by davidmc24** [comment]
Digging into the docs a bit, it looks like the [contains operator (~)](https://developer.atlassian.com/server/confluence/advanced-searching-using-cql/#contains) supports using [Confluence text-search syntax](https://developer.atlassian.com/display/CONFDEV/Performing+text+searches+using+CQL) for the right-hand side, which is based on [Lucene Query Parser Syntax](https://lucene.apache.org/core/4_4_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html).  In particular, both : and - are considered [special characters](https://lucene.apache.org/core/4_4_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Escaping_Special_Characters), and should be escaped with a backslash to use them literally.

**Comment by rdmueller** [comment]
hm. if it is lucene, we should be able to get a list of characters which have to be escaped, shouldn't we?

and in regards to ~ vs. =, I am not sure why we use '~' - maybe we didn't escape special characters and then where only able to match the title with the contains operator? I guess I have to check the commit history... maybe a blame could work...

**Comment by bodewig** [comment]
see #161 - we started using `~` instead of `=` in order to get case insensitive search. Over there I suggested using a phrase but was unsure whether quotes are matched in a case insensitive way, quoting wouldn't run this risk.

**Comment by rdmueller** [comment]
ah - right. The problem was that we easily duplicated pages when we fixed the case on a headline...

**Comment by rdmueller** [comment]
I think we have to restructure the confluence code into functions in order to cover it with unit tests which document the functionality in more details.
what do you think?

**Comment by davidmc24** [comment]
Here's an example of one way we might consider restructuring the code to promote testability.  Here, I've ported the scripts to classes in buildSrc.

If we head in this direction, we might not want to publish the full source of the various modules in the documentation any more.

While this approach allows for a more conventional development approach (ability to specify dependencies in buildSrc/build.gradle, ability to easily define classes in multiple files, ability to test classes independently), it also introduces an explicit "compile" stage for the classes, and by default runs the unit tests prior to running any main task (as part of the buildSrc project build).  If we like the developer experience but not running the build as part of generating/publishing documentation, we could consider packaging as a binary plugin.

https://github.com/davidmc24/docToolchain/tree/restructure-confluence-support

**Comment by rdmueller** [comment]
@davidmc24 great, that's already a good start.

And yes, we should remove some full source references and replace them with links to the sources. But I still stink that these references help to understand the modules and enable contributions, don't they?

Here are some of my (unstructured) thoughts:
- the scripted plugin allows to easily change, fix and update functionality. The many contributions prove this 
- thanx to a hackergarten at gr8conf, we already have a plugin for pandoc. We could use this as a blueprint for further binary plugins
- there is a maven plugin which also converts asciidoc to confluence: https://github.com/alainsahli/confluence-publisher . It would be great if we could merge both projects (@cstettler). But a huge difference is the java vs groovy style of both projects...
- the publishToConfluence module is one of the modules which needs a config. It would be great if we could consolidate the configs...

**Comment by davidmc24** [comment]
@rdmueller Pointing out which file/classes are most relevant to a given function (whether by link to git source file or just by name) is indeed useful for potential contributors, but may be largely noise for non-contributor users.  I'm not sure what the ratio of those user types is for this project.  If you're going to be contributing, you're going to need a full git clone and potentially even to configure an IDE project, at which point I'm not sure that having source links in the docs makes much of a difference at all.

By the way, I'm perfectly fine with throwing out my branch above if the project wants to stick to the script plugin approach.  I mostly wanted to see how difficult it would be to port, and allow comparison of the approaches.

**Comment by cstettler** [comment]
Thanks for the mentioning of https://github.com/alainsahli/confluence-publisher, @rdmueller! Referring to the ongoing discussion on the docToolchain Slack channel, I am convinced that the use of the AsciiDoc Confluence Publisher as part of docToolchain would provided added value when it is about publishing to Confluence. As agreed, we should compare the feature set and the publishing approach taken and see where the fit / gap is.

In addition to the Maven plugin, we also provide a Docker image and a pure Java command line client for publishing. The latter could easily be invoked from any script, being it Bash or Groovy. What is for sure still open is the alignment of the source documentation structure between both projects, or more specific an `AsciidocPagesStructureProvider` implementation that fits the source documentation structure assumed / supported by docToolchain. I am looking forward to the discussed feature list  for comparison, @rdmueller ;-).

With regard to the "stability" of the Confluence search, we decided in the AsciiDoc Confluence Publisher not to use the search at all, instead use the Confluence API to get access to existing pages. In case the title of a page changes, the old orphaned page gets deleted and a new page is added. This leads to a loss of the history of that page, but implements a stable and deterministic approach for publishing.

**Comment by rdmueller** [comment]
As far as I know, this is solved by now. Please re-open if you don't think so.
