### ISSUE TITLE
Add progress indicator/logging for 'allPages' fetch in publishToConfluence task

### ISSUE THREAD

**Issue by eoliphan** [docToolchain/docToolchain#1468]
**Is your feature request related to a problem? Please describe.**
With large spaces this fetching can take some time, and the user has no indication that docToolchain is actually working

**Describe the solution you'd like**
Logging per block of pages would probably suffice:  "X (or X of Y) pages retrieved", etc

**Describe alternatives you've considered**
None, this is opaque to the end user

**Additional context**
N/A

**Comment by PacoVK** [comment]
Thanks for this input, I think it makes sense and is an easy improvement. 👍
