### ISSUE TITLE
create class diagrams from source for docs

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#157]
see https://twitter.com/accreativos/status/975142484308316161 for details of the idea.

**Comment by gernotstarke** [comment]
QDOX parses java text - and imho therefore cannot currently handle other JVM languages...

imho another approach would be to integrate with [ArchUnit](https://archunit.org) to visualize architecture rules

**Comment by rdmueller** [comment]
I've seen tools which already create diagrams from source which can be included in the docs.
structurizr is one of them.
I guess we don't need an additional approach, so I will close this now
