### ISSUE TITLE
Some PlantUML diagrams appear to have strange layouts

### ISSUE THREAD

**Issue by davidmc24** [docToolchain/docToolchain#165]
## Expected behavior and actual behavior.

When said diagrams are rendered directly using plantuml, they have a reasonable layout, but render notably differently when rendered via doctoolchain.  In one example, doctoolchain rendering adds significant vertical space.

## Steps to reproduce the problem.

`$DOCTOOLCHAIN_HOME/bin/doctoolchain . generateHTML --no-daemon` on a project with an impacted plantuml diagram.  I don't know what characteristics cause a diagram to be impacted.

## Specifications like the version of the project, operating system, or hardware.

From my experimentation, it appears that upgrading "org.asciidoctor:asciidoctorj-diagram" from 1.5.4.1 to 1.5.8 resolves the issue.

**Comment by rdmueller** [comment]
thanx for the detailed report and hint on how to solve this problem!

now that it seems you've already found the proplem, would you mind to create a pull request with the new version number? 

I would really appriciate your contribution!

**Comment by davidmc24** [comment]
Sure thing!
