### ISSUE TITLE
Support for asciidoc text formatting in Confluence export

### ISSUE THREAD

**Issue by davidmc24** [docToolchain/docToolchain#167]
## Expected behavior and actual behavior.

My expectation was that if source documents used [text formatting](http://www.methods.co.nz/asciidoc/chunked/ch10.html) the formatting would carry over to Confluence.  While the classes are carried over, currently the styles associated with those classes aren't defined in the Confluence version, resulting in various formatting effectively being ignored.

## Steps to reproduce the problem.

Create a document that includes text formatting such as
```
[red]#Obvious# and [big red yellow-background]*very obvious*.
[underline]#Underline text#, [overline]#overline text# and
[blue line-through]*bold blue and line-through*.
```

* Run `$DOCTOOLCHAIN_HOME/bin/doctoolchain . generateHTML publishToConfluence`
* Open the page in Confluence, and see whether it has the expected formatting

## Specifications like the version of the project, operating system, or hardware.

Tested on version f8145b87af96b992397e7ab24217fcd295349c7b on a MacBook Pro running MacOS Sierra, though I doubt it's platform specific.

## Other notes

This may not be something that can be "fixed" in all situations.  As far as I can tell, default Confluence installations strip out a bunch of HTML tags.

I've got a version that appears to make it work by grabbing the first `style` element from the HTML version, and includes it in each page using a [Confluence html macro](https://confluence.atlassian.com/doc/html-macro-38273085.html).  However, said macro is disabled by default.  If desired, I can share those changes.

**Comment by rdmueller** [comment]
what happens with your changed code when the mentioned macro is not enabled? Will it break the output or will it just be the same as at the moment?

**Comment by davidmc24** [comment]
I'll investigate that and get back to you.

**Comment by davidmc24** [comment]
I've tested with Confluence 6.9.1.  It appears that if the mentioned macro is not enabled, the page will include a "unknown macro" warning, which is undesirable.

![image](https://user-images.githubusercontent.com/447825/41983453-23298938-79fc-11e8-9cdb-a586b95e1684.png)

While investigating, I came across the ability for space admins to configure a custom stylesheet for their space.  This might be an interesting alternative to document for users who lack admin access and/or can't get approval to enable the HTML macro.

For instances where the HTML macro is enabled, having it automatically "just work" (without manual per-space Confluence configuration) still sounds appealing to me.  I'm going to look into whether there are APIs to detect whether the HTML macro is enabled, as that would allow the desired behavior without an additional configuration setting.

**Comment by davidmc24** [comment]
Nope, no such REST APIs.  I think that leaves the options as:

1. Document how to configure space stylesheets
2. Add a configurable (enabled/disabled, default of disabled) feature to include the styles in each page that needs them via the html macro
3. Both 1 and 2
4. Do nothing

I'm open to pursuing a pull request for any of the above options.

**Comment by rdmueller** [comment]
have you tried to wrap the text in spans and use inline styles? At least, that's the way confluence changes the font color...

**Comment by rdmueller** [comment]
just gave it manually a try - this works for changing the background color and could work for even more...

**Comment by davidmc24** [comment]
While doing inline style rules is something that I believe would likely work, I was hoping to avoid having to identify and maintain every permutation of styling rule that Asciidoc supports and having rules in asciidoc2confluence to convert the classes to inline styles (if I'm understanding your suggestion correctly).

**Comment by davidmc24** [comment]
After some further testing, I found that my original planned approach (just include the whole default asciidoctor stylesheet in the page) wouldn't work, as some of the styles included conflict with default Confluence styling.

While there are a number of asciidoctor features that may display differently without the stylesheet, I think that the ones that are most likely to appear "broken" to document authors are the lack of styles for the built-in roles.  These also look to be unlikely to conflict with anything in Confluence.  Thus, I've put together a pull request to document how to apply these styles manually to a given space.

**Comment by davidmc24** [comment]
Merging #171 addressed this to my satisfaction.  Closing.

**Comment by rdmueller** [comment]
perfect. thanx for your support!
