### ISSUE TITLE
get docToolchain listed on WriteTheDocs

### ISSUE THREAD

**Issue by gernotstarke** [docToolchain/docToolchain#168]
http://www.writethedocs.org/guide/docs-as-code/

especially our (common) workshops, and our (German) series of articles.

**Comment by rdmueller** [comment]
so, basically this would be a PR for this page: https://github.com/writethedocs/www/blob/master/docs/guide/docs-as-code.rst

**Comment by rdmueller** [comment]
PR got accepted. cool :-)
