### ISSUE TITLE
Proposal: Sample multi-project Gradle build with docToolchain

### ISSUE THREAD

**Issue by asaremba** [docToolchain/docToolchain#178]
After having read the article series in Javamagazin, I have written and deployed a sample documentation with Asciidoc and Gradle (in a real life customer project). Worked great. Thank you!

My next step would be to make this reusable (for me and others). To be really useful, it should work in a multi-project build with minimal redundance, i.e. as much as possible of the build logic should reside in the root project's build file. My first attempt today was not successful, but I have limited experience with Gradle so far.

A simple example project (e.g. root + 2 sub-projects) demonstrating the correct approach would be very helpful.

**Comment by rdmueller** [comment]
Thanx for the feedback! I am glad that you could make use of your article series.

You are absolutely right - we need more examples to make it even easier to use the toolchain.
There are several approaches and all are a bit different:

- stand-alone installed as `doctoolchain` command
- multi project build (that's currently my favorite, but afaik, there are still some glitches)
- just added to the already existing project build (that was my approach when I started and I still like it)

But time is limited. So if you want to come up with a sample project, maybe together with a blog post... :-)

**Comment by rdmueller** [comment]
see also https://github.com/docToolchain/docToolchain/issues/162
and
https://github.com/aim42/htmlSanityCheck/issues/216

htmlSanityCheck will be the sample project. 
Tutorial has to be written.

**Comment by rdmueller** [comment]
htmlSanityCheck makes good progress as sample project:
https://github.com/aim42/htmlSanityCheck branch RC3
tutorial will follow

**Comment by rdmueller** [comment]
so, htmlSanityCheck is now a good example and on https://docs-as-co.de/getstarted/tutorial2 you'll find a tutorial.

Feedback would now be appreciated! :-)

**Comment by jstallkamp** [comment]
Thank you very much. 

I encountered two issues when following the tutorial on Windows 10 (using gradle wrapper)

1. When running `gradle tasks` after creating an empty `Config.groovy: `

```
D:\temp\tutorial1>gradlew tasks

> Configure project :docToolchain
docDir: .
mainConfigFile: Config.groovy
inputPath: [:]
inputFiles: [:]
outputPath: [:]


FAILURE: Build failed with an exception.

* Where:
Script 'D:\temp\tutorial1\docToolchain\scripts\AsciiDocBasics.gradle' line: 69

* What went wrong:
A problem occurred evaluating script.
> Could not normalize path for file 'D:\temp\tutorial1\docToolchain\.\[:]'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

D:\temp\tutorial1>
```
After copying the suggested content to `Config.groovy`, `gradle tasks` yields the expected output. 

2. After modifying `build.gradle` to configure the docToolchain's `docDir`, I get the following:

```
D:\temp\tutorial1>gradlew tasks

> Configure project :docToolchain
docDir: ../.
mainConfigFile: Config.groovy


FAILURE: Build failed with an exception.

* Where:
Script 'D:\temp\tutorial1\docToolchain\scripts\AsciiDocBasics.gradle' line: 25

* What went wrong:
A problem occurred evaluating script.
> ..\.\Config.groovy (Das System kann die angegebene Datei nicht finden)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

D:\temp\tutorial1>
```
Obviously, changing `docDir` to `.` removes the error, but causes docToolchain to use the docToolchain directory as `docDir` (since its identical to not adding the code to `build.gradle` in the first place).

**Comment by rdmueller** [comment]
thanx. that is great feedback!
I will try to fix this as soon as I can.

**Comment by LilMouse** [comment]
I have the doctoolchain submodule working with one root project and the doctoolchain! But I am trying to integrate it in a way that I have one root project and multiple subprojects that each need to run the generatePDF task, all with their own configs. Is there a way to integrate that with this submodule?
So I now have
- root
  - src
  - doctoolchain
  - subproject
    - src
Is that is any way possible with this module without initializing the toolchain in every subproject?

**Comment by jstallkamp** [comment]
> thanx. that is great feedback!
> I will try to fix this as soon as I can.

Any news about the Windows bug? I'd really like to use doctoolchain (as a clean, separate submodule), but unfortunately I am not gradle-savvy enough to fix this myself.

**Comment by rdmueller** [comment]
sorry, time it quite limited, so I couldn't do more work on this exact issue.
Since so many things have been advanced with docToolchain by now, I guess this issue is outdated and I will close it.
