### ISSUE TITLE
exportEA does not respect docDir

### ISSUE THREAD

**Issue by jstallkamp** [docToolchain/docToolchain#179]
## Expected behavior and actual behavior
**Expected:** The exportEA task scans the `docDir` for EAP files and exports images and notes files within `docDir`
**Actual:** The exportEA task scans the docToolchain root directory for EAP files and exports images and notes files relative to it.

## Steps to reproduce the problem.
In docToolchain root directory, run `bin\doctoolchain.bat <docDir> exportEA` , with `<docDir>` being the documentation's top-level directory (external to the docToolchain directory)

## Specifications like the version of the project, operating system, or hardware.
docToolchain-master, commit a42f81f

**Comment by rdmueller** [comment]
thanx for the report. I will take a look at it!

**Comment by rdmueller** [comment]
this should be fixed with the latest push - please reopen if you tests fail...
