### ISSUE TITLE
Folder pdfTheme missing

### ISSUE THREAD

**Issue by funkr** [docToolchain/docToolchain#190]
## Expected behavior and actual behavior.
All default targets should run without any error including the pdf generation.
Currently pdf generation is failing because pdfTheme folder and pdf-theme.yml file is missing in the repository

## Steps to reproduce the problem.
Run the default configuration from git.

## Specifications like the version of the project, operating system, or hardware.
latest version, Windows 10

**Comment by funkr** [comment]
Hi Ralf, I can help much with this gradle stuff, but if you need some help with testing just raise your hand. I would volunteer.

**Comment by rdmueller** [comment]
so, it seems that with the release version, the pdfTheme is ok (but the PDF generator has problems to find some images)...
So I guess I introduced this problem while fixing the tests... :-(

**Comment by funkr** [comment]
To ease the testing I wrong you a little bash script to test if the generation was successful from a fresh clone.
[dtc-int-test.sh.gz](https://github.com/docToolchain/docToolchain/files/2408581/dtc-int-test.sh.gz)

**Comment by rdmueller** [comment]
that's great. thanx!

**Comment by rdmueller** [comment]
we should include this in the travis script...

**Comment by funkr** [comment]
BTW. the tag V1.0.0 generates pdf and html, 
but some pictures are missing in html and pdf

![missing_in_pdf](https://user-images.githubusercontent.com/32101377/45926638-cedbb300-bf25-11e8-88e9-39a76a3073ee.PNG)
![missing_in_html](https://user-images.githubusercontent.com/32101377/45926639-d7cc8480-bf25-11e8-83ca-b5d0386ff1ac.png)

**Comment by rdmueller** [comment]
yes, I am currently also working on this. We have to come up with a stable configured version and then do a new release :-|

**Comment by rdmueller** [comment]
btw: do you mind if you create a PR for your shell script with the script stored in `docToolchain/src/test/bash/.`? I would then try to include it in the travis build...

**Comment by rdmueller** [comment]
so, I have a fix for the `generatePDF` command in regards to the `pdfTheme` folder. Now I will try to fix the images

**Comment by rdmueller** [comment]
it seems that the images are also missing in the html version...

**Comment by rdmueller** [comment]
found the problem with the images: since they are exported from EA, the where part of the `.gitignore`
changed `.gitignore` and added the images.

**Comment by rdmueller** [comment]
now, there is still a problem with those images... the new EA version doesn't export them nicely...
I'll try to fix that also...

**Comment by rdmueller** [comment]
see PR #192
