### ISSUE TITLE
integrate draw.io

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#194]

**Comment by gernotstarke** [comment]
cool idea!

**Comment by rdmueller** [comment]
just got some code up and running (not checked in yet) using the jgraphx / mxGraph library. 
It is kind of hard to work with it and the result is not usable (html in the shape text and most shapes do not render at all).
So I created a SO question with a cry for help :-)

https://stackoverflow.com/questions/53951770/render-png-image-from-draw-io-xml-file-in-java

**Comment by rdmueller** [comment]
argh. just noticed that this was wasted time:

if you work with draw.io, just work with `.png` files:
- Export as PNG, tick the box 'include a copy of my diagram'
- when you change the diagram, just open this PNG
- all save operations will be performed on this PNG!

So, there is no need to do a conversion in order to integrate draw.io with asciidoc!!!! :-)

**Comment by rdmueller** [comment]
see https://doctoolchain.github.io/docToolchain/#_exportdrawio

**Comment by jaredmorgs** [comment]
I'm going to put in a bit more procedural direction in this section because I hit a wall when trying to follow along from what is currently written. I'll reference this bug when I'm writing it.

**Comment by rdmueller** [comment]
@jaredmorgs thanx. I am curious about your thoughts

**Comment by jaredmorgs** [comment]
@rdmueller I have submitted the PR. I have not yet built the docs just in case changes are required. 

I also don't have gradle configured on my PC, but I'm willing to do it if required. I just wanted to get the words written before worrying about building.
