### ISSUE TITLE
add reading time, contributors and feedback

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#209]
see https://docs.microsoft.com/en-us/style-guide/welcome/ as example

**Comment by ghp-dev** [comment]
Calculating the reading time in minutes - in it's simplest form - seems to be dividing the article's [word count by 184](https://iovs.arvojournals.org/article.aspx?articleid=2166061)

Shall it be possible to add the reading time to any asciidoc file?

If so, would you consider a [block processor](https://asciidoctor.org/docs/asciidoctorj/#block-processor) for asciidoctorJ ?

```java
public Object process(AbstractBlock parent, Reader reader, Map<String, Object> attributes) { 
     
```
Would it be possible to get the document's word count (eventually) from the `AbstractParent` of the processed block?

**Comment by rdmueller** [comment]
The block processor could be a solution. But to be honest, I can't find too much good documentation on those plugin functionality that I already gave up to write a proper asciidoc plugin.
The 2.x version of the Gradle DSL might be better documented.

Have you seen my hacked `exportContributors` script? I guess we could add the reading time in there :-)

What do you think?

**Comment by ghp-dev** [comment]
Created #246 

Could use support on the following issues:

* unicode character is not displayed correctly
  `println("\u023F1")` on the Terminal in  my IntelliJ IDEA only used the `\u023F` part.

  Any suggestions?

* I still have many unresolved dependencies:
![bildschirmfoto vom 2018-11-29 01-30-07](https://user-images.githubusercontent.com/41126650/49191363-8f42a480-f376-11e8-9394-a085db10262d.png)

Any suggestions, where I could check my IDE's setup?

**Comment by rdmueller** [comment]
@ghp-dev sorry, I didn't see your question :-(
I guess you've fixed it by now?

There is now a basic implementation of the reading time in `exportContributors`, so I will close this ticket now
