### ISSUE TITLE
publishToConfluence broken

### ISSUE THREAD

**Issue by andreasbenzing** [docToolchain/docToolchain#218]
## Expected behavior and actual behavior.

Running the `publishToConfluence` task should work as described in the [docs](https://doctoolchain.github.io/docToolchain/#_publish_to_confluence)

Instead, `ConfluenceConfig.groovy` is not read. After adding it manually to the respective gradle file, I experienced a number of issues because the variables are inconsistently named. For example, `config.confluence.api` instead of `config.confluence.confluenceAPI`.

Am I missing something?

## Steps to reproduce the problem.

Set up ARC from scratch and try to publish.

**Comment by rdmueller** [comment]
Hi! Thanx for reporting this issue.

Have you tried to download the "release" version? https://github.com/docToolchain/docToolchain/releases

I've worked a bit on the master branch lately to make things better. One feature is that the `Config.groovy` and `ConfluenceConfig.groovy` have been merged, but the docs haven't been updated yet.

So, the current `publishToConfluence` should read the config from the main `Config.groovy` file.

this tutorial might be helpful to you: https://docs-as-co.de/getstarted/tutorial1

and yes, the documentation for the `publishToConfluence` task is currently not very much... that's also something we are working on. 

Thank you for your patience! ... and keep on reporting issues - I will try to help as much as I can...

**Comment by rdmueller** [comment]
have you seen this part of the documentation?

https://doctoolchain.github.io/docToolchain/#_publishtoconfluence

**Comment by andreasbenzing** [comment]
I went with https://doctoolchain.github.io/docToolchain/#_publish_to_confluence first. For section 3.6, the question would be where that `publishToConfluence.gradle` should be located. The one in the project looks quite different.

My fix was to rename config variables in `asciidoc2confluence.groovy` and use `confluenceConfigFile` in `publishToConfluence.gradle`.

Haven't tried the release, yet.

**Comment by PacoVK** [comment]
The docs are up to date and work for newer versions. Hence, we close this issue :)
