### ISSUE TITLE
publishToConfluence internal link targets

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#223]
explicit internal link targets seem to be rendered as links in confluence.
See https://arc42-template.atlassian.net/wiki/spaces/HSC/pages/503349258/1.1.+Requirements+Overview

![image](https://user-images.githubusercontent.com/1856308/47957734-e47bd800-dfbb-11e8-9ee2-c9ce05fc226e.png)

**Comment by d3rdud3** [comment]
Good evening, 

do you know since which version or commit, this bug is present ? I remember this feature working in the past. I would like to "downgrade" until there is a fix.

Thank you very much

**Comment by rdmueller** [comment]
I guess it was always there. The workaround seems to be not to set the `:sectanchors:` attribute:
https://asciidoctor.org/docs/user-manual/#anchors

**Comment by d3rdud3** [comment]
Wow thank you for the really fast feedback... 
I've just downgraded to commit b12e46544a0 from 26 Jun 2018 and after publishing to confluence, the bug is gone for now. I'll take this as a working workaround for now but I will also try your solution. Thanks for your help and have a nice evening.

**Comment by rdmueller** [comment]
thanx for the info. I will compare both versions and see if I can find what makes the difference...

**Comment by d3rdud3** [comment]
You're welcome, this is a great tool. I'm glad if I can help somehow ;)

**Comment by rdmueller** [comment]
Thanx! Feedback is always welcome!

I compared the two versions, but I can't find a difference which could be the problem.
I guess the problem is this line: https://github.com/docToolchain/docToolchain/blame/master/scripts/asciidoc2confluence.groovy#L467

docToolchain generated the following xhtml:

```
<br />
<ac:structured-macro ac:name="anchor" ac:schema-version="1" ac:macro-id="4ce96723-8d99-420c-a4a1-58bdeee30d88"><ac:parameter ac:name="">
  _basic_usage
 </ac:parameter></ac:structured-macro>

<h1>
 <ac:link ac:anchor="_basic_usage">
  <ri:page ri:content-title="1.1. Requirements Overview" ri:version-at-save="3" />
  <ac:plain-text-link-body>
   
  </ac:plain-text-link-body>
 </ac:link>1.1.1. Basic Usage</h1> 
``` 
 
while confluence create something like this:

```
<br />
<ac:structured-macro ac:name="anchor" ac:schema-version="1" ac:macro-id="7599ee32-0474-4d96-9bd2-43870e225082"><ac:parameter ac:name="">  
 _basic_usage </ac:parameter></ac:structured-macro>
</p>

<h1>1.1.1. Basic Usage</h1>
```

so, this looks like the problem could be in this line:
https://github.com/docToolchain/docToolchain/blame/master/scripts/asciidoc2confluence.groovy#L223

both changes are from 2 years ago...

Maybe the problem is not a change in docToolchain but a change in Confluence?

**Comment by rdmueller** [comment]
I think I've got it...

**Comment by rdmueller** [comment]
@d3rdud3  can you please give it a try to see if it works for you?

**Comment by rdmueller** [comment]
I just gave it a try: works on my machine :-)
