### ISSUE TITLE
generateHTML does not find source

### ISSUE THREAD

**Issue by ghp-dev** [docToolchain/docToolchain#228]
Unfortunately I could'nt get the current version working:
 
## Expected behavior and actual behavior.
expected: produce html output in build/html5
actual: build directory structure is not created when using
current version from master branch.
Debug output shows "NO-SOURCE" for task "generateHTML"
But Arc42template seems to be correctly initialized, though.

Version 1.0.0 is working though

## Steps to reproduce the problem.
clone github repo with 
```
git clone --recursive https://github.com/docToolchain/docToolchain.git
rm -rf .git
rm -rf resources/asciidoctor-reveal.js/.git
rm -rf resources/reveal.js/.git
```
export PATH

initialize from scratch and build with 
```
./gradlew -b init.gradle initArc42EN -PnewDocDir=../test

doctoolchain ../test  generateHTML
```

## Specifications like the version of the project, operating system, or hardware.

OS: Ubuntu 18.04.1 LTS

Versions: arc42 and doctoolchain from yesterday (november, 7th)
Java:

openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)

**Comment by rdmueller** [comment]
thanx. I will look into this later today.
until then you could try to use the v1 from the releases tab in this repository...

**Comment by rdmueller** [comment]
btw: NO-SOURCE sounds to me like the source to convert hasn't been configured in `Config.groovy`.
we now have a small tutorial which you might find helpful: https://docs-as-co.de/getstarted/tutorial2

**Comment by ghp-dev** [comment]
Hi Ralf
thank you for putting so much effort into solving problems, I'm facing too.

I tried out the tutorial https://docs-as-co.de/getstarted/tutorial2
It worked with some (very) minor hickups:
```
mkdir tutorial1 
cd tutorial
``` 

the last command is missing a '1'


`gradle init`produces a nice settings.gradle file (in folder tutorial1). The next command `echo "include 'docToolchain'" > settings.gradle` overwrites it's content with the one-liner.

Did you mean to append the 'include' statement instead with `>>`?

After issuing the following commands:
```
cd doctoolchain

bin/doctoolchain /absolute/path/to/tutorial1/ generateHTML
```

The output showed some (neglectable) warnings:
```
A problem was found with the configuration of task ':generateHTML'. Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated and is scheduled to be removed in Gradle 5.0.

 - Directory '/absolute/path/to/tutorial1/src/docs/images' specified for property '$1' does not exist.
unsupported Java version "10", defaulting to 1.7
Converting /absolute/path/to/tutorial1/src/docs/test.adoc
```

but I was able to successfully generate the HTML for `test.adoc`.

After that I repeated the whole procedure for the current master branch (without checking out tags/V1.0.0) and that worked too.

**Comment by ghp-dev** [comment]
Hi Ralf,
I found the culprit:
when following https://doctoolchain.github.io/docToolchain/#_how_to_install_doctoolchain
the task 
```
./gradlew -b init.gradle initArc42EN -PnewDocDir=myDocDir
```
will unpack the adoc files to `myDocDir` and `myDocDir/src`
but
https://github.com/docToolchain/docToolchain/blob/master/gradle.properties

expects the files to be located under `src/docs`
setting `inputPath = .`
solved it for me.

After that I tried generatePDF.
I adjusted gradle.properties and set `pdfThemeDir = ./pdfTheme`

The task failed with an exception.

Do you want me to follow-up on this in another issue?

**Comment by rdmueller** [comment]
Hi! These findings are great!
I knew there would be still some bugs in the tutorial 😞

would you like to create pull request for these issues? It you don't know how, I will assist you...

**Comment by ghp-dev** [comment]
Yep sounds like a plan.

In preparation for that:

What do you think ?

Would it be better to 
* adjust the "initialize from scratch" to `src/docs` or
* to change all current occurrences of `src/docs`?

Are there other stakeholders which we could invite into this discussion?

**Comment by ghp-dev** [comment]
@rdmueller I will create a PR for tutorial1.adoc

**Comment by ePex** [comment]
I just had the same issue. Wouldn't this fix the Problem? https://github.com/ePex/docToolchain/commit/cff27df45e2cefb47ce8dd53fe709257c5ec6002 

I cloned the docToolchain repo like this: 
git clone --recursive https://github.com/docToolchain/docToolchain.git
rm -rf .git
rm -rf resources/asciidoctor-reveal.js/.git
rm -rf resources/reveal.js/.git
cd docToolchain

initialize from scratch and build with

./gradlew -b init.gradle initArc42EN -PnewDocDir=/absolute/path/to/my/project/src/docs

doctoolchain /absolute/path/to/my/project/src/docs generateHTML

**Comment by ghp-dev** [comment]
Thanks @ePex  for looking into this. 

Applying your fix improved the situation:

 generateHTML worked with adoc sources on top level. :+1: 

But: 
* an (empty) src/docs folder has automatically been created
* I was not yet able  really choose a folder structure to my liking with Config.groovy alone.

I will test some more and provide feedback. But perhaps we should follow up with that discussion in #229.
