### ISSUE TITLE
exportPPT fails with exception on Linux

### ISSUE THREAD

**Issue by ghp-dev** [docToolchain/docToolchain#231]
## Expected behavior and actual behavior.
Expected: 

Extract asciidoc from ppt when using task exportPPT on Linux.
If this task is not supported, clearly state so in the documentation.

Actual:

[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.io.IOException: Cannot run program "cmd": error=2, Datei oder Verzeichnis nicht gefunden

## Steps to reproduce the problem.
run `doctoolchain . generatePPT` on linux from a directory containing the attached pptx file in folder src/docs. 
[InputSlides.pptx](https://github.com/docToolchain/docToolchain/files/2568803/InputSlides.pptx)

## Specifications like the version of the project, operating system, or hardware.
OS: Ubuntu 18.04.1 LTS

Versions: arc42 and doctoolchain from november, 7th

Java:

openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)

**Comment by rdmueller** [comment]
Thanx for reporting this. I guess powerpoint is not installed on your system?

This task uses visual basic script to export the slides and presenter notes. 
AFAIK, there is no library like Apache POI which is cable of doing this.

For the `exportExcel` task, we've used Apache POI - that why this task runs with Linux.

I've already opened issue #226 to fix the documentation - feel free to submit a PR for the docs of the exportPPT task :-)

How to work around this... 

The task is intended for architects which use PPT to present their ideas - if you work on Linux, you probably use something else for presentation - then it would make sense to create an exporter for this other tool.

If you use PPT on a windows machine but want to build your docs on a linux system - extract the slides on your windows machine to the `src/docs` folder and version them along with your other docs. 
This enables you to build the docs on a linux system.

Is it best practice to check in those generated files? 
At least, it has several advantages: 
* you do not depend on proprietary software to build your docs - you can even build them when your licence runs out or your switch to another tool
* you can better diff images and text than the binary formats.

**Comment by ghp-dev** [comment]
This SO question has some answers on how to execute vbs on linux:
e.g.
https://stackoverflow.com/a/31305027

basically they are recommending wine. 

Would this be feasible or would the additional dependency on wine be violating exitisting intentions?

Will create a PR for the docs 2morrow

**Comment by rdmueller** [comment]
Wine would be feasible if you run PPT on wine.
We already try to run the `exportEA` task on wine and I am collecting some experience with this.

A while ago I did some experiments with openOffice to export PPT but as I remember it was a bit harder - you can only do some kind of HTML export and don't have control of the image resolution which was (as I remember) quite low.

**Comment by rdmueller** [comment]
just read through the SO answers: the experiments with the `exportEA` task show that VBS runs on wine and has access to the COM objects...

**Comment by ghp-dev** [comment]
For the docs test repo I'm currently using that is linux only. Except for VS code I don't have any MS products on that machine. The pptx attached above has been created with Libreoffice. If the gradle task works together with wine, then I think there is no need for Powerpoint on linux or wine.

**Comment by rdmueller** [comment]
Do you think that Libreoffice implements the MS PPT COM interfaces?

**Comment by ghp-dev** [comment]
Hmm, don't know. A quick lookup only turned up this here:

https://api.libreoffice.org/examples/examples.html

and a sun COM interface:

https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1presentation.html

**Comment by ghp-dev** [comment]
I made a  PR. 

I've updated 
src/docs/manual/03_task_exportPPT.adoc

Building produced warnings about unresolved references therefore I did not replace the files in the docs folder. Could you please look into this?

**Comment by ghp-dev** [comment]
> AFAIK, there is no library like Apache POI which is capable of doing this.
> For the `exportExcel` task, we've used Apache POI - that why this task runs with Linux.

As for the docs, Apache POI should be capable of exporting PPT/ PPTX slides as well.
https://poi.apache.org/components/slideshow/xslf-cookbook.html

I would love to provide the code for that.
Alas, I would like to thoroughly test the solution on my local machines.
Currently I'm struggling with setting up my IDE for developing docToolchain.

Before I go down the wrong rabbit hole:
* Is the recommended dev approach already documented somewhere?
* Is IntelliJ Community Edition sufficient?

**Comment by rdmueller** [comment]
great work! Have you also seen an api method to export the speaker notes?

**Comment by ghp-dev** [comment]
https://poi.apache.org/apidocs/dev/org/apache/poi/xslf/usermodel/XSLFSlide.html#getNotes--

[Here](https://poi.apache.org/components/slideshow/quick-guide.html) it reads:

> first create a org.apache.poi.hslf.usermodel.HSLFSlideShow (from a org.apache.poi.hslf.usermodel.HSLFSlideShowImpl, which accepts a file or an input stream). Use getSlides() and getNotes() to get the slides and notes.

I guess pptx will be more or less the same.
Unfortunately the apis for ppt and pptx differ. 
I'd like to focus on pptx first....

**Comment by ghp-dev** [comment]
this command 
```
java -cp ./lib/*:ooxml-lib/*:./* org.apache.poi.xslf.util.PPTX2PNG ./sample.pptx
```
sucessfully exports all slides as images. 
In 4.0.0 it works for presentations with and without themes.
Additional to png also gif and jpg is supported.
output can be scaled and restricted to a range of slides

Would you prefer 
a) executing the above commandline (would require the POI binaries to be available on the resources path)
Or
b) accessing pptx2png from Java code?

**Comment by rdmueller** [comment]
great progress!
I guess focus on pptx is fine. I wonder if it would make sense for the time being to add switches to the config on which implementation to use... ?

regarding the pptx2png:
This is part of POI? Cool!
I think it makes sense to call it just from a groovy task as java/groovy code. The exportToExcel task already uses the POI dependency.

A call like `PPTX2PNG.main(['./sample.pptx'])` should do the trick, shouldn't it?

BTW: One requirement for my code was that the {slide}-tag in the notes gets replaced with the `image::slidename.png[]` pattern. This way, you can for instance write something like this

```
//tag::arc_overview[]
{slide}
//end::arc_overview[]
```

which lets you easily import the correct slide (even if some slides before are added or removed) to your docs by using the tag...

I don't know if we can achieve this with the `PPTX2PNG` out of the box or if we have to add the notes export... 

What do you think?

**Comment by ghp-dev** [comment]
> I wonder if it would make sense for the time being to add switches to the config on which implementation to use... ?

I don't think that's necessary yet: the existing VBScript task is called exportPPT and this one could be called exportPPTX

> I think it makes sense to call it just from a groovy task as java/groovy code.
ACK
>  The exportToExcel task already uses the POI dependency.

OK, but we would need to bump up that dependency to 4.0.0 then

> A call like `PPTX2PNG.main(['./sample.pptx'])` should do the trick, shouldn't it?

I think so, yes. Could not yet check it. Don't have the doctoolchain environment running yetin IDEA (unresolved symbols)

> BTW: One requirement for my code was that the {slide}-tag in the notes gets replaced with the `image::slidename.png[]` pattern. 
> I don't know if we can achieve this with the `PPTX2PNG` out of the box or if we have to add the notes export...

Well, notes export is out of scope for the PPTX2PNG utility.
But since we'll be calling the utility from code, it should be easy to add notes export to the groovy task.
Each note should has a page ID which should be corresponding to the index of the slide image  we exported.

Off-by-one, I guess ;-)

**Comment by rdmueller** [comment]
I guess we can copy and paste this java code into a gradle task - should run fine as groovy code...

Shall I give it a try?

**Comment by ghp-dev** [comment]
Well, my plan's to provide a PR for this until end of this week (in groovy and with spock spec)

**Comment by rdmueller** [comment]
perfect. so I leave my hands off the keyboard for now 😁

**Comment by uniqueck** [comment]
Hi guys,

I would like to know what is the status off this issue and if i can help.
For me this would be a create feature to get this also working on linux machines.

**Comment by uniqueck** [comment]
Hi guys,

i would like to bump it up. I created a asciidoctor-office-extension that extract slides as images and embbeded it directly to AsciiDoc. So the problem should be solved. Should i add a point in the documentation, that it so a extension exist and what you have to down to use it? The extension is also listed on the official site of [AsciiDoctor](https://asciidoctor.org/docs/extensions/).

**Comment by rdmueller** [comment]
wow. haven't visited this issue for a long time.
@uniqueck I still have your extension in mind and I know that we first have to upgrade the asciidoctor version in use. But I would like to close this issue for now, because I think the original issue has been solved.
