### ISSUE TITLE
add several issue templates

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#239]
like these: https://github.com/gitpod-io/gitpod/tree/master/.github/ISSUE_TEMPLATE

**Comment by ghp-dev** [comment]
(How) may I help you out on this one?

I tested adding the Issue templates on my fork. 

That was an easy process (given the access privileges)

The  [templates](https://github.com/gitpod-io/gitpod/tree/master/.github/ISSUE_TEMPLATE) you referenced above seem to be stripped down versions of the default ones used by the github Template Builder...

e.g. the github default template for Bug Report (this citation lost the text formatting when pasting here...)
```
 Issue: Bug report 
Create a report to help us improve

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]
Smartphone (please complete the following information):

Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Browser [e.g. stock browser, safari]
Version [e.g. 22]
Additional context
Add any other context about the problem here.
```

**Comment by ghp-dev** [comment]
Let me know, when I can help with something

**Comment by rdmueller** [comment]
oh, that's great! My goal was to have different templates because the current one does not always fit.
So if you already have this on your fork - I would be happy about a PR!

**Comment by ghp-dev** [comment]
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
seems to indicates .github/ as a valid directory

So IMHO it should be possible to move the PR-Template.

What are you referring to, when talking about 'the original template' ?

**Comment by rdmueller** [comment]
there is this "original" template still in the root folder: ISSUE_TEMPLATE.md

I giess I'll find some time later today to move these templates...

**Comment by ghp-dev** [comment]
Oh my, sometimes I do miss the obvious, you know. With the forste and the trees...
PR: #247

**Comment by rdmueller** [comment]
perfect. thanx. I think we can close this now...
