### ISSUE TITLE
Initializing and building arc42EN template as described in the docs does not produce HTML output

### ISSUE THREAD

**Issue by pmatyszok** [docToolchain/docToolchain#259]
**Describe the bug**
Initializing and building arc42EN template as described in the docs does not produce HTML output. Following steps described here: https://doctoolchain.github.io/docToolchain/#_how_to_install_doctoolchain in steps 2.1-2.3 ends with no output generated and message: 
```
:generateHTML NO-SOURCE

BUILD SUCCESSFUL in 1s
```

**To Reproduce**
1. ` git clone --recursive https://github.com/docToolchain/docToolchain.git docToolchain`
2.  `cd docToolchain/`
3. `rm -rf .git`
4. `rm -rf resources/asciidoctor-reveal.js/.git`
5. `rm -rf resources/reveal.js/.git`
6. `./gradlew -b init.gradle initArc42EN -PnewDocDir=arc42`
7. `./bin/doctoolchain arc42 generateHTML`
8. See:
```
:generateHTML NO-SOURCE

BUILD SUCCESSFUL in 1s

```
No build folder created.

**Expected behavior**
`build` folder created with sources generated inside.

**Configuration**
 - Windows 7 x64
- docToolchain run using "git-bash" - MINGW64

I am happy to help investigate this. Later I mangled a bit with settings, but it is hard to wrap the head arround the fact that they are splitted across `gradle.properties`, `Config.groovy` and can be overriden via commandline - not sure when and where the `inputPath` prop should be defined.

**Comment by pmatyszok** [comment]
Yes, it did. The files were sucessfully unzipped:
![image](https://user-images.githubusercontent.com/3974142/50688413-acc5f680-1025-11e9-9c15-14e5ee9e01f7.png)

**Comment by pmatyszok** [comment]
Missclick with closing the issue...

**Comment by rdmueller** [comment]
thanx for reporting this bug.
can you show us your `Config.groovy`? It seems that the template to be rendered is not configured the right way.

**Comment by pmatyszok** [comment]
I am attaching two files. One is `Config.groovy` from master directory, where docToolchain was check-out, and the other one, that is inside `arc42` directory. Btw. the `arc42` directory resides inside the docToolchain directory, but **not** in src directory (that is how the `initArc42EN` task created it).


docToolchain master config: [Config.groovy.txt](https://github.com/docToolchain/docToolchain/files/2727018/Config.groovy.txt)
arc42 config: [Config .groovy.txt](https://github.com/docToolchain/docToolchain/files/2727022/Config.groovy.txt)

I had to change the extension to .txt in order for github to digest it.

**Comment by pmatyszok** [comment]
I think the problem is not with `docDir`, as this is being overriden when issueing the command `./bin/doctoolchain arc42` - from the brief analysis of the script the `$1` parameter is being passed as `docDir`. In my opinion the `inputPath` parameter defined in `gradle.properties` is problematic. But I was not able to obtain sucessful build by modyifin the `inputPath` as well. 

Does this project have some test run of documentation build? Maybe this would shed me some light on how to use parameters properly.

**Comment by rdmueller** [comment]
So, it it has to do with the gradle properties, I guess I know when and why I changed it the last time.
Hope I will find some time today to have a look at it.

meanwhile: have you already taken a look at this tutorial? https://docs-as-co.de/getstarted/tutorial2

it describes another approach.
you currently install docToolchain as command line tool.

the tutorial describes how to use it as submodule i. your project.

another workaround (until I fix the current situation) could be to fall back to the v1.0 tag: https://github.com/docToolchain/docToolchain/releases

**Comment by pmatyszok** [comment]
I have not seen this tutorial yet. I was using only information gathered here: https://doctoolchain.github.io . I will give it a try. 

Later on I can support with writing the part of documentation on doctoolchain.github.io on how to perform first run and/or be the tester of initial configuration.

**Comment by rdmueller** [comment]
update of the docs is always welcome!
we somehow have to switch to docs / tutorials which are part of the automated tests...

**Comment by rdmueller** [comment]
@pmatyszok you are correct:

the `inputPath` in `gradle.properties` has to be set to `.` instead of `src/docs` to make it work again.

So, now that have the root case, I have to check what else will be broken by this change....

**Comment by pmatyszok** [comment]
Hm, for sure changing `inputPath` to `.` in `gradle.properties` change a bit. The task no more complains that there are no sources to process, instead it yields:

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':generateHTML' property 'sourceDir' during up-to-date check.
> Failed to create MD5 hash for file content.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
1 actionable task: 1 executed

```
I can't even spot the `sourceDir` in properties file. Any advice?

**Comment by pmatyszok** [comment]
Aw, yes. Using docToolchain.bat it works like a charm. 

So, the solution to the problem was to:

* modify `gradle.properties` so that it states `inputPath = .`
* start using `docToolchain.bat` script on Windows, even when using bash

From my side the note might be closed as now it works as expected. But I think the documentation could be improved: I am not sure, whether what we have at doctoolchain.github.io is about the V1.0 tag, or the most recent version. If it is about the most recent version, then I could modify the docs to emphasize the that on Windows the .bat script has to be used, and that "working directory" has to be set in `gradle.properties` via `inputPath` variable.

**Comment by jakubjab** [comment]
@rdmueller - I see it's a problem not only with initializing and building arc42EN template, but in general with using docToolchain as a tool after V1.0.0, with previously working documents. I'll try to have a look. Right now I cannot upgrade without modifying the tool's code, which is breaking the idea why bin/doctoolchain was created.

**Comment by rdmueller** [comment]
@jakubjab with every day, I like the  `bin/doctoolchain` idea more, because it removes dependencies from the project in which dt is used.
I wonder if it would make sense to create something like the gradle-wrapper which stores the dt-version in a properties file of the project and downloads dt to the user's home folder if needed...

**Comment by gernotstarke** [comment]
@rdmueller - concerning `bin/doctoolchain`: good point, I moved that discussion to [a new issue](https://github.com/docToolchain/docToolchain/issues/278) where we might discuss options...

**Comment by synesthesia** [comment]
I came to this issue because I was finding similar issues to @pmatyszok  (Windows 8.1, Git BASH)

Working on latest version of `master` branch (178f3eecb53)

docToolchain installed outside of my project, with [devToolchain]\bin added to Path.

Apologies in advance, this is my first exposure to this tool so I may have misunderstood how it is supposed to be used. 

However given a command line of
`doctoolchain.bat [INPUTDIR]  [TARGET] [OPTIONS]]`

I would assume that the [INPUTDIR} parameter would be the path (relative or absolute) to the root of my document sources - ie. (if I have understood correctly), the path where `Config.groovy` will be found.

So although changing `gradle.properties` as above to set `inputPath = .` fixes the simple example where the arc42 template is in the current directory, it doesn't work for a more general case.

How should we tell the script where to find our document sources?

**Comment by rdmueller** [comment]
`-P` sets a property - it is directly passed to the underlying gradle:
https://docs.gradle.org/current/userguide/command_line_interface.html#environment_options

**Comment by synesthesia** [comment]
Thanks @rdmueller 

After a bit of experimentation and exploration I found [this](https://github.com/jakubjab/docToolchain/commit/59f95d24ee4293c1a06734233afc516a04ecc06b) at @jakubjab 's fork which I was able to adapt, so it now seems to work for our environment in the way we need it.

So for example if I have a project with this structure:

```
\
-- src
---- <source code for project>
-- docs
---- Config.groovy
---- master.adoc
---- src
------included.adoc

```

I can now run `doctoolchain.bat ./docs generateHTML` and get a result, without having to specify any -P properties.

I haven't tried against a more "traditional" setup yet.

Slowly getting over my culture shock of dealing with two new (to me) tools (Gradle and Groovy)...

**Comment by jakubjab** [comment]
@pmatyszok - could you please try again if the latest fix resolves this issue?

**Comment by pmatyszok** [comment]
@jakubjab erm... I think by some terrible gmail rule I didn't get rest of the e-mails in the issue, but only the latest one from stale-bot, and even that one... I left unread for too long.

Anyway, I have used recent version of docToolchain and went through the steps to reproduce. It works like a charm right now. To settle the facts, I am using Windows 10 Pro with a Git Bash. I didn't tested with Powershell though, but then again - when I originally raised the issue, I wasn't using it as well. It looks very good.

So now I will allows myself to close the ticket, and if I'll be able to - remove the `wontfix` label, as that issue is for sure `fixed` now.

**Comment by rdmueller** [comment]
thank you for the detailed update!
