### ISSUE TITLE
prepare docToolchain for the new Asciidoctor Gradle plugin

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#261]
see https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development-2.0/README.adoc for details

**Comment by gernotstarke** [comment]
maybe adjust the documentation of htmlSanityChecker too...

**Comment by EiGude** [comment]
dead url

**Comment by rdmueller** [comment]
close this because it is outdated (but still important.)
