### ISSUE TITLE
Confluence: Inline Comments

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#28]
When using inline comments in confluence, a new `publishToConfluence` overwrites these comments.

Inline comments are stored in confluence like this:

`<p>Lorem <ac:inline-comment-marker ac:ref="e8e647e6-b612-4123-b1bb-3f5fd6d89c10">Ipsum</ac:inline-comment-marker> etc.</p>`

So, it should be possible to at least notice them, maybe even keep them.

**Comment by rdmueller** [comment]
I don't consider confluence as a good choice for publishing anymore. With the features available in the generated HTML (backlinks to the repository), Confluence is more a workaround than a problem solution.
That's why I close this issue now.

**Comment by rehsack** [comment]
In many companies, confluence is the state of knowledge management, thus suggestion use anything else doesn't help ;)

However - we have an issue created at atlassian for that: https://jira.atlassian.com/browse/CONFCLOUD-74749

Maybe - when enough people care - it will be fixed sooner.
