### ISSUE TITLE
collectIncludes

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#282]
Collect includes should search for adoc files in the whole project, but it only searches in the task's project (`projectDir`) which is only the docToolchain folder if used as submodule.

The task should be extended to the whole project.

**Comment by synesthesia** [comment]
Further, with docToolChain installed outside the project and added to the path, the `collectIncludes` task scans the docToolChain folder, _not_ the project folder

This is consistent I think with the use of `projectDir` as the source of files to scan at https://github.com/docToolchain/docToolchain/blob/master/scripts/collectIncludes.gradle#L15 

Perhaps this needs another property which defaults to the same value as `docDir` (for the common case where records such as ADR are in a subdirectory of the document directory), but which can be overridden on the command line with `-PscanDir=<other root>` ?

And then https://github.com/docToolchain/docToolchain/blob/master/scripts/collectIncludes.gradle#L15 might read
```
File sourceFolder = scanDir
```
?

what do you think @rdmueller ?

**Comment by rdmueller** [comment]
thanx for your contribution!
As your PR changes the properties file, I need some more time to review it...
We jsut hat a change inthe propterties and I want to make sure that this doesn't interfere...

**Comment by synesthesia** [comment]
Of course! To be honest as I get more into using docToolchain I am hacking more tasks to suit my use case, not just for paths but to adjust generated Asciidoc code. Feels like a codesmell so I think these should all be part of the bigger #279 and other similar “where do we go” conversations.

I think the conversation about subrepo v /bin is key

**Comment by rdmueller** [comment]
that's great! most of the tasks ate hacked together to see if the use case fits and they are developed for just one use case.

so if you extend some of the tasks to fit a more general use case, it would be great if you could contribute them back.

**Comment by rdmueller** [comment]
time flies by... I just managed to create another PR where I tried to address some of the issues...
Now I have to find some time to bring both together...

**Comment by rdmueller** [comment]
Thanx for your contribution and thanx for the patience!
You PR has been merged!
