### ISSUE TITLE
docToolchain doesn't want publish my asciidoc file  to confluence

### ISSUE THREAD

**Issue by valerosha** [docToolchain/docToolchain#287]
Hello !
Can you help me? please!
I can't understand is it correct settings my environment or did I forget smt?
My ConfluenceConfig.groovy file:
input = [
    	[ file: "build/html5/Subscription.html", ancestorId: 32995 ]
	]
confluenceAPI = 'https://examplevalerosha.atlassian.net/wiki/rest/api/'
confluenceSpaceKey = 'NEW'
confluenceCreateSubpages = false
confluencePagePrefix = ''
confluenceCredentials = 'my_user_gmail:my_password'.bytes.encodeBase64().toString()

**Comment by rdmueller** [comment]
your config looks good.
What is the error message you get?
Does the file `build/html5/Subscription.html` exist after you do a `./gradlew generateHTML`?
The given `confluenceAPI` is a fake one I assume because you don't want to disclose yours here, correct?

**Comment by valerosha** [comment]
1. I don't have any error message. that's the problem , because I don't know why my file isn't published
2.  In which folder should I check it?
3. No, https://examplevalerosha.atlassian.net/wiki - it's my real host where I'm trying to publish asciidoc file (converted to html file)
4. Yep, space "NEW" already exists

**Comment by rdmueller** [comment]
1) try to use the switch `--info` this might yield some more information
2) do you use docToolchain in the /bin/doctoolchain version? Or as gradle submodule?
3) ah, ok - so I am missing the access rights

**Comment by rdmueller** [comment]
maybe this working project with config might help:
https://github.com/duschata/reproduceCodeFormattingFailure

Have you configured the input files?
```
inputFiles = [
        [file: 'Subscription.adoc',       formats: ['html','pdf']],
]
```
?

**Comment by valerosha** [comment]
![image](https://user-images.githubusercontent.com/13032857/54543683-288dd900-49af-11e9-8a1c-8dde9bbaebe2.png)

Is that means something went wrong?

**Comment by rdmueller** [comment]
What does it say before?
What is the command you invoke and what does it say about `generateHTML`?

**Comment by duschata** [comment]
are you sure that your ancestorId: 32995 is correct? In try "ContentTools" -> "ReorderPages" in confluence.  Do you see folders outside the root there?

**Comment by valerosha** [comment]
1. When I did generateHTML
![image](https://user-images.githubusercontent.com/13032857/54637747-77fd0380-4a9a-11e9-9bb3-a9e3f5b14fa5.png)
2. I use the following command:
![image](https://user-images.githubusercontent.com/13032857/54637869-b4c8fa80-4a9a-11e9-9ed9-4d894599044a.png)
and get the second result :
![image](https://user-images.githubusercontent.com/13032857/54637911-d4f8b980-4a9a-11e9-9f45-ec36d9dd7cc7.png)
but nothing is published on my page =(
3. I checked - ancestorId: 32995 is correct. Also i tried to make a request without ancestorId:
input = [
[ file: "build/html5/arc42-template.html" ]
]
confluenceAPI = 'https://examplevalerosha.atlassian.net/wiki/rest/api/'
confluenceSpaceKey = 'NEW'
confluenceCreateSubpages = false
confluencePagePrefix = ''
confluenceCredentials = 'my_mail:my_password'.bytes.encodeBase64().toString()

**Comment by duschata** [comment]
these settings are outdated (unfortunately not deleted in the project). Copy the current docToolchain/Config.groovy into your project dir.  
```
https://github.com/docToolchain/docToolchain/blob/master/Config.groovy
```
the confluence input section is nested:

```
confluence.with {
    input = [
            [ file: "build/docs/html5/arc42-template-de.html" ],
    ]

    // endpoint of the confluenceAPI (REST) to be used
    api = 'https://[yourServer]/[context]/rest/api/'

//    Additionally, spaceKey, createSubpages, pagePrefix and pageSuffix can be globally defined here. The assignment in the input array has precedence

    // the key of the confluence space to write to
    spaceKey = 'asciidoc

....
}
```
I promise, after that all will work as expected

**Comment by valerosha** [comment]
If you have a some free time,please, can you check my settings in files maybe I confused something?

**Comment by duschata** [comment]
you are using the wrong Groovy.config. These settings are never read by the script. You need this
```
confluence.with {...}
 
```

and the settings later don't have the confluence prefix. Have a look at this (working) project:
```
https://github.com/duschata/reproduceCodeFormattingFailure
```

**Comment by valerosha** [comment]
Should I use the same Groovy.config for my project? because now I have the next struct....
![image](https://user-images.githubusercontent.com/13032857/54820006-c7b41880-4cae-11e9-9457-cff49b2a7788.png)
 and my docs
![image](https://user-images.githubusercontent.com/13032857/54820064-edd9b880-4cae-11e9-9a7f-68db525d680a.png)
 Or something extra ?

**Comment by duschata** [comment]
you need only one Config.groovy, placed in the root of the project which you want to publish. You must configure all there (in your case input files in the upper section and publish files in the nested confluence.with section).
Put the adoc file under src/docs/

After that launch the 
```
doctoolchain . publishToConfluence
```
from the root folder from your project. 

Again, the

```
https://github.com/duschata/reproduceCodeFormattingFailure
```
has a valid project structure

**Comment by valerosha** [comment]
I downloaded your project. Now I have next struct
![image](https://user-images.githubusercontent.com/13032857/54830098-e32c1d00-4cc8-11e9-8804-928f1c354cd7.png)
![image](https://user-images.githubusercontent.com/13032857/54830117-ea532b00-4cc8-11e9-9d7a-616e80129461.png)

But I have next error

![image](https://user-images.githubusercontent.com/13032857/54830063-d27ba700-4cc8-11e9-8a27-4e1554601a01.png)

**Comment by duschata** [comment]
open the project in an IDE (eg. vscode) and switch all content to UTF-8...

**Comment by rdmueller** [comment]
Great to see that the first problem is fixed - do we have to update docs somewhere?

now, I get the feeling that the current problem is not because of wrong UTF-8 encoding but of a wrong protocol for a URL. I think I've seen this somewhere before. URISyntaxException

Please check all your `include`- and `image`-statements.

**Comment by rdmueller** [comment]
@duschata ok, you had the same problem (URISyntaxException) before: 
https://github.com/docToolchain/docToolchain/issues/271

Do you rember what exactly it was? I woudl like to replace this error message with a help message...

...and if it is really a problem with the encoding: there is now a `fixEncoding`-Task: https://doctoolchain.github.io/docToolchain/#_fixencoding

**Comment by valerosha** [comment]
Thank you soooo  much for your help !!!! And your very cool tool =)

**Comment by rdmueller** [comment]
@valerosha did you find what was causing the `URISyntaxException`? What was the root cause?

**Comment by valerosha** [comment]
This was due to the following causes:
1. I fixed the encoding in main adoc file 
2.  Fixed some include path
And also I want ask you again)  
Is there some way to update my confluence page which has already load in confluence? (with the help of your tool)

**Comment by rdmueller** [comment]
1. hm. so the `URISyntaxException` was due to wrong encoding? interesting...

2. can you please reformulate your question? What do you mean by "already load in confluence"?
if you change an asciidoc file in your project, your confluence pages will be updated...

**Comment by valerosha** [comment]
I get the following error
![image](https://user-images.githubusercontent.com/13032857/55309181-aea52780-5465-11e9-856e-0859ae8fff9b.png)

**Comment by valerosha** [comment]
2. I understood why the page was not updated: it's happened because I hadn't filled out pagePrefix. And docToolchain tried to create a new page, but page with the same name already had been created. This results in the following error:  **something went wrong - got an http response code 400:
[statusCode:400, data:[authorized:false, valid:true, allowedInReadOnlyMode:true, errors:[], successful:false], message:A page with this title already exists: A page already exists with the title....** . But now all is ok, Thank you)

**Comment by rdmueller** [comment]
thanx for this important update!
I will try to make error messages better...
