### ISSUE TITLE
Confluence: Split by page

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#29]
Asciidoc can contain page breaks `<<<<`
It would be great if these could be used as markers to split long confluence pages into several pages

**Comment by bodewig** [comment]
it looks as if this resulted in

```
<div style="page-break-after: always;"></div>
```

inside the generated HTML markup.

It should be possible to detect this and create subpages. What would you use as their titles?

**Comment by rdmueller** [comment]
you normally put page breaks right before headlines. 
maybe we can extract the first headline in the subpage with jsoup?

**Comment by bodewig** [comment]
Let's see

* If the next headline we find is a `h2`, then we don't need to do anything. This is going to become a separate page anyway.
* The same is true for `h3` if `confluenceCreateSubpages` is `true`.

For the remaining cases we'd use the text of the next headline as page title and make the new page a subpage of the last `h2` (`h3` if `confluenceCreateSubpages` is `true`) page created.

Correct?

Currently the headline used as page title is removed from the tree. This would only be save for page breaks if the page break really occurred directly before a headline. If there was any content between the page break and the headline, we'd better preserve the headline. Or maybe the page break should be ignored unless it directly preceded a headline?

Should headlines of the new page be promoted the same way it currently happens for pages created from `h3`s?

**Comment by rdmueller** [comment]
hm. interesting. Didn't we (you!) solve this by now? Have to check this...

**Comment by rdmueller** [comment]
afaik, this can be closed as fixed
