### ISSUE TITLE
provide asciidoc2Confluence as plugin

### ISSUE THREAD

**Issue by duschata** [docToolchain/docToolchain#290]
We would like to provide asciidoc -> publishToConfluence company-wide. Of course that only makes sense if we provide it to our programmers as a gradle-plugin. I would therefore like to encapsulate asciidoc2Confluence. Later, other scripts could follow step by step. I would review the script again and possibly fix #281. If publishToConfluence is encapsulated, it would be easier to create a plugin from it.

**Comment by rdmueller** [comment]
good idea. What do you mean by "encapsulate"? Just turn it from a script into a class for plugin distribution?

If you encapsulate the code, you also might want to take a look at https://github.com/confluence-publisher/confluence-publisher
maybe we can refactor it to create a common code base...

**Comment by duschata** [comment]
That sounds very tempting, but could quickly become overkill. To convert the existing codebase of "asciidoc2Confluence.groovy" into a plugin, only a few steps are necessary. "Confluence-publisher" has a submodule called "asciidoc-confluence-publisher-converter" which suggests that some APIs are easy to use (outside maven), but it may take a long time to evaluate, maybe it fails. "asciidoc2Confluence.groovy" is currently sufficient for our purposes, so I would first try to make a plugin out of it.

**Comment by rdmueller** [comment]
ok. so give it a try!

**Comment by duschata** [comment]
```
plugins {
  id "de.docs-as-co.publishToConfluence" version "1.0-SNAPSHOT"
}
```
closure
```
confluenceSettings {
    settings {
        global {
            spaceKey = 'mustBeSet'
            createSubpages = true
            pagePrefix = ''
            pageSuffix = ''
            extraPageContent = ''

            fileToPublish { //will override global
                filePath = 'build/myGeneratedDoc.html' //path or url (beginning with http)
                ancestorId = 1234
                preambleTitle = "arc42"
                spaceKey = ''
                createSubpages = true
                pagePrefix = 'aPrefix'
                pageSuffix = 'aSuffix'
                extraPageContent = ''
            }
        }

        restClient {
            api = 'https://path'
            credentials = "user:password".bytes.encodeBase64().toString()

        }
    }
}
```
This is the first attempt. Works for me. More information will follow soon. Please send me a PM to share the plugins.gradle.org secret.
