### ISSUE TITLE
publishToConfluence: Support of custom REST query header

### ISSUE THREAD

**Issue by tbrandenburg** [docToolchain/docToolchain#292]
**Is your feature request related to a problem? Please describe.**
In my environment we have to use the confluence REST API through a gateway using authorization (with user and password) _and_ an API token in such a way:

`    def headers = [
            'Authorization': 'Basic ' + config.confluence.credentials,
            'keyid': '<API-Token>',
            'X-Atlassian-Token':'no-check'
    ]
`
So as a workaround I had to change `asciidoc2confluence.groovy` and add my hardcoded `keyid` to `pushToConfluence` and `uploadAttachment`.

**Describe the solution you'd like**
Is it possible to add such header key-value pairs into Config.groovy?

**Describe alternatives you've considered**
Alternatively specific key id configuration can be provided but I think our "keyid" is proprietary and therewith not generically usable.

Thanks!

**Comment by rdmueller** [comment]
there is already a fix for this on my notebook. But it will still take until end of next week...
