### ISSUE TITLE
rebuild the documentation

### ISSUE THREAD

**Issue by jagedn** [docToolchain/docToolchain#298]
I've created 2 PR to improve the documentation but I'm not sure about how to update the doc directory. 
If I understand correctly I need to create this issue

**Comment by rdmueller** [comment]
thanx for this ticket. I've just updated the PR-template to reflect how to update the docs.

**Comment by rdmueller** [comment]
so, after I found a bug with the list of contributors, I now also updated the docs.
Still ahve to check your second PR, but I think this issue can be closed now...
