### ISSUE TITLE
 java.lang.Exception: missing authentication credentials

### ISSUE THREAD

**Issue by valerosha** [docToolchain/docToolchain#303]
**Describe the bug**
I filled in the password and e-mail correctly in   Config.groovy file, but every time there is a java error.lang.Exception: missing authentication credentials
**To Reproduce**
1. Set  up file - Config.groovy [with correct credentials, I checked it several times=) ]
2. Set  up file - gradle.properties 
3. Set  up file -  JiraConfig.groovy
4.  After that use command - 
doctoolchain C:\please\docToolchain-master  publishToConfluence --no-daemon -q

**Expected behavior**
After that, I expected to see all the files added to confluence, but ....
**Screenshots**
![image](https://user-images.githubusercontent.com/13032857/57192695-f246f180-6f3b-11e9-9d34-4d41ebd5b777.png)

**Configuration**
 - OS: Windows
 - Browser: chrome
 -   JDK 8.0

**Comment by rdmueller** [comment]
can you give us a bit more about your confluence instance?
Is it self hosted? I see from your logs that you use crowd...

**Comment by valerosha** [comment]
What do you mean:  give us a bit more about your confluence instance...
1. I  registered on this link - https://ru.atlassian.com/software/confluence
2. I enter to the system on this link - https://id.atlassian.com/login

**Comment by rdmueller** [comment]
So, as I do understand, you use the version hosted by atlassian. That's what I use too.
Do you use some special characters for username or password?

**Comment by rdmueller** [comment]
I you send me an email, I can set you up as a user in our confluence space and we can give it a try to see if your setup works there....
ralf.d.mueller@docs-as-co.de

**Comment by ewoks** [comment]
@valerosha did you resolve your issue with confluence credentials? 
Did you use username/password or username/token combination? Assumption is that password usage was deprecated in favor of token.
Let us know so we can do something with this ticket and others can benefit from solution

**Comment by ewoks** [comment]
@valerosha we will assume this ticket can be closed as repeated tests with valid credentials in a Config.groovy showed no issue. If you still have issues, feel free to reach 😊
cc: @rdmueller
