### ISSUE TITLE
Running doctoolchain.bat on other Drive causes error (Windows)

### ISSUE THREAD

**Issue by bohni** [docToolchain/docToolchain#304]
**Describe the bug**
Running doctoolchain.bat (in German Windows 10) causes following error:
`Der Befehl "." ist entweder falsch geschrieben oder konnte nicht gefunden werden.`

**To Reproduce**
1. Create the DocDir on Drive C:
2. `cd` to another Drive, eg. D:
3. run `D:\xyz> doctoolchain.bat C:\docdir generateHTML`

**Expected behavior**
HTML-Docs should be generated

**Configuration**
 - OS: Windows 

**Additional context**
Running in cmd or git-bash causes same error

_**Solution**_
doctoolchain.bat, Line 23: Add Parameter `/d ` to `cd` so that drive is also changed, not just directory

**Comment by rdmueller** [comment]
interesting finding! thanx for the report.
As you already have the solution - would you like to create a pull request?

**Comment by rdmueller** [comment]
thanx for the PR! I guess this can be closed now?
