### ISSUE TITLE
Atlassian basic authentication is deprecated

### ISSUE THREAD

**Issue by magmax** [docToolchain/docToolchain#316]
**Describe the bug**
I'm trying to use the exportJiraIssues feature and it doesn't work. After a while trying to recreate the problem just using curl, I think the real problem is that docToolchain is using basic auth and it has been deprecated recently:
https://community.developer.atlassian.com/t/announcement-deprecation-of-basic-authentication-with-passwords-and-cookie-based-authentication-in-jira-cloud-rest-apis/15687

I'm using an on premise instance of Jira and running docToolchain from linux.

**To Reproduce**
1.  ./bin/doctoolchain example exportJiraIssues

**Expected behavior**
Retrieve the jira issues.

**Screenshots**
it shows nothing interesting, but creating the related `curl`:

```
curl -u user@company.com 'https://WHATEVER.atlassian.net/rest/api/2/search?jql=project=FOO' -i -H "Content-Type: application/json" -s -v
```

Despite I've simplified the query, it is returning a 401 forbidden (it require the password and I double checked the one I'm prividing is fine).

When running it:

```
$ ./bin/doctoolchain example exportJiraIssues

> Configure project :
arc42-template.adoc

> Task :exportJiraIssues FAILED
https://WHATEVER.atlassian.net
project='FOO' AND resolution='Unresolved' ORDER BY priority DESC, duedate ASC

FAILURE: Build failed with an exception.

* Where:
Script '/somepath/docToolchain/scripts/exportJiraIssues.gradle' line: 38

* What went wrong:
Execution failed for task ':exportJiraIssues'.
> groovyx.net.http.HttpResponseException: 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

That URL works for me in a browser when I'm already logged with same user.

**Configuration**
 - OS: Linux
 - Browser: Firefox, curl.
- docToolchain commit: 0a8e3107f738afa53fe7535253afb0698e398d9c
 - Relevant SDK Versions:

```
$ ./bin/doctoolchain example --version

------------------------------------------------------------
Gradle 5.3.1
------------------------------------------------------------

Build time:   2019-03-28 09:09:23 UTC
Revision:     f2fae6ba563cfb772c8bc35d31e43c59a5b620c3

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.15.0-48-generic amd64
```

- Also tried with docToolchain v1.1.0 and:

```
$ ./bin/doctoolchain example --version

------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.15.0-48-generic amd64
```

**Additional context**

These issues may be related:
- #292 
- #303

**Comment by rdmueller** [comment]
thanx for reporting this issue and linking to the announcement.

it says "Basic authentication with API tokens is the recommended replacement.".

Have you tried this mechanism? You should be able to replace the password in the config with a generated token. AFAIK, you can generate the token through the Jira Web-UI.

If this works, we only have to update the docs...

**Comment by magmax** [comment]
After a while reading, I think that it is not related with my issue (despite the announcement should be considered for a near future).

I'm not sure about what is happening, because everything seems to be right. I will try with another cloud instance this weekend where I'm jira admin.

I tried to generate a token with that and I couldn't. I tried generating one with bitbucket and failed (but maybe I was too quickly, I'm going to try again).

**Comment by rdmueller** [comment]
hm. Do you see in the error message or stacktrace somewhere a reference to "CROWD"?

**Comment by magmax** [comment]
No, but I've advanced one step.

This is not related to docToolchain, but I think it is a good idea to doc it.

I've gone to https://id.atlassian.com/manage/api-tokens and I've created a new api token. Just by using it as password the `curl` worked for me and docToolchain changed the error:

```
> java.text.ParseException: Unparseable date: "2017-06-29T17:15:24.657+0200"
```

This is another different error and I think I can handle it.

**Comment by rdmueller** [comment]
sounds interesting. Keep us updated!

**Comment by magmax** [comment]
Just worked.

My format was "yyyy-MM-dd'T'HH:mm:ss.SSSZ", taken from examples at https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#parse(java.lang.String)

Maybe it should be parameterizable :)

Anyways, as summary:

- The authentication problem was fixed by using an api-token instead of the password. It can be generated at https://id.atlassian.com/manage/api-tokens. Maybe this should be documented.
- There is a problem with dates that may be parameterized.

And... that's it :)

**Comment by rdmueller** [comment]
Hi @magmax, I just tried to update the docs to reflect your findings:
https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/03_task_exportJiraIssues.adoc

But I didn't get the date problem yet. So the parse String is

    yyyy-MM-dd'T'H:m:s.000z

and your jira instance returns

    2017-06-29T17:15:24.657+0200

So, I guess `"yyyy-MM-dd'T'H:m:s.Sz"` worked for oyu and should be the standard format for parsing the date, correct?

**Comment by magmax** [comment]
There is a typo: "Ist deprecated".

About dates: I'm not sure, but maybe it should be a variable to avoid touching the script. I'm not sure if Jira uses a different format for different countries, time formats or just one for all of them. By extracting it to a variable it should be fixed.

**Comment by rdmueller** [comment]
but the new parse string is the same which worked for you?

**Comment by rdmueller** [comment]
so, this should now work for you. the config for the date parser and formatter is not available

**Comment by magmax** [comment]
The format that worked for me was 
```
yyyy-MM-dd'T'HH:mm:ss.SSSZ
```
Maybe it is different for hosted and cloud confluence flavours.

Thank you!

**Comment by rdmueller** [comment]
thanx for the valuable feedback.
