### ISSUE TITLE
Windows: Blank in path breaks relative path

### ISSUE THREAD

**Issue by kvt11** [docToolchain/docToolchain#319]
**Describe the bug**
Blanks in docPath break execution of doctoolchain.bat
docPath is not correctly passed to gradle when executing doctoolchain.

**To Reproduce**
1. Preparation
assume doctoolchain is installed in D:\prg\doctoolchain
assume "D:\my doc path\" as the root directory of some documentation (i.e. "D:\my doc path\Config.groovy"
3. run doctoolchain
> cd D:\my doc path
> d:\prg\docToolchain\bin\doctoolchain.bat . generateHtml

Script 'D:\prg\docToolchain\scripts\AsciiDocBasics.gradle' line: 29

* What went wrong:
A problem occurred evaluating script.
> d:\my\Config.groovy (Das System kann den angegebenen Pfad nicht finden)
**Expected behavior**

**Configuration**
 - OS: Windows 10

**Comment by rdmueller** [comment]
thanx!

**Comment by rdmueller** [comment]
I guess we can close this now...
