### ISSUE TITLE
create a microsite for the project

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#330]

**Comment by rdmueller** [comment]
this might be a fun series of pull requests.
with the knowledge of this german artikel (there is also a repository), it should be easy to setup a jbake site in `/src/site` : 
https://www.informatik-aktuell.de/entwicklung/methoden/docs-as-code-alles-unter-einem-dach.html

the start of such a microsite would be enough for hacktoberfest

**Comment by Nicca3006** [comment]
Microsite already implemented ;)
