### ISSUE TITLE
Deep nested structure

### ISSUE THREAD

**Issue by opensource21** [docToolchain/docToolchain#34]
At the moment we have a really nested structure. I wondering if it wouldn't become more handy to have the following structure:

At top level
- src/doku and src/doc: based on the assumption that nobody writes a documentation in two languages and even if he does it's better to create than 2 git repos.
- under doku or doc only  arc42, images and perhaps pdfTheme (even this is not really documentation it's more styling) and than no further nesting. 

It's make it easier to delete all the stuff it's not necessary and easier to navigate.

**Comment by rdmueller** [comment]
yes, the current structure leaves room for improvement. 
the EN/DE folders make it more explicit with which language you have to deal, but I get your point...

**Comment by rdmueller** [comment]
I guess we should first separate the arc42 tempalte from doctoolchain and then rework the strcuture:
#91

**Comment by jakubjab** [comment]
I have started some work on #91 but didn't have time to finish. I'm planning to do some work next week.

**Comment by rdmueller** [comment]
I think we've did some progress on this by now and it is time to close this ticket.
Please open new issues if you think there is something missing.
