### ISSUE TITLE
Proposal: Convert keywords to Confluence labels

### ISSUE THREAD

**Issue by dierk42** [docToolchain/docToolchain#342]
When publishing to Confluence I'd like to attach labes (=keywords) to pages. This helps creating reporting pages and improves searching results.

In an asciidoc header I define :keywords: which become a meta tag 'keywords' in HTML.

In my version of asciidoc2confluence.groovy I split the keywords into a list and add the labels after(!) the creation of a page. Confluence does not allow to include labels at the time of creating a page.

My quirking the script works for me. But as I'm not an experienced Groovy programmer -- have look at it if you think this feature useful.

[asciidoc2confluence.txt](https://github.com/docToolchain/docToolchain/files/3515982/asciidoc2confluence.txt)

**Comment by rdmueller** [comment]
^hey, this sound like a good idea!
Do you mind to send you code as a Pull-Request? This would make it easier to review it as diff...

**Comment by sabatmonk** [comment]
this is in master, should it be closed?

**Comment by rdmueller** [comment]
thanx. yes, I guess it can be closed.
