### ISSUE TITLE
publishToConfluence: allow proxy configuration

### ISSUE THREAD

**Issue by bit-jkraushaar** [docToolchain/docToolchain#345]
**Is your feature request related to a problem? Please describe.**
At my customers company connecting to Confluence is only possible via proxy. The current version of org.codehaus.groovy.modules.http-builder:http-builder:0.6 does not allow to specify proxy settings via command line or environment properties. They have to be given by calling HTTPBuilder#setProxy(host, port, schema).

**Describe the solution you'd like**
I like to specify the proxy settings in the project (e.g. in Config.groovy) or as environment properties (e.g. Javas http.proxyHost, ...).

**Describe alternatives you've considered**
Extending asciidoc2confluence.groovy by calling http.setProxy(...) and api.setProxy(...) and using parameters defined in config.confluence would do the trick for us. Unfortunately it is not possible to specify non proxy hosts or proxy credentials this way.

**Comment by rdmueller** [comment]
hm. interesting. I've never had the situation that there is a proxy between docToolchain and Confluence.
Since you've already done some investigations - do you have already a solution in mind?

**Comment by bit-jkraushaar** [comment]
See pull request #346.

**Comment by bit-jkraushaar** [comment]
Thanks a lot!
