### ISSUE TITLE
Cannot upload files to confluence

### ISSUE THREAD

**Issue by nikolaialex** [docToolchain/docToolchain#351]
I try to publish files to confluence. I always get the message "> created page null". Confluence returns 200 Ok, but does not create the page. If I use curl, I can create the page.

**To Reproduce**
+ Tested with toolchain-1.0.0 and master
+ bin/doctoolchain ../myproject publishToConfluence --no-daemon -q -info

**Expected behavior**
I expect, thst the pages are created or an error message is provided.

**Configuration**
+ Gradle 5.4.1
+ Build time:   2019-04-26 08:14:42 UTC
+ Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d
+ Kotlin:       1.3.21
+ Groovy:       2.5.4
+ Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
+ JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
+ OS:           Mac OS X 10.12.6 x86_64

**Additional context**
Config
```
outputPath = 'build'

inputPath = '.' 

inputFiles = [ 
        [file: 'src/docs/test.adoc', formats: ['html']],
             ]   

taskInputsDirs = ["${inputPath}/src",
                  "${inputPath}/images",
                 ]   

//taskInputsFiles = ["${inputPath}/test.adoc"]

confluence = [:] 
confluence.with {
    input = [[ file: "build/html5/src/docs/test.html" ]]
    api = 'https://.../confluence/rest/api/'
    spaceKey = 'myspace'
    createSubpages = false
    pagePrefix = ''
    pageSuffix = ''
    credentials = "u:p".bytes.encodeBase64().toString()
   
```
File
```
= Test
== Section
Lorem...
```

**Comment by ewoks** [comment]
@nikolaialex can you confirm this issue is still existing with the newest docToolchain (latest commit on master)?

**Comment by nikolaialex** [comment]
Fixed in current version.

**Comment by rdmueller** [comment]
thanx!
