### ISSUE TITLE
Pull all Confluence page metadata from the selected space, to perform title match in-memory, and avoid CQL

### ISSUE THREAD

**Issue by LuisMuniz** [docToolchain/docToolchain#352]
**Is your feature request related to a problem? Please describe.**
This fixes disparities in how CQL is interpreted on Confluence Server vs Cloud.
There have also been instances of CQL not behaving well if the title of a page conains colons. This may happen with other special characters we are not aware of.

**Describe the solution you'd like**
We fetch metadata of all pages through the REST API, keep the relevant data cached in a Map, indexed by lowercase title (Confluence does not allow duplicate titles).

Modify the search functionality to use the Map instead of querying the API with CQL.

**Describe alternatives you've considered**
Switching to using EQUALS instead of CONTAINS operator in the CQL operator, discussed in #348
Using the GET endpoint instead of the search endpoint.

**Additional context**
The origin of the issue was us migrating from cloud to server and seeing that doctoolchain behaves differently.

**Comment by rdmueller** [comment]
This is also done, isn't it?

**Comment by LuisMuniz** [comment]
Yes :-)
