### ISSUE TITLE
Allow including raw OpenAPI markup to wrap in a custom confluence macro

### ISSUE THREAD

**Issue by LuisMuniz** [docToolchain/docToolchain#354]
**Is your feature request related to a problem? Please describe.**
We would like to be able to keep the openAPI definitions in our code repository, and use the publishToConfluence command to push the OpenAPI yaml to confluence Swagger Editor marketplace macro. See https://marketplace.atlassian.com/apps/1218914/open-api-swagger-editor-for-confluence?hosting=cloud&tab=overview

**Describe the solution you'd like**
I don't know Asciidoctor very deeply, so my solution may not be optimal.
What I was looking into, is creating a configuration option in the confluence configuration options, that would inform the script that a certain Section should be treated specially.

For example:

```
confluence {
    openAPISection="OpenAPI"
}

```

would inform the script that the following asciidoctor section 

```
== OpenAPI
++++
include::openapi/api.yaml[]
++++
```

Which streams raw the yaml file into the output, contains a raw OpenAPI yaml file.

The pushToConfluence method could then treat this section differently, and add the necessary XHTML to include the swagger editor macro and thus creating a page showing a nice swagger-ui  interface with the given API definition.

I would like to open a discussion on how to do this properly in your script, and if this is something that you'd be willing to consider.

**Describe alternatives you've considered**

**Additional context**

**Comment by rdmueller** [comment]
very cool idea!
I wasn't aware of the swagger editor macro for confluence until now.

Here is how I would implement your idea:

- visit a confluence page with the macro included and do a "view storage format" on this page (not "view source"). You will notice a tag like `<ac:structured-macro ... `. This is the macro you need to replace the html source with
- in your AsciiDoc, I would use a role like this:

```
    [role="openapi"]
    [source, yaml]
    ----
    include::openapi/api.yaml[]
    ----
```

This should give you syntax highlighting for the standard rendering and it should warp your source in a `<div>`-tag with class `openapi`. This makes it easy selectable with jsoup.

- now take a look at https://github.com/docToolchain/docToolchain/blob/master/scripts/asciidoc2confluence.groovy#L289
here we already rewrite code blocks and wrap the source in a `structured-macro`. You need to add a switch here to check for the outer class of `openapi` and wrap with the different macro in that case.

It would be great if you could create an option for this - not everybody uses the swagger macro. Something like `config.confluece.use_openapi_macro`. See https://github.com/docToolchain/docToolchain/blob/master/scripts/asciidoc2confluence.groovy#L402 for an example

Does this help?

**Comment by LuisMuniz** [comment]
This helps a lot! I'll give it a go!

**Comment by LuisMuniz** [comment]
I was able to implement the functionality almost as you described it.
The differences are the following:

The required markup to make the inclusion of the yaml file possible, with the addition of setting the class attribute, is the following:
```
[source.openapi, yaml]
----
include::openapi/api.yaml[]
----
```
I used the camelCase version of  your configuration option, to conform to existing options:

```
useOpenapiMacro = true
```

I had to bump the version that you use of jsoup, as the version that was included did not include the wholeText() method on Element. This method preserves the line breaks of the inner text.

**Comment by rdmueller** [comment]
wow. that was quick!
thanx a lot!

**Comment by rdmueller** [comment]
I guess we can close this now, can't we?

**Comment by LuisMuniz** [comment]
Yes! Thanks .
