### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.ivy.plugins.resolver.DependencyResolver

### ISSUE THREAD

**Issue by StephanPraetsch** [docToolchain/docToolchain#356]
**Describe the bug**
When I run 
```
gradle publishToConfluence --stacktrace
``` 
it shows me 
```
Caused by: java.lang.ClassNotFoundException: org.apache.ivy.plugins.resolver.DependencyResolver
```
What am I missing or is this a bug?

**To Reproduce**
See https://github.com/StephanPraetsch/ClassNotFoundException-DependencyResolver

**Expected behavior**
Not a `ClassNotFoundException`

**Configuration**
```
> gradle --version

------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Linux 4.15.0-62-generic amd64
```

**Comment by rdmueller** [comment]
Thanx for the detailed bug report. I am able to reproduce it. Now I will see how to fix it.

**Comment by rdmueller** [comment]
Argh. It seems that there is a problem with the tutorial... it says you should checkout the `v1.0.0` tag.
While the tutorial worked when I wrote it, somehow it now is broken if you check out the old tag.

So, please do the following:

```
cd docToolchain
git pull origin master
cd ..
./gradlew publishToConfluence
```

This should at least remove the current exception but will lead to a configuration error.
I will update the tutorial.

**Comment by rdmueller** [comment]
@StephanPraetsch did you already find some time to give this solution a try?

**Comment by StephanPraetsch** [comment]
Yes. Now I could update [my instruction](https://github.com/StephanPraetsch/ClassNotFoundException-DependencyResolver) (I had some docker and jdk problems ... ). It does run now without exception, affirmative.

It really helped me to reproduce steps I've done by writing it as a docker image. I recommend you do the same with your tutorial. Feel free to copy anything from my instruction if you want to.

**Comment by rdmueller** [comment]
oh, that is nice - we should somehow add this knowledge to the docs...
How about a PR?

**Comment by StephanPraetsch** [comment]
Ok. I will create a PR on https://github.com/StephanPraetsch/docs-as-co.de. My reported issue is solved. Thanks.
