### ISSUE TITLE
Default name when publishing to confluence

### ISSUE THREAD

**Issue by sabatmonk** [docToolchain/docToolchain#369]
**Describe the bug**
ConfluenceConfig.groovy refer to preambleTitle ad being outdate (and it doesn't seems to work) but the new version (as refered, Config.goory) show no replacement for it. What it does is that whatever i publish to confluience is name arc42 at first level

**Expected behavior**
a replacement or an explanation for preambleTitle

**Comment by sabatmonk** [comment]
found the issue and did a local fix, want me to do a PR?
in asciidoc2confluence.groovy, line 717, it check in input and not confluence
i simply added a line like 689 to check if it is in config.confluence. I tested and it works, it also behave like expected if the param isn't there

**Comment by rdmueller** [comment]
a PR would be awesome!

**Comment by sabatmonk** [comment]
there you go
https://github.com/docToolchain/docToolchain/pull/371

**Comment by ewoks** [comment]
guess this needs to be closed as PR is merged, correct?
