### ISSUE TITLE
finding the asciidoctor-pdf version

### ISSUE THREAD

**Issue by sabatmonk** [docToolchain/docToolchain#390]
Im looking around, trying to find the version of asciidoctor-pdf used in the toolchain (and maybe update it if needed). I cannot seems to find where it is declared. It might be that i am not looking at the right place, i'm not that good with groovy

**Comment by rdmueller** [comment]
it is a bit hidden within the code:

https://github.com/docToolchain/docToolchain/blob/master/scripts/AsciiDocBasics.gradle#L50

`org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.15`

you might want to give a try to the `v2.x` branch which is already on `1.5.0-beta.8`:

https://github.com/docToolchain/docToolchain/blob/v2.x/scripts/AsciiDocBasics.gradle#L54

**Comment by sabatmonk** [comment]
using branch 2, i kept getting 
:generatePDF NO-SOURCE

**Comment by sabatmonk** [comment]
i'll close this, since you provided the location. As for v2, it keeps failing, i'll play around.

Will probably end up being an other issue ;)

**Comment by rdmueller** [comment]
:generatePDF NO-SOURCE means that the config has changed.
try to use the `--info` option when you execute docToolchain. This will output the config which docToolchain sees and it might give you a hint...
