### ISSUE TITLE
exportEA task only handles .eap and not .eapx

### ISSUE THREAD

**Issue by dunschtig** [docToolchain/docToolchain#391]
Hi all,

When you have a model in the new file format (extension .eapx) it is silently ignored.
I think the files with the "new" extension should also be taken up.

**To Reproduce**
1. put a .eapx file into the project
2. run the task with --info
3. only the .eap files are taken up

**Expected behavior**
The task also works for .eapx files

**Configuration**
 - OS: Windows

**Propsed change**
extend line 204 to include also eapx e.g. by adding `OR fso.GetExtensionName (file.Path) = "eapx"`

**Comment by rdmueller** [comment]
thanx. I wasn't aware that the file extension changed (didn't update yet).

It seems that you already know the solution. Could you be so kind and create a pull request?

**Comment by dunschtig** [comment]
Yes just fixing the script would be easy.
But a proper pull request inkl. tests etc. will need some more time.

Question: How would you like to handle backward compatibility? Some might not have yet updated EA and therefore the test would potentially fail. Should there be a kind of switch / property to deal with that? Or just a straight forward update made?

**Comment by rdmueller** [comment]
I think we don't need automated tests. A manual test will be ok for this simple change.
regarding the backwards comp. - just change the script in such a way that it will export both extensions....

**Comment by dunschtig** [comment]
Okay the pull request is made. Hope it's fine.

**Comment by rdmueller** [comment]
Welcome to the list of contributors!
PR has been merged

**Comment by rdmueller** [comment]
I guess we can close this issue, can't we?
