### ISSUE TITLE
Update asciidoctorj-diagram to be able to render mindmaps

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#392]
PlantUML now supports mindmaps. 
We shall update asciidoctorj-diagram to the current version (v2.0.0) to get the current plantUML version and to be able to render mindmaps.

**Comment by mahuber** [comment]
This feature becomes very interesting because MindMaps in PlantUML are really very quick and easy to create.

**Comment by mahuber** [comment]
What is the status of this request?

**Comment by rdmueller** [comment]
please check the `2.x`-branch. I've just updated lots of dependencies and it should be able to render mindmaps now.
Tests run locally fine, but travis errors :-|

**Comment by mahuber** [comment]
Do you have an example of this? My following example in the asciidoc code still gives the
error "No such participant startmindmap" in the rendering output.

.example diagram
[plantuml,"{plantUMLDir}mindmap3",png]
----
@startmindmap
skinparam monochrome true
skinparam componentStyle uml2
!pragma graphviz_dot jdot
+ OS
++ Ubuntu
+++ Linux Mint
+++ Kubuntu
++++_ 10, 11
+++_ Lubuntu
++++_ 14, 15
+++_ KDE Neon
++ LMDE
++ SolydXK
++ SteamOS
++ Raspbian
-- Windows 95
-- Windows 98
-- Windows NT
--- Windows 8
--- Windows 10
@endmindmap
----

**Comment by mahuber** [comment]
Do you have an answer about my mindMap question above? Do you have an example how to integrate a plantUML mindmap in AsciiDoc in docToolchain. Thanks.

**Comment by rdmueller** [comment]
hm. I just gave it another try. I have the v2.x branch checked out and it generates mind maps.
I wonder what's the difference between out setups.

**Comment by mahuber** [comment]
generating Mindmaps in HTML works with Branch v2.x
genrating PDF gives following error output:

Task ':generatePDF' is not up-to-date because:
  Value of input property 'attributes' has changed for task ':generatePDF'
Converting /x/x/xy.adoc
conversion missing in backend pdf for pass
(TypeError) nil can't be coerced into Integer

**Comment by mh182** [comment]
TODO: test and close.

**Comment by mh182** [comment]
asciidoctorj-diagram was updated to 2.2.7 with PR #1141

**Comment by PacoVK** [comment]
Verified [8e9e1edbf](https://github.com/docToolchain/docToolchain/commit/8e9e1edbf85a0fb249d7f3fa9e5ba4d3e13594f7) was able to render the mindmap example of @mahuber 
Due to changes meanwhile in plantuml the example mindmap was
```
.example diagram
[plantuml,"{plantUMLDir}mindmap3",png]
----
@startmindmap
skinparam monochrome true
skinparam componentStyle uml2
!pragma layout smetana graphviz_dot jdot
+ OS
++ Ubuntu
+++ Linux Mint
+++ Kubuntu
++++_ 10, 11
+++_ Lubuntu
++++_ 14, 15
+++_ KDE Neon
++ LMDE
++ SolydXK
++ SteamOS
++ Raspbian
-- Windows 95
-- Windows 98
-- Windows NT
--- Windows 8
--- Windows 10
@endmindmap
----
```

Verified with `generateHTML` and `generatePDF` tasks and Java 11
