### ISSUE TITLE
asciidoctor-diagram: ERROR: Failed to generate image: PlantUML image generation failed:

### ISSUE THREAD

**Issue by azngeek** [docToolchain/docToolchain#395]
**Describe the bug**

asciidoctor-diagram: ERROR: Failed to generate image: PlantUML image generation failed:

**To Reproduce**

Install DocToolChain (https://doctoolchain.github.io/docToolchain/#_how_to_install_doctoolchain)
Edit any page and add a plantuml diagram

**Expected behavior**
The Toolchain should render a plantuml diagram using graphviz

**Screenshots**

![image](https://user-images.githubusercontent.com/213429/72800241-29367200-3c47-11ea-8443-43cabbf0123d.png)

**Comment by rdmueller** [comment]
interesting. Could you please copy & paste the whole stacktrace?
PlantUML should work if graphviz dot is installed on the command line.
Windows or Linux?

btw: you can also use PlantUML without Graphviz as explained here:
https://docs-as-co.de/news/plantuml-without-graphviz/

This blog also shows you how to check if PlantUML recognized your graphviz installation.

**Comment by stehlih** [comment]
Which graphviz version do you use?

PlantUML isn‘t working with versions newer than 2.38.

See https://plantuml.com/de/faq for mor information.

**Comment by mh182** [comment]
TODO: test and close.

**Comment by mh182** [comment]
docToolchain 2.2.1 generates images from PlantUML fine.

**Comment by mh182** [comment]
We upgraded to the newest `org.asciidoctor.asciidoctorj-diagram` to latest version 2.2.7.
On Linux PlantUML renders fine.
