### ISSUE TITLE
make doctoolchain gradle 7.0 compatible

### ISSUE THREAD

**Issue by ruediduedi** [docToolchain/docToolchain#396]
Problem: Currently the gradle version 6.1 gives a warning that testCompile will not be available in gradle 7.0 anymore.

Solution:
docToolchain/build.gradle : 15:-     testCompile(
docToolchain/build.gradle : 15:+     testImplementation(

Thank You!

**Comment by rdmueller** [comment]
great.
do you know what the minimum gradle version for `testImplementation`is?
... and would you be so kind to create a PR?

Thanx!

**Comment by rdmueller** [comment]
btw: if help is needed with creating the PR, just say so :-)

**Comment by EiGude** [comment]
the issue is still in the current version. How we can avoid this issue in future versions of Gradle.

**Comment by ruediduedi** [comment]
@EiGuide you mean in the current version of doctoolchain? I did create a pull request but I am not sure, whether I did everything correct, it is the first time I am contributing on github.

**Comment by rdmueller** [comment]
sorry, I will check the PR just now

**Comment by rdmueller** [comment]
#399 has been merged. Thanx for your contribution.
Please close this issue as soon as you managed to give it a try :-)

**Comment by ruediduedi** [comment]
Working. Changing status to closed. However: The guys from asciidoc are apparently still using older gradle. I could not find the repo for the gradle plugin https://asciidoctor.org/docs/asciidoctor-gradle-plugin/ thus still these warnings persist: 

`> Task :tools:docToolchain:generatePDF
Type 'AsciidoctorTask': non-property method 'asGemPath()' should not be annotated with: @Optional, @InputDirectory. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'logDocuments' has redundant getters: 'getLogDocuments()' and 'isLogDocuments()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'separateOutputDirs' has redundant getters: 'getSeparateOutputDirs()' and 'isSeparateOutputDirs()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'asciidoctor' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'asciidoctorExtensions' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'classpath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'defaultResourceCopySpec' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'defaultSourceDocumentPattern' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'gemPath' has @Input annotation used on property of type 'FileCollection'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'logDocuments' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'resourceCopyProxy' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'resourceCopySpec' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sourceDocumentNames' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. `
