### ISSUE TITLE
Discussion: exportExcel

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#40]
@opensource21 : just gave it a try - a really great feature! I like the evaluation for formulars...

However, I would like to discuss three design decisions:

1. Naming: should we call it exportExcel or more generic name since I guess the POI code will also handle open office for example
2. output folder: shall we use the src or the build folder? I used for some tasks the src folder because the involved tools are not available on a build server (Windows/Linux problem). Afaik, POI will also run on a Linux machine and it is running really fast (doesn't have to start Excel), so it could make sense to use the build folder.
3. output format: csv works great, an asciidoc table could give us more freedom for extensions. For example, POI could read the alignment of the cell content and create corresponding markup

What do you think?

**Comment by opensource21** [comment]
1. About Naming: As far as I know POI only supports Excel and my implementation need a recently new version of excel (XML-Format xlsx). This is part of the search pattern. However at home I only use Libre Office calc, but if I'm talking about it, I still say "My excel sheet etc.". So I think it's more a synonym then a Trademark, something like Tempo in Germany.

2. About the folder: The big advantage of storing the csv at src is, that you see the changes in the history. You can easily diff it. But it's indeed a matter of taste. Furthermore it's easier to use AsciidocFX and have a preview. Last but not least: If we put it into the normal build-process we must cleanly define in and output files.

3. I don't think that it's a good idea to have cell specific alignements. How ever it would be nice to translate bold and italic etc for a single word. But I have no idea how to realize it. I would guess that this will become more complicated. We could store it as a feature request, but at the moment I wouldn't do it. I f some one need it, he will ask for it. At the moment it's hard enough to navigate in the gradle file.

**Comment by rdmueller** [comment]
1. OK agreed
2. history - that's a good reason. Together with being independent from excel (at any point you can throw away the xls and only use the text as source)
3. I've played around with your code :-) alignment and column width is now implemented *g* will push later...

**Comment by opensource21** [comment]
Be careful to make the code in the gradle file not too complex. Perhaps [Composite builds](https://docs.gradle.org/current/userguide/composite_builds.html) are a good option.

**Comment by rdmueller** [comment]
I think we can close this discussion, can't we?
we now even have the script plugins...

**Comment by rdmueller** [comment]
I will close this now. 
We now ahve a working excelExport and I will commit some tests in just a minute. This should be enough.
please open another issue if you need to.
