### ISSUE TITLE
publishToConfluence: Error rendering macro 'code'

### ISSUE THREAD

**Issue by tkleiber** [docToolchain/docToolchain#402]
**Describe the bug**

Publish works, but contained code blocks:

```
[source, batch]
----
bin\doctoolchain c:\docToolchainTest publishToConfluence
----
```

are not generated. Instead on the Confluence page following is shown:

```
Error rendering macro 'code': Invalid value specified for parameter 'com.atlassian.confluence.ext.code.render.InvalidValueException'
bin\doctoolchain docToolchainTest publishToConfluence
```

**To Reproduce**
```
Steps to reproduce the behavior:
1. checkout latest version doctoolchain commit 2023551398bb6e09e8db12d8e89c0e39e0d8e28b
2. create an new empty directory docToolchainTest
3. set JAVA_HOME=<JDK 1.8.0_181>
4. cd <docToolchain>
5. gradlew -b init.gradle initArc42EN -PnewDocDir=<docToolchainTest>
6. configure <docToolchainTest>\Config.groovy for Confluence
7. add the code shown before to arc42-template.adoc
8. bin\doctoolchain <docToolchainTest> publishToConfluence
```

**Expected behavior**
Code should be shown formatted in Confluence like in HTML or PDF

**Screenshots**

**Configuration**
 - OS: Windows 10 Professional (Build), SLES 12 (Confluence)
 - Browser Chrome
 - Relevant SDK Versions JDK 1.8.0_181 
 - Confluence Server 7.1.0

**Additional context**

**Comment by rdmueller** [comment]
can you please retry and use `[source, bash]` or `[source, html]` instead of `[source, batch]`?
I have the feeling that confluence only allows a certain set of syntax highlighting types. "bash" and "html" should be in the list. I just found the following language in the dropdown of my own confluence instance:

ActionScript, AppleScript, Bash, C#, C++, CSS, ColdFusion, Delphi, Diff, Erlang, Groovy, HTML and XML, Java, Java FX, JavaScript, PHP, Perl, Plain Text, PowerShell, Python, Ruby, SQL, Sass, Scala, Visual Basic

I guess `powershell` might be closest to your use case.

**Comment by tkleiber** [comment]
bash and powershell works fine! Will look what match in the future.

**Comment by raul1991** [comment]
Thanks a lot @tkleiber  This makes that error disappear. But now the json looks like this

![image](https://user-images.githubusercontent.com/1281636/100458432-ce349d80-30e9-11eb-9888-52e03e22383b.png)

Is there a way to make it look like a formatted json ?

**Comment by tkleiber** [comment]
The error now happens with bash and powershell too in doctoolchain 2.2.1!

**Comment by rdmueller** [comment]
so, do I understand this correct that the problem is that confluence does not understand some of the syntaxt highlighting languages which are supported by asciidoc?

The code-block-macro and the valid languages are described here: https://confluence.atlassian.com/doc/code-block-macro-139390.html

The code in doctoolchain which tries to match asciidoc sntax highlighting with with confluence code blocks can be found here: https://github.com/docToolchain/docToolchain/blob/ng/scripts/asciidoc2confluence.groovy#L466

As I can see, there are already some rules defined.

Which rules do we miss?

**Comment by tkleiber** [comment]
After upgrading to version 2.2.1 already existing rules for bash and powershell does not work anymore. 
This works until version 2.1.0.
Maybe relevant: Configuration createSubpages = true (2.1.0) / subpagesForSections = 2 (2.2.1).

**Comment by rdmueller** [comment]
Six month ago, we changes the logic: https://github.com/docToolchain/docToolchain/blame/6e376b522d34cdb29814d33a4babe76382ec4106/scripts/asciidoc2confluence.groovy#L461

Can you see if a version from more than six month ago works for you?

Can you post the header of your asciidoc code block and the converted macro from confluence here? You can view the marco in conflzence by taking a look at the "storage format view" (I think this is what it is named in the right hand menu of a page)

**Comment by tkleiber** [comment]
Already told - 2.1.0 is working. 
Have not tried 2.2.0 because of Issue https://github.com/docToolchain/docToolchain/issues/1054 in 2.2.1: fix for publishToConfluence was broken in v2.2.0
I don't see an option "storage format view" on my confluence page here. This is confluence 7.18.1 Server here.

View Source code of the browser (Edge) shows:

```
     </p><div class="content"> 
      Error rendering macro 'code': Invalid value specified for parameter 'com.atlassian.confluence.ext.code.render.InvalidValueException'<pre class="conf-macro output-block" data-hasbody="true" data-macro-name="code">
         /test
        </pre> 
     </div> <p /> </li> 

```
"View Source" in the confluence page shows (Description of the image as I cannot upload one here):

Code Block | language = bash
/test

**Comment by rdmueller** [comment]
thanx. I now had some more time to check this problem.

I use the following AsciiDoc source

```asciidoc

.some code
[source, bash]
----
curl dtcw
chmod +x dtcw
----

```

And publish it to confluence (cloud instance) and it is correctly rendered as

![image](https://user-images.githubusercontent.com/1856308/234335744-989199dd-d7bd-4f29-a6be-9e95f2f82cff.png)

Interestingly, my confluence says the code is rendered as "Shell" where your error massage says "bash"

```
dtcw - docToolchain wrapper V0.38
docToolchain V2.2.1
docker available
home folder exists

use local homefolder install /home/rdmueller/.doctoolchain/
Java Version 11
```

what is different to your setup?

**Comment by tkleiber** [comment]
The problem exist for header deeper than second level in combination with the configuration parameter _subpagesForSections = 2_ and _docToolchain 2.2.1_.

```
== second level header

[source,bash]
----
/install
----

=== third level header

[source,bash]
----
/install
----
```

The code block from second level header is rendered fine, the code block from the third level header (generated in the sub page) gives the error.

The same code renders both code blocks fine with configuration parameters _createSubpages = true_ and _allInOnePage = false_ and _docToolchain 2.1.0_.

Off topic: Why I can not upload screenshots here?

**Comment by hardyac** [comment]
i can confirm that this is a problem in all "depper" sections than 2. Is there a known workaround instead of going back (we have a very large document where we need 3-4)? For us it will be a show stopper. We already spend one day to find the issue, but without success. Confluence 7.19.0 .

**Comment by rdmueller** [comment]
So, the first source renders as

```
<p><ac:structured-macro ac:name="toc"/></p><p>
<div class="content">
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">bash</ac:parameter><ac:plain-text-body><![CDATA[/install]]></ac:plain-text-body></ac:structured-macro>
</div>
</p><p><ac:structured-macro ac:name="children"><ac:parameter ac:name="sort">creation</ac:parameter></ac:structured-macro></p><p style="display:none">
```

or nicely formatted

```
<p><ac:structured-macro ac:name="toc"/></p>
<p>
  <div class="content">
  <ac:structured-macro ac:name="code">
    <ac:parameter ac:name="language">bash</ac:parameter>
    <ac:plain-text-body>
      <![CDATA[/install]]>
    </ac:plain-text-body>
  </ac:structured-macro>
</div>
</p>
```

The second one as 

```
<p><ac:structured-macro ac:name="toc"/></p>
<p> 
 <div class="content"> 
  <ac:structured-macro ac:name="code">
   <ac:parameter ac:name="language">
    bash
   </ac:parameter>
   <ac:plain-text-body>
    <![CDATA[
     /install
    ]]>
   </ac:plain-text-body>
  </ac:structured-macro> 
 </div>
 ```
 
 So, the main difference is that the second one is formatted and that there are line breaks around the "language" argument.

**Comment by rdmueller** [comment]
So, it seems that the bug is in this line: https://github.com/docToolchain/docToolchain/blob/ng/scripts/asciidoc2confluence.groovy#L528

Seems to be a bug or unknown feature in the jsoup library. I will prepare a workaround.

**Comment by rdmueller** [comment]
created a PR with the workaround. Do you know how you can instantly give this PR a try?

**Comment by rdmueller** [comment]
Should be now available if you use version "latest"

**Comment by tkleiber** [comment]
Latest version on Github is from march and is version 2.2.1, where the error happens! So what do you mean with latest - do mean 3.0.0-rc1?

**Comment by rdmueller** [comment]
dtcw lets you use "latest" as version which will clone the repository. This works with a local install.
But I also plan to release 3.0 this weekend

**Comment by tkleiber** [comment]
Last time I tried to dowload dtcw behind our corporate network I was not succesful. 
Therefore I downloaded the release file and work with doctoolchain in bin directory directly. 
Anyway I will wait till monday and retry it on both ways with 3.0.
