### ISSUE TITLE
What is the right way to Inject credentials in config.groovy

### ISSUE THREAD

**Issue by chess-levin** [docToolchain/docToolchain#405]
Hi Guys,

afaik the standard way of injecting credentials in gradle build process is to define the credentials in your personal file  ~/.gradle/gradle.properties.

I have to inject confluence credentials to my gradle build for using your publishToConfluence-Task. But the credential value pair defined in my gradle.properties is not set inside of config.groovy ( e.g. "${username}:${password}" == ":")

So what is the right way you propose to inject credentials into config.groovy?

And if there is yet no way to access the properties from gragle.properties, could you implement one?

**Comment by rdmueller** [comment]
thanx for the feedback.

you could fetch the credentials from the environment like this:

credentials = "${System.getenv('USER')}:${System.getenv('PASSWORD')}".bytes.encodeBase64().toString()

but I will also check how to use the `gradle.properties` file. I guess we just have to add a binding.

**Comment by nilsmahlstaedt** [comment]
A possibility would be to update the config befor binding it, should the config contain empty credentials. Maybe by inserting something like this into [publishToConfluence.gradle](https://github.com/docToolchain/docToolchain/blob/master/scripts/publishToConfluence.gradle) between lines 25 and 26?

```.groovy
 if(config.confluence.credentials.isEmpty()){
            logger.quiet("no credentials set")
            logger.quiet("trying from gradle properties")
            config.confluence.credentials = 
 ${confluenceUser}:${confluencePassword}".bytes.encodeBase64().toString()
        }
```

**Comment by rdmueller** [comment]
@nilsmahlstaedt did you already test it manually? Would you like to send a pull request?

**Comment by nilsmahlstaedt** [comment]
Yeah I did, seemded fine to me. I will send you a pull request.

**Comment by ewoks** [comment]
@rdmueller guess this is one is resolved as merge is complete. Ready to close, no?
