### ISSUE TITLE
Broken Improve & Feedback-Buttons in docToolchain-Manual 

### ISSUE THREAD

**Issue by gernotstarke** [docToolchain/docToolchain#413]
![image](https://user-images.githubusercontent.com/1233990/78877791-af49a400-7a51-11ea-916d-b07d56262979.png)

**Configuration**
 - OS: Chrome on MacOS

**Comment by rdmueller** [comment]
![image](https://user-images.githubusercontent.com/1856308/78889762-9d253100-7a64-11ea-939a-e87ade7bd426.png)

very strange. Do you see the following image/button?

![image](https://img.shields.io/badge/create-an%20issue-blue.svg)

maybe it has to do with the encoding of the buttons.

**Comment by gernotstarke** [comment]
I'll close this - it's an issue due to my adblocker...

**Comment by rdmueller** [comment]
hm. does it block all external images?
