### ISSUE TITLE
publishToConfluence: ancestorId does not work

### ISSUE THREAD

**Issue by k-werner** [docToolchain/docToolchain#419]
**Describe the bug**
I'm trying to publish my document to confluence and put an ancestorId in the Config.groovy file. Unfortunately the ancestorId is not used and the pages are published to the space root. I use a personal confluence space inside of my company.

**To Reproduce**
1. generateHtml
2. configure an existing ancestorId
3. publishToConfluence
--> Content is published to the space root and not to the page with the ancestorId

**Expected behavior**
When I define an ancestorId, I expect that the pages are published to the page with the ancestorId

**Configuration**
 - OS: Windows using the Git Bash with doctoolchain shellscript on path
 - Relevant SDK Versions JDK 11

**Additional context**
My Configuration in Config.groovy:
confluence = [:]
confluence.with {
    input = [[ file: "build/html5/showcase_docs_as_code.html" ]]
    api = '<my-api>'
    ancestorId = '4711'
    spaceKey = 'myspace'
    createSubpages = false
    pagePrefix = ''
    pageSuffix = ''
    credentials = "${System.getenv('USER')}:${System.getenv('PASSWORD')}".bytes.encodeBase64().toString()
    extraPageContent = '<ac:structured-macro ac:name="warning"><ac:parameter ac:name="title" /><ac:rich-text-body>This is a generated page, do not edit!</ac:rich-text-body></ac:structured-macro>'
}

**Comment by k-werner** [comment]
I have looked for other possibilities to publish the AsciiDoc documentation to confluence. I found the following Maven plugin: [Confluence Publisher](https://confluence-publisher.atlassian.net/wiki/spaces/CPD/overview?mode=global).

It seems to work very well, but with some drawbacks using the docToolchain.

- The images are resolved relative to the location of the referencing AsciiDoc file and the `:imagesdir:` attribute is not evaluated.
- subsections are creating depending on the source structure and if you use this feature, the ordering of the created child pages cannot be influenced

But maybe it is worth thinking about the integration of this plugin.

**Comment by k-werner** [comment]
I found the problem in the file `asciidoc2confluence.groovy`  the initialization of the variable `parentId` did not include the `Config.groovy` file. I also removed the unused variable `masterid`.

Pull Request is created https://github.com/docToolchain/docToolchain/pull/422

**Comment by rdmueller** [comment]
sorry, I had not much time lately to work on these issues.

Thanx for the PR! And welcome to the growing List of Contributors!

The original config was designed to have an `ancestorId` per file, eg

```
input = [[ file: "build/html5/showcase_docs_as_code.html", ancestorId: `1234` ]]
```

because every file could be placed somewhere else in the tree of documents.

As I read your PR, it will add the possibility to have a globally configured ancestorId.
I guess this can be quite useful. 
I also guess that the main problem you faced came from the documentaiton.
The comments where not really clear about where to specify the ancestorId.
Maybe we should add it to the example.

Would you mind to re-visit the comments and see what we would have to change to describe the options in a better way?

**Comment by k-werner** [comment]
Thank you for your answer.
Obviously I didn't read the documentation in-depth. In the `publishToConfluence` task it is described in the comments of the example code. I think it would be more clear, if the information of the comments are put above of the example. It would also be helpful, if the example code includes the `ancestorId` as you mentioned in your comment.

In my opinion it is enough, when the `ancestorId` only can be defined per file in the input array.

**Comment by rdmueller** [comment]
I've accepted the PR. Can you please check that it works like expected and close this issue?

Thanx for being an active conributor!

**Comment by k-werner** [comment]
I've checked out the master branch and tried to publish some pages to our Confluence and it works as expected. 
Thank you and you're welcome.
