### ISSUE TITLE
exportPPT does not work

### ISSUE THREAD

**Issue by k-werner** [docToolchain/docToolchain#420]
**Describe the bug**
I've tried to export the demo PowerPoint presentation, but it throws the following error message:
![image](https://user-images.githubusercontent.com/64542321/80696647-f9192d80-8ad7-11ea-9c69-6519c87419a7.png)

After commenting out the exportEA.gradle module in the build.gradle file I got the following error message:

![image](https://user-images.githubusercontent.com/64542321/80696689-0df5c100-8ad8-11ea-9594-ee65d77de324.png)

**To Reproduce**
1. initialize a project
2. copy the Demo.pptx to the src of the new project
3. run: docToolchain . exportPPT

**Expected behavior**
The slides and the speaker notes of the PowerPoint are exported. 

**Configuration**
 - OS: Windows with cmd and Git Bash
 - Relevant SDK Versions JDK 11

**Comment by rdmueller** [comment]
short explanation: the `exportEA` contains a method called `streamingExecuted` which is used to execute VisualBasic scripts. It shows the output while executing.

That is why `exportEA` is needed.

let's look into the `exportEA`...

so, it seems the error occurs while the VisualBasic script is executed...

it seems that you use `cmd` to execute the task. 
can you please try to use powershell?

**Comment by k-werner** [comment]
Thank you for your reply.

I tried it using Powershell and got the same error message:
![image](https://user-images.githubusercontent.com/64542321/82987394-baec2c80-9ff7-11ea-96ed-45ba2c3e7c41.png)

I tried it also with Git bash with the same result.

**Comment by Hellmy** [comment]
Had the same issue... Seems like a character encoding thin.
parsing the the input String for the cmd solves the issue
```
String s = new String(delegate.value, Charset.forName("UTF-8"));
def p = "cmd /c ${s}".execute()
```
