### ISSUE TITLE
generateHTML output two images/images/ in the html

### ISSUE THREAD

**Issue by chenryn** [docToolchain/docToolchain#421]
**Describe the bug**
the output html file contains such lines: `<img src="images/images/policy-list.png" alt="policy list">`, but the real imagedir is images/xxx

**To Reproduce**
1. I install the docToolchain follow the "Linux with download as zip" section.
2. The file path in my disk as '~/gitdir/docs' and '~/gitdir/docToolchain-master'
3. Run ./gradlew -b init.gradle initExisting -PnewDocDir=../docs
3. I change inputPath to '../docs', and inputFiles to 'MYFILE.adoc' in the Config.groovy
4. Run ./bin/doctoolchain . generateHTML
5. Check ./build/docs/html5/MYFILE.html and see the "images/images/xxx" error. the real images were copied into ./build/docs/html/images/xxx

**Expected behavior**
need to generate "images/xxx" in the HTML

**Screenshots**

**Configuration**
 - OS: macos 10.15.4

**Additional context**
I try to move my ../docs into ./docToolchain-master/src/docs and change the Config.groovy back as default, but got images/images/ again.

**Comment by rdmueller** [comment]
thanx for the error report and sorry for the time it took me to react.

how do you specify your images?

could it be that you specify them as `image::images/xxx[]` ?

AsciiDoc has an attribute `:imagedir:` which is set to `images`. 
So, the above statement would leed to the behaviour you describe.

**Comment by chenryn** [comment]
tks.
