### ISSUE TITLE
Enhance exportEA for dedicated connections and option to filter on export packages

### ISSUE THREAD

**Issue by PeterStange** [docToolchain/docToolchain#426]
One drawback of the script exportEA is the missing support of database connections for enterprise architect projects.
Only local project files can be used. A possibility to configure the connection string for the project database shall be added.
Another disadvantage is the missing possibility to filter the packages to be exported. 
Better approach: add a configuration for a list of package GUIDs to be used for export. 
Both, configuration and functionality is missing in current exporter: exportEA

An additional configuration shall be added to set the project to be opened and to add none, one, or multiple packageGUIDs used as a filter for packages used for export.
All parameters shall be optional. If not set, the current behaviour shall retained.

**Comment by rdmueller** [comment]
thanx for your feedback. I think I already had once a filter for GUIDs, but couldn't make it open source.
The filter was the bigger problem when connecting to a "real" database (opposed to the jet-database engine files).

But I also remember that there was a trick to connect with the current code to a database. Isn't it possible to store the database connection string within a project file which then can be used to conenct to the database through docToolchain? I thought it was a solution like this which we used...
