### ISSUE TITLE
Problems by following the documentation from Initializing till building

### ISSUE THREAD

**Issue by NWest09** [docToolchain/docToolchain#430]
Hey together,
I hope you can help me, and I can help other people with their journey to get start with docToolchain.

I have 4 issues and 3 solutions for them. So I need help for 1 of them.

What I did so far:

1.)	Downloading the Files:
        a.        docToolchain.zip
        b.        asciidoctor-reveal.js-9667f5c5d926b3be48361d6d6413d3896954894c.zip
        c.        reveal.js-tags-3.3.0.zip
2.)	Extract it all in the right place as recommended in the documentation
        a.        `C:\Progamme\docToolchain`
        b.        `\resources\reveal.js`
        c.        `\resources\asciidoctor-reveal.js`
3.)	Checking installed software
	a.	Java
java version "1.8.0_251"
	b.	Gradle (I know that docToolchain use a different version, but I tried the newest one for the tutorial below mentioned)

Gradle 6.5
			Build time:   2020-06-02 20:46:21 UTC
			Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4
			Kotlin:       1.3.72
			Groovy:       2.5.11
			Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
			JVM:          1.8.0_251 (Oracle Corporation 25.251-b08)
			OS:           Windows 10 10.0 x86
4.)	Start PowerShell and go to the directory and type in:
	a.	`./gradlew -b init.gradle initArc42DE -PnewDocDir=./src/docs/TestVS`Getting this result:
```
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
…
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
```

Solution for me was:
1.)	in the file Gradle.properties
2.)	Disable Line 2
a.	`org.gradle.jvmargs=-Xmx2048m`
b.	`//org.gradle.jvmargs=-Xmx2048m`

I don’t know why my computer had a Problem with this size, but okay it works for me to disable the maximum size – I know there will be maybe some troubles with that later on, but I need a progress and this problem will pop up in future.

So after that problem I had a problem how to type `-PnewDocDir=<newDocDir>` in Windows because the example in the documentation was for Linux and I think for advanced people with skills they already know how to do it in the right way but me helped: https://docs-as-co.de/getstarted/tutorial2

As example for me in windows it worked with:
`PS C:\Progamme\docToolchain> ./gradlew -b init.gradle initArc42DE „-PnewDocDir=./src/docs/TestVS"`

If I want to use it in the structure in docToolchain, which I prefered as a starter with docToolchain, so nothing else should be go so wrong, I hoped so I used the src directory.
Is this the proper way, I’m not sure, but I didn’t manage it to get in a other directory, even if I tried to get well known with the script files and config files as it is described in the documentation.

> docToolchain by default uses src/docs as the directory of your documentation. If you use a different directory you need to go to <docToolchain home> and set the inputPath property in gradle.properties to your/path.

Maybe somebody can give me a hint to solve that I can use for example `E:\user\work\morePath\` problem?

So next real problem after this, is right now where I’m really struggling:

```
PS C:\Progamme\docToolchain> doctoolchain.bat ./src/docs/TestVS                                                         
> Configure project :
arc42-template.adoc
You are using one or more deprecated Asciidoctor Gradle plugin features. To help with migration run with --warning-mode=all.

> Task :exportChangeLog FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Progamme\docToolchain\scripts\exportChangelog.gradle' line: 15

* What went wrong:
Execution failed for task ':exportChangeLog'.
> Could not find matching constructor for: java.io.File(String, ConfigObject)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


BUILD FAILED in 1s
1 actionable task: 1 executed
```

So I go to the mentioned File and look at line 15

```
//tag::exportChangeLog[]
...
        def cmd = "${config.changelog.cmd} ."
        def changes = cmd.execute(null, new File(docDir, config.changelog.dir)).text
        def changelog = new File(targetDir, 'changelog.adoc')
        logger.info "> changelog exported ${changelog.canonicalPath}"
        changelog.write(changes)
...
```

For `new File(docDir, config.changelog.dir)` I need a docDir so maybe this should be the troublemaker so I tried some varaiatons like:

> - `" ./src/docs/TestVS"`
> - `'./src/docs/TestVS'`
> - `"docDir=./src/docs/TestVS"`
> - `docDir=./src/docs/TestVS`
> etc.

I don't know if it is right or not, that I'm not defining docDir well.
So I need there some advice.

So after this long text I try to summarice it a little bit:

Solved problems:
1.)
Problem with starting a Gradle Daemon, 
> `Could not reserve enough space for 2097152KB object heap`
> Solved:
> 1.)	in the file Gradle.properties
> 2.)	Disable Line 2
> a.	`org.gradle.jvmargs=-Xmx2048m`
> b.	`//org.gradle.jvmargs=-Xmx2048m`

2.)
Problem with typing the newDocDir:
> `-PnewDocDir=<your directory>`
Solved for me by:
> `"-PnewDocDir=./your directory"`

3.)
> `exportChangelog.gradle' line: 15`

Only that I think I am typing the path wrong again like before.
Yep that was it.

`PS C:\Progamme\docToolchain> doctoolchain.bat ./src/docs/TestVS generateHTML` 
You should read "3.1. Conventions" for more details at this point.

Unsolved problem:

4.)
> default directory changing from src/docs to another harddisk directory
For example "E:\..."

Thank you for your patience and help have a nice Sunday.
After editing I wish you a nice start in the week.

Best regards
NWest

Editing: Changing some typing errors and adding my failure of building.

**Comment by rdmueller** [comment]
thanx for your detailed report. This helps us to make docToolchain better.

1) I've added a note to the FAQ section: https://doctoolchain.github.io/docToolchain/#_known_error_messages 
I hope this helps others.

**Comment by rdmueller** [comment]
2) this heavily depends on the shell you use and I also don't know the exact rules when to use `"` and when not. :-|

**Comment by rdmueller** [comment]
3) glad that you found the problem!

**Comment by rdmueller** [comment]
4) I think to solve this, the manual does not a good job at explaining the general concept:

docToolchain is used for projects and every project might bring its own copy of docToolchain or use an instance which is installed in some central directory. Each project resides in its own directory.

Within those project-directories, there might not only be the documentation, but also code. For Java projects, the code is kept in `/src/main/java` and the default location for docs in docToolchain is `src/docs`.

This explains why you would not want to switch the `docsDir` (`src/docs`) to someting like `e:/...`. I guess the manual is also not really clear about this. I think this part of the manual needs a rework: https://doctoolchain.github.io/docToolchain/#_build .

So, in the config, there is the `docsDir` which defaults to `src/docs` and if you use docToolchain as command line tool (it seems that you do so), you should add the `<path to docToolchain>/bin` to your path and use it as `doctoolchain.bat <projectDir> generateHTML`. In this case, `<projectDir>` can be something like `e:/somePath`.

Hope this helps.

We currently work on brushing up the general user experience to address exactly the points you mentioned here. But it will still take some time.

**Comment by NWest09** [comment]
Dear Mr Mueller,

1.) 
Thank you for adding this to the FAQ section.
Hope it help other people.

2.) 
I use right now my onboard Powershell from Windows:
`PS E:\Test> $PSVersionTable`
> Name | Value
> PSVersion | 5.1.18362.752
> PSEdition | Desktop
> PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0...}
> BuildVersion | 10.0.18362.752
> CLRVersion | 4.0.30319.42000
> WSManStackVersion | 3.0
> PSRemotingProtocolVersion | 2.3
> SerializationVersion | 1.1.0.1

Maybe this is interesting. for people who are searching for the same problems as I had.

3.)
I am also glad that I lost my blindness.

4.)
I did this already to my path, but I had trouble with the initialisation process, so I decided to use docToolchain as command line tool, back to the basic should help to get an improvement. That was my approach.

After your hint I found for me a workaround:

> PS C:\Windows\system32> `Set-Location -Path C:\Progamme\docToolchain` 
> PS C:\Progamme\docToolchain> `.\gradlew.bat -b init.gradle initArc42DE "-PnewDocDir=./src/docs/TestVS2"`
> PS C:\Progamme\docToolchain> `Move-Item -Path C:\Progamme\docToolchain\src\docs\TestVS2 -Destination E:\Test\`
> PS C:\Progamme\docToolchain> `docToolchain.bat E:\Test\TestVS2 generatePDF`

So this was just a test and I will take care of your advice with the directories in my next new structure:
```
> C:\<Path>\<ProjectName>\src\main\<CodeLanguage>\<CodeFilesEtc>
> E:\<Path>\<ProjectName>\src\docs\<documentation with a arc42-Template, which is used as a wardrobe, which can be filled up, if necessary>
```
https://www.youtube.com/watch?v=GkXpe-tZtNg&t=364s

That is the idea behind that directories structure, right?

I will do a script for me I think so, I am not sure if it helps here somebody, but I will post it, if I am satisfied with my solution.

Thank you for your reply it helped me a lot as a starter in documentation docs as code with docToolchain. I will be happy, if you brushed docToolchain up.

Best regards
NWest

**Comment by rdmueller** [comment]
btw: I made some progress with the new installation process. I hope I can publish it soon.

**Comment by NWest09** [comment]
I hope you will publish it soon.

I will keep an eye on docToolchain. 

Best Regards
NWest

**Comment by rdmueller** [comment]
first baby steps are coming: docToolchain will soon be on sdkman! https://sdkman.io/sdks#doctoolchain
