### ISSUE TITLE
Dockercontainer & Pandoc

### ISSUE THREAD

**Issue by dr460neye** [docToolchain/docToolchain#433]
**Describe the bug**
Seems like pandoc is not part of the docker container atm.

**To Reproduce**
Search for the pandoc inside the newest container release. Try to run adoc to pandoc conversion.
Both seems to fail.

**Expected behavior**
Container is able to convert adoc to docx

**Configuration**
 - Docker

```

outputPath = 'build/docs'

// Path where the docToolchain will search for the input files.
// This path is appended to the docDir property specified in gradle.properties
// or in the command line, and therefore must be relative to it.

inputPath = 'Folder/';
inputFiles = [
        [file: 'file.adoc', formats: ['html','adoc','docbook','docx']],
]
taskInputsDirs = ["${inputPath}/media"]
taskInputsFiles = []
```

`doctoolchain . --stacktrace --info convertToDocx -PmainConfigFile=....`

**Comment by ehmkah** [comment]
I opened a PR for this requirement. I am happy to hear your feedback

**Comment by ehmkah** [comment]
Now there is a docker-image with pandoc available - https://hub.docker.com/r/doctoolchain/doctoolchain-with-pandoc

I believe this issue could be closed.
