### ISSUE TITLE
exportEA do not use docDir for export folder

### ISSUE THREAD

**Issue by PeterStange** [docToolchain/docToolchain#439]
**Describe the bug**
A doc-as-code project is set up using docToolchain as an external repository. 
[docToolchain]/bin folder is added to PATH environment variable.
Running on windows.
From inside the docDir directory the command is called:"doctoolchain . exportEA"
The export is executed.
expected:
Instead of expected location "[docDir]/src/docs/images/ea",
diagrams are exported into "[docToolchain]//src/docs/images/ea".

reason:
exportEAP.vbs does not use the docDir as a base.
exportEAP.vbs uses the current directory as base.
The current directory is set to the script dir instead.

Is there any workaround know to avoid this? Maybe a missing configuration?

**Comment by rdmueller** [comment]
Thanx for the PR!!! I guess this issue can now be closed?

**Comment by PeterStange** [comment]
Thanx for clarification of the test failure. Yes, we can close it.
