### ISSUE TITLE
Update org.apache.httpcomponents:httpclient and commons-beanutils:commons-beanutils

### ISSUE THREAD

**Issue by pperez** [docToolchain/docToolchain#440]
**Describe the bug**
I can't use docToolchain on my environment as i'm using nexus mirrors that blocks open source components that have vulnerabilities. If i try to even do a doctoolchain . generateHTML i get an error pointing me that i have some unavailable libs (Due to them being vulnerable)

**To Reproduce**
1. Init a project with existing docs
2. Execute doctoolchain . generateHTML
4. Get error:
~~~bash
doctoolchain . generateHTML
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :
arc42-template.adoc
You are using one or more deprecated Asciidoctor Gradle plugin features. To help with migration run with --warning-mode=all.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Development\Programs\apps\docToolchain\build.gradle' line: 82

* What went wrong:
A problem occurred evaluating root project 'docToolchain'.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not download httpclient-4.2.1.jar (org.apache.httpcomponents:httpclient:4.2.1)
      > Could not get resource 'https://mycorpmirror/repository/gradle-plugins-maven-proxy/org/apache/httpcomponents/httpclient/4.2.1/httpclient-4.2.1.jar'.
         > Could not GET 'https://mycorpmirror/repository/gradle-plugins-maven-proxy/org/apache/httpcomponents/httpclient/4.2.1/httpclient-4.2.1.jar'. Received status code 403 from server: Requested item is quarantined
   > Could not download commons-beanutils-1.8.0.jar (commons-beanutils:commons-beanutils:1.8.0)
      > Could not get resource 'https://mycorpmirror/repository/gradle-plugins-maven-proxy/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.jar'.
         > Could not HEAD 'https://mycorpmirror/repository/gradle-plugins-maven-proxy/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.jar'. Received status code 403 from server: Requested item is quarantined

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
~~~

**Expected behavior**
I expect the build to succeed and generate my htmls from asciidoc

**Screenshots**
N/A

**Configuration**
 - OS: Windows 10
 - SDK Versions Adoptopenjdk 11

**Additional context**
I'm using a corporate maven mirror, i've struggled a little bit to use it, as besides configuring the maven mirror for libs itself i also had to configure the plugin mirrors (gradle was trying to use the plugins.gradle.org repo, which i can access because we're not allowed to) and editing some gradle scripts in doctoolchain as they were pointing directly to the gradle plugin maven repo (i.e in scripts/publishToConfluence.gradle, scripts/htmlSanityCheck.gradle, scripts/exportMarkdown.gradlescripts/exportJiraIssues.gradle, scripts/exportExcel.gradle, scripts/AsciiDocBasics.gradle).
With that sorted out i wanted to upgrade the components (org.apache.httpcomponents:httpclient and commons-beanutils:commons-beanutils) as they were unavailable on my corp mirror due to vulnerabilities present.
I tried excluding them and manually adding them to doctoolchain build.gradle:
~~~groovy
configurations {
 all*.exclude group: 'org.apache.httpcomponents', module:'httpclient'
 all*.exclude group: 'commons-beanutils', module:'commons-beanutils'
}
dependencies {
    testImplementation(
            ('junit:junit:4.12'),
            ('org.spockframework:spock-core:1.3-groovy-2.5'),
            ('com.athaydes:spock-reports:1.6.2'),
            //('org.slf4j:slf4j-api:1.7.13'),
            //('org.slf4j:slf4j-simple:1.7.13'),
            gradleTestKit()
    )
    implementation 'org.apache.httpcomponents:httpclient'
        constraints {
            implementation('org.apache.httpcomponents:httpclient:4.5.12') {
                because 'previous versions have a bug impacting this application'
            }
        }

    implementation('commons-beanutils:commons-beanutils') {
        version {
            strictly '1.9.4'
        }
    }
}
~~~
But i had no luck, it's still trying to download them, and as i'm a real noob using gradle i don't know the right approach to be able to update those libs

**Comment by rdmueller** [comment]
wow, that took me a time to find a solution but it seems that the following works:

replace the dependency definition of the http-bùilder` with the following code:

        classpath ('org.codehaus.groovy.modules.http-builder:http-builder:0.7.2') {
            exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        }
        classpath 'org.apache.httpcomponents:httpclient:4.5.12'

unfortunately, I currently lack the time to further test this (test if the code still runs with the new version)
maybe I find some more time later this week

**Comment by pperez** [comment]
Awesome! So far i've tried the generateHtml task and it's working, thank you!

**Comment by mh182** [comment]
Can we close this issue?
