### ISSUE TITLE
ExportEA: Diagram Notes are not exported

### ISSUE THREAD

**Issue by AndreaMcls** [docToolchain/docToolchain#450]
The Diagram Objects notes are exported as expected, however the Diagram Notes are not exported.

**Comment by rdmueller** [comment]
I see, I guess the docs are missing an important detail:
you have to prepend `{adoc:filename}` to your notes in order to export them to `filename.adoc`. All notes with the same `filename` will be appended.

Does this info help?

**Comment by AndreaMcls** [comment]
Yes, it is correct that only elements notes with the prefix `{adoc:filename} `are exported.  It is also correct that the diagram elements are exported in a .ad file and  all the elements belonging to a diagram are appended in one .ad file. This works for the elements of a diagram but the note of the diagram itself is not exported.
The fix of this is just one line of code in `exportEAP.vbs`, I will do a pull request as soon as I can.

**Comment by rdmueller** [comment]
ah! cool. I never had this use case. Thnax for the PR!

**Comment by AndreaMcls** [comment]
Before proceeding with the PR I need approval from my employer, I'm not sure how long it will take.

**Comment by AndreaMcls** [comment]
thank you @PeterStange for the PR
