### ISSUE TITLE
Missing example file in documentation

### ISSUE THREAD

**Issue by ewoks** [docToolchain/docToolchain#453]
**Describe the bug**
Current documentation is missing linked file [myfile.json](https://doctoolchain.github.io/docToolchain/attachement/myfolder/myfile.json)

**To Reproduce**
1. go to [publish to confluence configuration](https://doctoolchain.github.io/docToolchain/#_configuration_3) part of the documentation
2. click the link in **enableAttachments example** section to "My API definition"
3. See error: "404 File not found"

**Expected behavior**
File is available

**Comment by rdmueller** [comment]
hm. I guess the bug is that the `link` macro was excaped - it shouldn't be a link to a file but an example how to link to it. I just fixed this.

Reopen if you thing that was the wrong fix :-)
