### ISSUE TITLE
Force execution to stop with failure on missing image reference

### ISSUE THREAD

**Issue by PeterStange** [docToolchain/docToolchain#455]
I'm looking for a way to cause an failure of the tool execution in case the image reference is invalid and the image couldn't be found. 
ascciidoctor offers this by using command line attributes:  "asciidoctor -a attribute-missing=warn --failure-level=WARN"
How can I add those parameters when calling a task like generateHTML. 
Tried to follow the call sequence and extended attributes defined in AsciiDocBasics.gradle 
    attributes (
        'plantUMLDir'         : '',
        'attribute-missing'   : 'warn'

But this didn't changed the behaviour. 
Is there any documentation available about the flow of the execution chain ?
Any existing possibility to enable this kind of warnings?

**Comment by rdmueller** [comment]
I guess the solution for this is in the following ticket:
https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/154

**Comment by mh182** [comment]
Closing since addressed with #1098
