### ISSUE TITLE
Update documentation for Jira Excel

### ISSUE THREAD

**Issue by ewoks** [docToolchain/docToolchain#459]
**Update** documentation source and **build** documentation related to [#454]( https://github.com/docToolchain/docToolchain/issues/454) & its [PR](https://github.com/docToolchain/docToolchain/issues/458). 
Added features:
- Jira configuration for multiple request to Jira API
- Saving Jira results to Excel files
- Basic support for custom fields in Jira results

Documentation should briefly describe new Jira configuration, explain flexibility and mention that results (issues) will be saved in different files for each given JQL, in different formats (Excel & Asciidoc) depending on configured flags 

checklist:
 * [x] Documentation updated
 * [ ] Documentation built and pushed
 * [x] Emphasize deprecation of old Jira configuration, which will be removed soon

**Comment by rdmueller** [comment]
@ewoks is this on your todo-list? May I assign you?

**Comment by ewoks** [comment]
yes, I can do it
