### ISSUE TITLE
Add ancestorName convinience attribute to confluence configuration

### ISSUE THREAD

**Issue by ewoks** [docToolchain/docToolchain#460]
Publishing Confluence documentation often needs to be done to specific location in a Confluence space document tree (nested under specific "node")

This is currently possible by using attribute `ancestorId`. As great as this feature is, at the same time it is slightly inconvenient to use it. Value of this attribute should be the number that represents ID of parent page in Confluence, but this value is not so obvious to find. 

As documents titles in Confluence need to be unique, proposal for improvement of this situation is following:
1. Introduce new convenience attribute `ancestorName`
2. when this attribute exists `asciidoc2confluence.groovy` script will (in the background) try to find id of the page defined by page title.
- If this attempt fails (misspelled name, non existing page name, etc), let's make it graceful and workflow continues as `ancestorName` was never defined.
- if attempt to retrieve page id by page name is successful, that id will take priority over possibly defined `ancestorId` and documentation should clearly state this priority

**Comment by dr460neye** [comment]
Would you see a support for renaming in there?

**Comment by ewoks** [comment]
@dr460neye can you please clarify? I'm not sure I understood what you mean by "support for renaming"
