### ISSUE TITLE
Duplicate/legacy changelog configuration

### ISSUE THREAD

**Issue by ewoks** [docToolchain/docToolchain#462]
It seems like there is forgotten file containing changelog configuration at: **`/scripts/ChangelogConfig.groovy`**

Actual changelog configuration (used by `exportChangelog.gradle`) is already present in main `Config.groovy` and I couldn't find any other script which references the file in question, so my assumption is that this is legacy file and it can be removed.

**Comment by ewoks** [comment]
@rdmueller can you confirm this file is for removal please? 
Maybe this issue can be tagged as  "very easy", "first contributor" or similar?

**Comment by rdmueller** [comment]
yes, I think I can confirm this. marked for Hacktoberfest :-)

**Comment by rdmueller** [comment]
seems that this can be closed...
