### ISSUE TITLE
GitHub Pages site of the project renders 404

### ISSUE THREAD

**Issue by ewoks** [docToolchain/docToolchain#463]
It seems like github pages documentation site is not available on https://doctoolchain.github.io/ 

![Screenshot from 2020-08-24 18-39-42](https://user-images.githubusercontent.com/1666500/91072167-6463ae00-e639-11ea-9312-b5a7aa8e6719.png)

**Comment by ewoks** [comment]
Seems that is configured for `https://doctoolchain.github.io/docToolchain/` instead of `https://doctoolchain.github.io` like I thought.
IMHO root page looks nicer and it didn't occur to me to check there.

In case you want to configure it with the root page, [here is the guide](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site), otherwise ticket can be closed :)

**Comment by rdmueller** [comment]
yes, root page looks nicer, but for this, the docs have to be in a repository called `doctoolchain.github.io`.
I could now create such a repository and add a 404 which redirect to the right page (or index page which redirects)

**Comment by rdmueller** [comment]
please recheck. I guess we can close this now. :-)

**Comment by ewoks** [comment]
Great idea👍 I almost didn't notice redirect 😊
We can close this one
