### ISSUE TITLE
Update documentation for passing credentials as parameters

### ISSUE THREAD

**Issue by ewoks** [docToolchain/docToolchain#477]
Documentation for Jira & Confluence related tasks should be updated asap, to reflect changes in #476 

It is crucial to inform and motivate users to start passing credentials as parameters independently of execution (local machine or CI/CD). This way we will promote best practice and avoid exposing of sensitive data in users repositories.

**Comment by rdmueller** [comment]
PR has been merged, so I guess we can close this issue, can't we?
