### ISSUE TITLE
test Failing when using the gradle wrapper

### ISSUE THREAD

**Issue by AndreaMcls** [docToolchain/docToolchain#486]
**Problem Description**
The test tasks are failing when executing with the gradle wrapper.
The same tests are not failing when a local gradle installation eg. version 6.4 is used.
All other tasks eg: generateHTML, exportEA, pulishToConfluence, etc..  are working as expected.

**To Reproduce**
1. cd to doctoolchain rootfolder
2. ./gradlew test --info
3. All tests are failing
4. Error Message:
`  > Configure project :
    Evaluating root project 'docToolchain' using build file 'D:\test\docToolchain\build.gradle'.

    FAILURE: Build failed with an exception.

    * Where:
    Build file 'D:\test\docToolchain\build.gradle' line: 6

    * What went wrong:
    Plugin [id: 'org.asciidoctor.convert', version: '2.4.0'] was not found in any of the following sources:

    - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
    - Plugin Repositories (could not resolve plugin artifact 'org.asciidoctor.convert:org.asciidoctor.convert.gradle.plugin:2.4.0')
      Searched in the following repositories:
        Gradle Central Plugin Repository

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 5s
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$2.execute(DefaultGradleRunner.java:255)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner$2.execute(DefaultGradleRunner.java:251)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:324)
        at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:251)
        at docToolchain.ExportChangeLogSpec.test creation of log file(ExportChangeLogSpec.groovy:19)
`

**Expected behavior**
test are executed and passed. Tests are passed when using a manual installed gradle (for example v6.4)

**Configuration**
 - OS:  WIndows
 - Relevant SDK Versions JDK 14

**Additional context**

**Find a good headline**
test Failing when using the gradle wrapper

Example:
exportContributors throws exception when ...

**Comment by ehmkah** [comment]
Gradle 6.0.1 does not support JDK 14 https://docs.gradle.org/6.0.1/release-notes.html. Maybe you could choose an older version.

**Comment by rdmueller** [comment]
hm. It is true that Gradle 6.x does not support JDK14, but I think it then should fail sooner.
I get the feeling that it is something like a proxy configuration.

Could it be that you installed gradle instance has some kind of proxy configured which the wrapper lacks?
It says that it can't download a ressource which normally should be downloadable...

**Comment by ehmkah** [comment]
Proxy would be my seconds guess - but when I run it locally with jdk14 I get an other error. So combining JDK14 with gradle 6.0.1 seems not to be a good idea, anyway.

**Comment by rdmueller** [comment]
just gave it a try:

Start IDE through gitpod:

httsp://gitpod.io#https://github.com/docToolchain/docToolchain

downgrade Java

> sdk install java 8.0.265-open

run test

> ./gradlew test

works.

Next step is to upgrade the automated test to refelct the requirement for newer java version. This will make an upgrade of gradle necessary

**Comment by ehmkah** [comment]
@rdmueller - Do you expect something like 
```
sourceCompatibility = '11'
targetCompatibility = '11'
``
in `build.gradle`? Which version of jdk should be used? Or do you only want to define the jdk version for running the tests?

**Comment by AndreaMcls** [comment]
I have tested with jdk11, and still have the same error.
I exclude it is a proxy issue as well, because if I delete the "username"/.gradke intsallation previously done by the wrapper all the components are downloaded and I can perform regular doctoolchain tasks.
@PeterStange also tested this on his machine and got the same error.

**Comment by rdmueller** [comment]
I am sure that the artefact exists:
https://plugins.gradle.org/plugin/org.asciidoctor.convert

Regarding the proxy: it could be that the gradle plugin repository is replaced with a cached version which does not contain the latest artefact.

Somehow, you should be able to run gradle in such a way that it outputs the URL where it is looking to the artefact. Maybe you have to add `--debug`.

I think it should be something like:
https://plugins.gradle.org/m2/org/asciidoctor/asciidoctor-gradle-jvm/

Here, you see al of the available versions. If you cached version does not have the 2.4.0 version, you could try to downgrade.

**Comment by PeterStange** [comment]
I'm convinced it is a proxy configuration issue. 
In all other use cases the current project settings (gradle.properties) are taken into account and no failure happen.
But calling the test task, it is a different behaviour.
Same is described at: [https://github.com/gradle/gradle/issues/1233].
Adding the cntlm proxy url and port didn't work for me, but I added the real proxy url, port, username and password to the build.gradle.
like this:
test {
  systemProperties = ['systemProp.http.proxyUser':"[username]", 'systemProp.http.proxyPassword':"[password]", 'http.proxyHost':"[proxy address]", 'http.proxyPort':"[Port]",'https.proxyHost':"[proxy address]", 'https.proxyPort':"[Port]", 'http.ssl.insecure':"true", 'systemProp.http.ssl.insecure':"true", 'systemProp.http.ssl.ignore.validity':"true"]
}

Of course, we need to find a solution without the need to set the password and username, but this is another issue.

Same parameter values are used when starting the JVM for the Gradle Test Runner execution.

**Comment by rdmueller** [comment]
ah - guess you are right. I didn't think of that the tests don't take the proxy settings into account...

**Comment by AndreaMcls** [comment]
I confrim the issue is solved with @PeterStange  proposal. 

An alternative way without need to set password and user name is to add the systemProp for the proxy to the gradle.properties in the doctoolchain folder. 
The systemProp I have used are the same I have in my _"username"/.gradle/gradle.properties_, there is no need to add the real proxy url, port, username and password. 
Both solution are a workaround, as they imply a mod to the main doctoolchain _gradle.properties_ or _gradle.build_.

**Comment by rdmueller** [comment]
these are great news! I think we should add this information somewhere to the docs.
any idea where it could be found?

**Comment by AndreaMcls** [comment]
It fits in the chapter "4.1 How to run test". I'm waiting for my employer approval to send contributions.

**Comment by rdmueller** [comment]
@AndreaMcls did you get the approval?

**Comment by AndreaMcls** [comment]
yes, pull request is coming!
