### ISSUE TITLE
ConfluenceConfig.groovy missing

### ISSUE THREAD

**Issue by ambition-consulting** [docToolchain/docToolchain#492]
You write about "scripts/ConfluenceConfig.groovy", but this seems to have moved inside the Config.groovy, right?

---
#page:manual/02_install.adoc

**Comment by ewoks** [comment]
That's correct. Whole configuration, including confluence is in one file: `Config.groovy`.
I assume you refereed to [this](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/02_install.adoc#publish-to-confluence) mistake in documentation, no? Would you be interested in correcting it and making PR?

**Comment by rdmueller** [comment]
I removed the last chapter. Please reopen this issue if you see more room for improvement.
