### ISSUE TITLE
unnecessary error message due to configuration not being set

### ISSUE THREAD

**Issue by PeterStange** [docToolchain/docToolchain#493]
**Describe the bug**
On every call (e.g. gradle tasks) an unnecessary error message due to configuration for exportOpenAPI not being set.
This causes questions marks on my side and many questions to be answered.
It's a "Don't care." message. If exportOpenAPI is not used, no specification needs to be set.
So, logging an error is annoying.
I'll commit a small pull request to reduce the log level from error to info instead.

**To Reproduce**
call 'gradle task' or any other task (gradle generatePDF)
On top of each log, an error is shown: 
---> OpenAPI specification file not found in Config.groovy (https://doctoolchain.github.io/docToolchain/#_exportopenapi)

**Expected behavior**
Errors, related to current command are shown only.
Errors, not causing any mailfunction on the requested action are not shown.

**Comment by rdmueller** [comment]
thanx!
