### ISSUE TITLE
Travis CI changes in pricing plans

### ISSUE THREAD

**Issue by ahus1** [docToolchain/docToolchain#495]
This project uses Travis CI. On November 2nd they [announced their new pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). 

This boils down to that all open source projects:
* EITHER need to move over to travis-ci.com and apply for free build minutes or pay for their build minutes
* OR they need to find some other place (maybe GitHub actions)

Please share your thoughts - what do you suggest?

**Comment by rdmueller** [comment]
thanx for opening up this issue. I wasn't aware of this. I just applied for the beta. let's see how this works out.

**Comment by rdmueller** [comment]
I just migrated docToolchain to travis-ci.com and triggered the first build. Seems to work.
If I understand the pricing plan the right way, we have aprox >100 builds per month for free. let's see how this works out.
i'll close this for now.
