### ISSUE TITLE
Add properties for htmlSanityCheck

### ISSUE THREAD

**Issue by bjsee** [docToolchain/docToolchain#507]
**Is your feature request related to a problem? Please describe.**
I would like to use the htmlSanityCheck task to validate our documentation. Now we have a few links in the doc which for example require authentication so htmlSanityCheck would mark this links as broken. 
htmlSanityCheck allows to configure which statuscodes shall be interpreted as warning, error or success but this configuration can not be done through Config.groovy of docToolchain as far as I see.
Also it would be great if the junit-xml output of htmlSanityCheck can be activated and the failOnErrors flag could be set to true so that we could assure that only valid documentation is exported through cib.

**Describe the solution you'd like**
Create additional properties in Config.groovy and delegate them to htmlSanityCheck.

**Describe alternatives you've considered**
I see no alternatives but I am new to this project... maybe there is one?

**Comment by rdmueller** [comment]
thanx for the contribution - I guess we can close this issue now. Please re-open if I was wrong.
