### ISSUE TITLE
GenerateAsciidoc (required for GitHub readme and Wiki files)

### ISSUE THREAD

**Issue by aisbergde** [docToolchain/docToolchain#515]
**Is your feature request related to a problem? Please describe.**
Currently, GitHub (and GitLab) offer limited support for AsciiDoc previews (READMEs and other repo documentation), and they ignore any `include::` directive

**Describe the solution you'd like**
Add native support for AsciiDoc output (i.e. AsciiDoc 2 AsciiDoc) to allow creation of preprocessed ADoc source files.
I suggest some `GenerateAsciidoc` similar to `GenerateHTML` and `GeneratePDF`

**Describe alternatives you've considered**
Here is a feature request for asciidoctor related to the same issue:
https://github.com/asciidoctor/asciidoctor/issues/3312
And there was posted a possible solution:
https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb

But I am not a Ruby programmer and I don't plane to become a Ruby programmer.
I think it is a good idea to include this feature into docToolchain (maybe via AsciiDoctor if this would be included there) to give users an easy way to generate GitHub readme and Wiki files. 

**Additional context**
It was very easy to setup and to use docToolchain and it is very easy to generate documentations using this tool. I was very impressed how this worked out of the box. It would be great if the GitHub limitations could be solved also this easy way.

In this case, not only readme files could be generated, but also Wiki files.
"Publish to Confluence" is included into docToolchain, but in case it is a GitHub project then GitHub Wiki would be the best place for a Wiki which reqires asciidoc files without `include::`

**Comment by rdmueller** [comment]
thanx for the feedback and the kind words.

your idea is interesting.
AFIK, GitLab already supports the `include::` directive - at least the instance I work with :-) It also supports plantuml through a plantuml or kroki server.

But there is also a drawback - you don't see the structure of your documents anymore.
That's the reason why I personally prefere microsites like this one: https://github.com/docToolchain/arc42-template-project .

...but back to your idea: as I do undestand it, it would be nice to be able to (for instance) use includes in a readme to reference parts of the manual. A command like `generateAsciiDoc` or maybe `refreshGitIncludes` that resolves these includes.
I guess these includes would have to be different from the normal ones in order to be refreshable...
A `README.adoc` like this

```
this is just a demo

include::manual/about.adoc[]

further text
```

could be replaced with

```
this is just a demo

//start-include::manual/about.adoc[]
[content of manual/about.adoc]
//end-include::manual/about.adoc[]
further text
```

what do you think?

**Comment by aisbergde** [comment]
@rdmueller 
> I do undestand it, it would be nice to be able to (for instance) use includes in a readme to reference parts of the manual. A command like generateAsciiDoc or maybe refreshGitIncludes that resolves these includes.

yes

Your idea, to replace the `include::manual/about.adoc[]` by the content of the included file would be a solution: In case if the "manual/about.adoc" doesn't contain any other includes. 

----

the result site of the **microsite** you describe here https://github.com/docToolchain/arc42-template-project looks good. This would be good to use as a project site for some GitHub projects (for example).

I will try to understand the way from
> use ./gradlew bake to build the site and ./gradlew bakePreview to start a little webserver.
to the ready site
https://arc42-demo.netlify.app/index.html

Maybe you could add some words about the way from the build to the target server in the readme of this project. Maybe it is very easy.

I installed Gradle only to be able to use docToolchain. I even did not know about it before (working in BI, with DWH, MSSQL and so on). And if there are easy ways, to combine the docToolchain results with some microsites, this would be great.
Maybe you could add some of these ideas at the end of https://doctoolchain.github.io/docToolchain

It is related to docToolchain, I see this as a possible optional extension to the "chain". And it is even a project in the organization docToolchain. But if you would not mention it here I even would not find it. Because there are many repositories under docToolchain, and it is not pinned and in the list it is without a description:
![image](https://user-images.githubusercontent.com/9020187/104563811-6eb73080-564a-11eb-83c3-8905813aae16.png)

I found one of your (?) blog post where netlify is used together with Jekyll to be able to use asciidoc (which is not supported by GitHub pages). And reading this I found, it is possible, but my markdown based Jekyll site using GitHub pages is fine for now. There was an extra build server used, and I found this too complicated and oversized for my own website. Maybe this microsite is even easier than Jekyll.

**Comment by aisbergde** [comment]
I see, the usage of https://github.com/docToolchain/arc42-template-project is very easy
I just need to build, and then I could deploy the whole site to any provider.

Maybe I should investigate this mystic Gradle, which creates these out-of-the-box solutions :-)

**Comment by rdmueller** [comment]
> Maybe I should investigate this mystic Gradle, which creates these out-of-the-box solutions :-)

In case of the arc42 microsite, Gradle is only used to execute the jBake plugin. But if you use other build tools, then take a look at https://bake.org/docs/ - there are plugins for many build tools and even a CLI tool.

**Comment by rdmueller** [comment]
> It is related to docToolchain, I see this as a possible optional extension to the "chain".

I am already preparing a docToolchain version with jBake under the hood. My next talk @ FOSDEM might be interesting for you:
https://fosdem.org/2021/schedule/event/ttddoctoolchain/

The AsciiDoc Support for Jekyll is not as good as it could be. That's why I switched to jBake.

Regarding github - you could build the microsite locally (or with travis) and push it to a github-pages branch. That's how we did it for docToolchain in the past. This makes oyu independent from the features available on github.

**Comment by aisbergde** [comment]
@rdmueller 
Thank you. I marked the event in my calendar.

> Regarding github - you could build the microsite locally (or with travis) and push it to a github-pages branch. That's how we did it for docToolchain in the past. This makes oyu independent from the features available on github.

Very good idea. And it should be easy to handle.

For now, I will investigate, what would be better:
- to keep source code and documentation (and the relevant parts from "arc42-template-project") in one project  
   it would be easy to include parts of code into the documentation and I think this should be a pragmatic solution I could use in every project in the future.
- to separate documentation and code in different projects  
   this is what I see at docToolchain

**Comment by mh182** [comment]
Can we close this issue?

**Comment by aisbergde** [comment]
yes, we can close
