### ISSUE TITLE
initArc42RU not available in contradiction to what documentation states

### ISSUE THREAD

**Issue by joel-loewenstein** [docToolchain/docToolchain#535]
## Describe the bug
Cannot use the initArc42RU statement as proposed in [2.2.2 arc42 from scratch](https://doctoolchain.github.io/docToolchain/#_arc42_from_scratch)

>You can also do that by running the initArc42<language> task. Currently supported languages are:
>DE - German
>EN - English
>ES - Spanish
>RU - Russian

## To Reproduce
1. Follow installation according to docs [2.1 get the tool](https://doctoolchain.github.io/docToolchain/#_get_the_tool), Linux with git clone method
2. Init according to [2.2.2 arc42 from scratch](https://doctoolchain.github.io/docToolchain/#_arc42_from_scratch):
    
    `./gradlew -b init.gradle initArc42RU -PnewDocDir=../CleanArc42RU`

3. Error message: 
    ```
    ./gradlew -b init.gradle initArc42RU -PnewDocDir=../CleanArc42RU
    Starting a Gradle Daemon (subsequent builds will be faster)
    > Configure project :
    compiling with Java 1.8.0_181 at 11:18:59

    FAILURE: Build failed with an exception.

    What went wrong:
    Task 'initArc42RU' not found in root project 'docToolchain'. 
    Some candidates are: 'initArc42DE', 'initArc42EN', 'initArc42ES'.
    ```

## Expected behavior
Initialize the folder with the russian template as indicated in the documentation.

## Screenshots
N/A

## Configuration
```
docToolchain . --version
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.15.7 x86_64
```
## Additional context
N/A

**Comment by rdmueller** [comment]
I've just added the task. can you please verify this fix?

**Comment by joel-loewenstein** [comment]
Hello, i checked the commit 0faae74 successfully manually. Is there any docToolchain command that could actually check wether the local vs the repo version got some updates? I know this would come with brew but brew likes reusing existing recepies. Please do not confuse my questions with lazyness, i just have to learn so much about how you build docToolchain and the used components... 

In terms of NG: is there some discussion forum or issue that you use to collect feedback on NG?

**Comment by rdmueller** [comment]
I just activated the discussion feature on this repository today. Let:s try and see if it is useful.

No, currently there is no feature which checks for updates but this might be a good idea!

**Comment by joel-loewenstein** [comment]
If you applied the fix to master, i think we can close this issue?

**Comment by joel-loewenstein** [comment]
Closing as dicussed, as i opened it and verified it.
