### ISSUE TITLE
Conditional HTML content processed with generatePDF task from arc42 template

### ISSUE THREAD

**Issue by joel-loewenstein** [docToolchain/docToolchain#536]
## Describe the bug

After clean install and init of Arc42EN i use generatePDF task and find the following undesired content is rendered into the PDF(see also Screenshot below):

```
<style>
.arc42help {font-size:small; width: 14px; height: 16px; overflow: hidden; position: absolute; right: 0px; padding: 2px 0px 3px 2px;}
.arc42help::before {content: "?";}
.arc42help:hover {width:auto; height: auto; z-index: 100; padding: 10px;}
.arc42help:hover::before {content: "";}
@media print {
	.arc42help {display:hidden;}
}
</style>
```

As i understand the documentation for [AsciiDoc / Conditionals / ifdef and ifndef Directives](https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/#ifdef), the following codeblock from arc42-template.adoc shall only be processed when the backend is HTML, but somehow gets processed into the PDF content:

```
//additional style for arc42 help callouts
ifdef::basebackend-html[]
++++
<style>
.arc42help {font-size:small; width: 14px; height: 16px; overflow: hidden; position: absolute; right: 0px; padding: 2px 0px 3px 2px;}
.arc42help::before {content: "?";}
.arc42help:hover {width:auto; height: auto; z-index: 100; padding: 10px;}
.arc42help:hover::before {content: "";}
@media print {
	.arc42help {display:hidden;}
}
</style>
++++
endif::basebackend-html[]
```

## To Reproduce
1. Follow installation according to docs [2.1 get the tool](https://doctoolchain.github.io/docToolchain/#_get_the_tool), Linux with git clone method
2. Init according to [2.2.2 arc42 from scratch](https://doctoolchain.github.io/docToolchain/#_arc42_from_scratch):
    
    `./gradlew -b init.gradle initArc42EN -PnewDocDir=../CleanArc42EN`

3. Create according to [2.3 Build](https://doctoolchain.github.io/docToolchain/#_build):
    
    ```
    cd ../CleanArc42EN
    docToolchain . generatePDF
    .
    .
    BUILD SUCCESSFUL in 15s
    1 actionable task: 1 executed
    ```
4. Open the created outputfile arc42-templet.pdf within a reader to your liking, find the undesired content described in the screenshot just after the table of contents.

## Expected behavior
The mentioned content shall not be rendered into the PDF by the processor but respect the condition properly only to be executed when  HTML is processed: 

```
<style>
.arc42help {font-size:small; width: 14px; height: 16px; overflow: hidden; position: absolute; right: 0px; padding: 2px 0px 3px 2px;}
.arc42help::before {content: "?";}
.arc42help:hover {width:auto; height: auto; z-index: 100; padding: 10px;}
.arc42help:hover::before {content: "";}
@media print {
	.arc42help {display:hidden;}
}
</style>
```

## Screenshots
![image](https://user-images.githubusercontent.com/4130973/108624706-d67d4a00-7446-11eb-9935-adb4072d40ae.png)

## Configuration
```
docToolchain . --version
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.15.7 x86_64
```
## Additional context
N/A

**Comment by rdmueller** [comment]
there is already a fix for this in the arc42 template project. The pdf outbut also uses the html backend - that is the problem with this conditional code

**Comment by joel-loewenstein** [comment]
Ah, i looked into this repo and the asciidoctor repo for corresponding issues. Murphys law... 
Do you have by any chance the issue number at hand in the arc42 repo?
Thanks in advance.
BTW: i had planned to attend your FOSDEM Slot, but a customer issue came along,... watched the recording happily.. great idea with the overall wrapper... i had a similar though but would have startet from homebrew...

**Comment by rdmueller** [comment]
Homebrew is a nice tool and maybe we can add a homebrew version. With all the experience I now collected from different teams, my goal is to make the wrapper as independent as possible from other tools. Even including Java.

**Comment by rdmueller** [comment]
so, the PR to fix this can be found here: https://github.com/arc42/arc42-template/pull/133
I think I'll have to run the generator in order to make it available.
In another instance, I fixed ith with the `filetype` attribute and checked if it is `html`

**Comment by joel-loewenstein** [comment]
Thank you, started to looking into it, i made the mistake to only looking at open issues in asciidoctor-pdf repo... Beginners mistake...

**Comment by rdmueller** [comment]
the templates are re-generated. You should now be able to download the fixed ones

**Comment by rdmueller** [comment]
Discussions - I think, it is ok to discuss things like that here as issue. But I will also activate discussions just now...: https://github.com/docToolchain/docToolchain/discussions

let's move this discussion to there...

**Comment by rdmueller** [comment]
please verify the solution and update this issue accordingly :-) Thanx!

**Comment by joel-loewenstein** [comment]
Hello, as i checked for #535 if the task is now available to install Arc42RU i used the fresh init of Arc42RU, EN, ES and DE to verify that the updated zips including help of the forementioned languages are error free in the regards to mentioned style section. I did only verify the DE plain version, which was also rendering without the style section as desired.

**Comment by joel-loewenstein** [comment]
As this seems fixed now i would close the issue, if you do not have anything to add?

**Comment by rdmueller** [comment]
I live by the rule that an issue should be closed by the one who opened it 😀

**Comment by joel-loewenstein** [comment]
As i opened it and verified the changed template contents with master and ng, close hereby this issue...
