### ISSUE TITLE
dtcw: improve (on mac) - ng used for testing

### ISSUE THREAD

**Issue by joel-loewenstein** [docToolchain/docToolchain#543]
## Is your feature request related to a problem? Please describe.
I downloaded dtcw into the /Downloads folder on mac, executed from there. Not sure if the path topics below could be avoided, if the wrapper would be put somewhere else?

1. The current beta docToolchain wrapper (dtcw) installable via doctoolchain.github.io/dtcw is using wget to download artifacts. Wget is not available as a standard tool on mac. 
```
./dtcw local
dtcw - docToolchain wrapper V0.11
force use of local install
docToolchain not installed.
doctoolchain not found
Do you wish to install doctoolchain to /Users/myuser/.doctoolchain?
1) Yes
2) No
#? 1
installing doctoolchain
./dtcw: line 120: wget: command not found
unzip:  cannot find or open /Users/myuser/.doctoolchain/source.zip, /Users/myuser/.doctoolchain/source.zip.zip or 
/Users/myuser/.doctoolchain/source.zip.ZIP.
bash: /Users/myuser/.doctoolchain/docToolchain-ng/bin/doctoolchain: No such file or directory
```
   To work around it, i did a brew install wget, to continue the tests.

2. The second line seems kind of duplicate? I cannot quite make out the intention behind it.
````
docToolchain not installed.
doctoolchain not found
````

3. If docker is chosen, but not available i would expect the script to stop when docker is not found, but it seems it does a local install instead, which has some errors:
[dtcw docker after brew wget.pdf](https://github.com/docToolchain/docToolchain/files/6032109/dtcw.docker.after.brew.wget.pdf)

**UPDATE:** In a second run the question for y/n did not occur as in the pdf, but a similar error:
```
* What went wrong:
Execution failed for task ':exportChangeLog'.
> java.io.IOException: Cannot run program "git" (in directory "/Users/jlo2k/Downloads/src/docs"): error=2, No such file or directory
```

4. After that i tried sdkman (without cleaning the previous) and got this, but expected as found somewhere in the code how to install sdkman instead of running into the gradle task:
```
./dtcw sdkman
dtcw - docToolchain wrapper V0.11
home folder exists
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
FAILURE: Build failed with an exception.
* What went wrong:
Task 'sdkman' not found in root project 'docToolchain'.
* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 6s
```

Then i realized i should have used sdk not sdkman ... but works as expected, i might not be the only one who will do this mistake, maybe better catch it... but also cleaned all docToolchain folder before this run... so it might acually be an inconsistent result.

```
./dtcw sdk   
dtcw - docToolchain wrapper V0.11
force use of sdkman
docToolchain not installed.
please use sdkman to install docToolchain
$ sdk install doctoolchain ng-beta
```

5. Why is ng Gradle 6.6.1 instead of current master 6.7.1?

6. Finally i tried local install, but got a similar error like the previous installs with docker:
```
> Task :exportChangeLog FAILED
FAILURE: Build failed with an exception.
* Where:
Script '/Users/jlo2k/.doctoolchain/docToolchain-ng/scripts/exportChangelog.gradle' line: 15
* What went wrong:
Execution failed for task ':exportChangeLog'.
> java.io.IOException: Cannot run program "git" (in directory "/Users/myuser/Downloads/src/docs"): error=2, No such file or directory
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 57s
1 actionable task: 1 executed
```
7. Hoping that the other installation tasks succeeded i tried to download the DE template:
```
./dtcw downloadTemplate
dtcw - docToolchain wrapper V0.11
home folder exists
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :downloadTemplate
Install arc42 documentation template.
For more information about arc42 see https://arc42.org
[ant:input] Which language do you want to install? (EN, DE, ES, RU)
<-<-------------> 0% EXECUTING [15s]
[ant:input] Do you want the template with or without help? (withhelp, plain)
<--<-<-------------> 0% EXECUTING [25s]
Download https://github.com/arc42/arc42-template/raw/master/dist/arc42-template-DE-plain-asciidoc.zip
arc42 template unpacked into /Users/myuser/Downloads/src/docs/arc42
added template to docToolchainConfig.groovy
use 'generateHTML' or 'generatePDF' to convert the template

BUILD SUCCESSFUL in 28s
```
8. Then i tried to create a pdf:
```
./dtcw generatePDF
dtcw - docToolchain wrapper V0.11
home folder exists
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
arc42/arc42.adoc

> Task :generatePDF
Converting /Users/myuser/Downloads/src/docs/arc42/arc42.adoc
could not locate or load the pdf theme `custom in /Users/myuser/Downloads/pdfTheme; reverting to default theme

BUILD SUCCESSFUL in 32s
1 actionable task: 1 executed
```
I found that there really was not PDFTheme folder, so i copied it from the template folder and ran again:
```
./dtcw generatePDF
dtcw - docToolchain wrapper V0.11
home folder exists
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
arc42/arc42.adoc

> Task :generatePDF
Converting /Users/myuser/Downloads/src/docs/arc42/arc42.adoc

BUILD SUCCESSFUL in 19s
1 actionable task: 1 executed
```
The theme was still not applied, so i deleted the file and ran again. This time the pdf was created using the theme. As the doctoolchain_demo.adoc was not there i think a task misses the copy of the template folder. But when using the arc42 template, to have that demo file there is acutally distracting and confusing.

## Describe the solution you'd like
For 1.  verify if curl can be used for all intended platforms, e.g. sdkman and homebrew both do use it.
In general i presume the other errors are ng related, which eventually become fixed.

I wonder if a wrapper has some intelligence build in, if it would be worthwile to build in more automation:
Check what you find: local, docker, sdkman if only one is found leverage that instead of asking what to do. When a force of either is chosen, do not present text but acually ask if it should be installed first or maybe even go for it as it was already chosen. 

If the wrapper is incidentaly started in /Downloads /Documents /User (other typical non project folders) maybe ask wether it is really intended to run here.

## Describe alternatives you've considered
For 1. There is an alternative to create a mac specific workaround: an alias redirecting wget on mac to curl. See [Stackoverflow - OS X: equivalent of Linux's wget](https://stackoverflow.com/questions/4572153/os-x-equivalent-of-linuxs-wget)

## Additional context
N/A

**Comment by rdmueller** [comment]
1) i've updated the wrapper. It now check for wget, curl and unzip. If wget is not available, it uses curl. If both are not available or unzip is missing, it will fail with a message

**Comment by rdmueller** [comment]
2) duplicate message: second line has been updated to "sdkman not found". We'll also have to move these message to debug output in a later version

**Comment by rdmueller** [comment]
5) if fixed this but still have to push it

**Comment by rdmueller** [comment]
regarding most of the remaining issues:

- the path you started dtcw in should not be a problem. But dtcw assumes that this is your project folder
- I think most of the ´problems occured because I didn't think about what to do when dtcw is executed without a command, only with a "forced" way to use a specific install:
  - the first argument (local, docker, sdk) is mainly used for debug reasons. It forces the wrapper to use the specified type of install
  - if this argument is not given, the wrapper tries to find a good way to run doctoolchain:
    - if docker is available, use docker
    - if a local install is already available, use it
    - if sdkman is available, ask the user to install docToolchain via sdkman
    - as the user if the wrapper should download and install docToolchain
  - something went wrong with you `dtcw docker` command - I will check this

btw: to reset everything for the next test, you have to remove the `.doctoolchain` folder in your home directory.

**Comment by rdmueller** [comment]
just retested on M1-Chip hardware and noticed that macOS has a java-shim installed :-(

**Comment by rdmueller** [comment]
updated the wrapper to detect missing java on macOS

**Comment by joel-loewenstein** [comment]
Sh... i forgot, i already thought about it, but forgot to write it down in this issue. Good you catched that...

**Comment by joel-loewenstein** [comment]
does skdman propose to install java when docToolchain is demanded to be installed? i read some people dislike about it that it fiddles itself into the shell and is hard to remove... as a mac user i tend to brew, but that misses of course some of the sdk relevant specialities of sdkman

**Comment by rdmueller** [comment]
as a java dev, I prefere sdkman to install java. It also easily let's you switch versions. But the way java gets installed doesn't matter for docToolchain. Maybe we should emphasis in the outputted help statements.

**Comment by rdmueller** [comment]
I thought about to modify the gradle-wrapper which ships with docToolchain to install java if it is not installed. But I guess I will not find the time for doing so soon.

**Comment by rdmueller** [comment]
ha! just found this old issue and noticed that there is now a `getJava` task which installes the right JDK. And docToolchain will tell you to use it if it runs into problems.

**Comment by rdmueller** [comment]
@joel-loewenstein can we close this issue? Or is there something still missing?

**Comment by mh182** [comment]
I would like to keep this open until we integrate the test suite in an macOS environment.
