### ISSUE TITLE
downloadTemplate: Failed to load AsciiDoc document - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#549]

**Comment by rdmueller** [comment]
converted .asciidoctorconfig.adoc from 'WINDOWS-1252' to 'UFT-8'
  converted arc42.adoc from 'WINDOWS-1252' to 'UFT-8'
  converted .asciidoctorconfig.adoc from 'WINDOWS-1252' to 'UFT-8'
  converted config.adoc from 'WINDOWS-1252' to 'UFT-8'

**Comment by mh182** [comment]
Can we close this?

**Comment by rdmueller** [comment]
yes
