### ISSUE TITLE
relying on title in Confluence is dangerous

### ISSUE THREAD

**Issue by bodewig** [docToolchain/docToolchain#57]
We just had a case where exporting one document "stole" a page from a different document because they happened to share the same title. We now made using `confluencePagePrefix` mandatory for us. The real problem is, we only noticed the problem by chance.

When the `parentId` is set `pushToConfluence` could verify the ancestor of the page it finds for a given title matches the `parentId` and either reject the exporting the page or at least print a warning.

**Comment by rdmueller** [comment]
that's true and that's what the `pagePrefix`was introduced for (have to write more docs).
Another problem is when you rename a title. If you not only change the case, then you just create a new page, but when you just change the case, it runs into an error...

For larger projects, this is a real pain.

**Comment by aheusingfeld** [comment]
IMPOV this is very much related to #15! It all boils down to 
a) how we identify a mapping page in Confluence (maybe store the pageIds somewhere?) and
b) what was the user's intention: when the user changed the source document in that they switched the order of two sections (including their headings) or they changed the title, should we delete the previous Confluence pages and create new ones or should we update the identified pages? Both might break the page history and deleting pages will create a lot of noise.

I don't currently see a simple solution

**Comment by rdmueller** [comment]
I guess you are right. this is not easy to solve, but we should give it a try since it is really annoying...
#15 is related but IMHO easier to fix...
