### ISSUE TITLE
Markdown with pandoc as replacement for asciidoc

### ISSUE THREAD

**Issue by gabyx** [docToolchain/docToolchain#573]
Targeting Confluence, would it be possible to have the same tool chain, but targeting "markdown" instead of asciidoc.
Basically a huge enhancemend ;-).
The generated HTML5 from Asciidoctor: is that a sepcial format Confluence understands? or can any HTML5 be uploaded to a Confluence page?

**Comment by rdmueller** [comment]
Confluence uses an xhtml dialect as internal storage format which is quite close to standard html.
So, with docToolchain, we first convert AsciiDoc to HTML, split the HTML by heading, convert some features and send the result to confluence.

For your idea, I see two options:

- convert markdown to html and feed it to https://github.com/docToolchain/docToolchain/blob/master/scripts/publishToConfluence.gradle
- convert markdown to asciidoc (I guess via pandoc) and feed it to `publishToConfluence.gradle`

If one of those approaches yields good results, I would copy the `publishToConfluence` task and modify it further to fit the markdown needs.

**Comment by rdmueller** [comment]
btw: since I don't see a reason to use markdown instead of asciidoc, I will not create code for this feature.
However, I am ready to support you with my knowledge to reach your goal

**Comment by gabyx** [comment]
Thats cool, I was just thinking about supporting markdown ( pandoc style) because its easier to read, with some filters an stuff it might be easily compatible with your asciidoc setup, do you have special features in asciidoc that you use to support jira links and other stuff? or is it kind of post processing or asciidoctor plugin stuff?

Von meinem iPhone gesendet

**Comment by mh182** [comment]
The core idea of docToolchains is to provide a tool chain to create technical documentation based on Asciidoc. 

There is a reason why both formats exists (see [Compare AsciiDoc to Markdown](https://docs.asciidoctor.org/asciidoc/latest/asciidoc-vs-markdown/).

We close this issue since we focus on Asciidoc as source format.

If you come up with a PR which would nicely integrate in the existing solution, we can discuss it again.
