### ISSUE TITLE
Get a OK/NOK and a summary of broken links for htmlSanityCheck

### ISSUE THREAD

**Issue by Rosi2143** [docToolchain/docToolchain#586]
**Is your feature request related to a problem? Please describe.**
When I run the task [htmlSanityCheck](https://doctoolchain.github.io/docToolchain/#_htmlsanitycheck) I only get a "thanx for using HtmlSanityChecker."

For bigger problems this is hard to read and even harder to "interpret" on a Jenkins for a commit checker if the SanityCheck passed or failed.

**Describe the solution you'd like**
I would like to get an easy to read and interpret summary of the check that I can use in a script - on Jenkins.

I want to get two information

- returnCode: OK/NOK
- if NOK
  1. how many errors have been found 
  2. with what error code (400/401/...) / image missing
  3. how many files have an error

Additionally - as a premium AddOn - I would like to have an optional filter for the errors that are reported.
e.g. 
- only consider 404 as this points to a really wrong link.
- ignore 403 as this points "only" to a missing password.

Also for users that did not read the documentation a reference to the file `build/report/htmlchecks/index.html` would be great.
I really like this page - for manual checks - but people not familiar with the task will not find it.

**Describe alternatives you've considered**
I've added currently a parser of build/report/htmlchecks/index.html to do a post-evaluatation of the results.

**Additional context**
For bigger project ( I have 40+ files) we have set up a Jenkins and our intention is to add this [htmlSanityCheck](https://doctoolchain.github.io/docToolchain/#_htmlsanitycheck) to our review and do not allow a commit when a link is broken. But we have lots of password protected sites. Users have generally access, but the Jenkins user - as a group user - is not allowed access to these sites.

**Comment by rdmueller** [comment]
docToolchain uses https://github.com/aim42/htmlSanityCheck to check the broken links. I think this issue is more related to htmlSanityCheck than docToolchain, so I will move the issue.

**Comment by Rosi2143** [comment]
Sure - thanks for pointing me to the real sources.

**Comment by Rosi2143** [comment]
Checked more detailed documentation at https://github.com/aim42/htmlSanityCheck  and found the problem is already solved.

Remaining problem already got reported [exclude certain URLs from checking](https://github.com/aim42/htmlSanityCheck/issues/276)

**Comment by rdmueller** [comment]
so, do we have to update the htmlSanityCheck version used by docToolchain?

And do we have to update the docs to link to the htmlSanityCheck docs?

**Comment by Rosi2143** [comment]
Linking the documentation more prominently seems to be a good idea. I'll give it a try.
I don't see any relevant change between 1.1.4 and 1.1.5. But I can't see where version 1.1.3 was taken from :-(.
