### ISSUE TITLE
uploadToConfluence attachement handling

### ISSUE THREAD

**Issue by Hellmy** [docToolchain/docToolchain#613]
**Is your feature request related to a problem? Please describe.**
The attachment detection is currently done by prefix the href src-Property. If you try to place the attachment files in folders near the asciidoc the attachment will not always start with "attachments"

**Describe the solution you'd like**
Wouldn't also a option with a contain-check be possible - as the path just has to contain attachments or something else and therefore the folder structure itself must not be fixed to start everywhere with the same.

**Describe alternatives you've considered**
I could also change the attachmenet folder to "./" but I'm concerned for possible collisions with other href-elements.

**Additional context**
I try to have multipe folders and I want to publish the base.adoc to confluence. "some_attachment.xml" is used in "folder_1.adoc"
```
- base.adoc
-- folder_1
--- folder_1.adoc
--- attachments
---- some_attachment.xml
```

**Comment by rdmueller** [comment]
hm. can you point me to the line of the source you are refering to?
https://github.com/docToolchain/docToolchain/blob/master/scripts/asciidoc2confluence.groovy

**Comment by Hellmy** [comment]
https://github.com/docToolchain/docToolchain/blob/2fe3c6fb2d3230385070b830a5f91cc292436096/scripts/asciidoc2confluence.groovy#L539
there is the prefix check and if the prefix is matched then an upload is done. I currently work with the the config `attachmentPrefix = "./"` but it feels like a hack...

**Comment by rdmueller** [comment]
ah, I see. This is a feature I never used myself.
As I do understand, this feature is for attachments besides the formal images. 
For instance, when I also want to upload a zip-file or pdf.

Can you propose a code change?

**Comment by Hellmy** [comment]
I will think about it - will just take a bit time.

**Comment by rdmueller** [comment]
If you want to, we could implement it as pair programming... just suggest a time and date. ralf.d.mueller@gmail.com

**Comment by Hellmy** [comment]
current documentation enhancement is fine - thank you!
