### ISSUE TITLE
dtcw - sdkman installation check returns wrong result

### ISSUE THREAD

**Issue by uniqueck** [docToolchain/docToolchain#621]
**Describe the bug**
sdkman is installed

**To Reproduce**
I tested this on ubuntu, so here command sdk returns command not found.

**Expected behavior**
sdkman should detected as installed.

**Configuration**
 - OS: Ubuntu 20.10 with zsh

**Additional context**
none

**Comment by uniqueck** [comment]
A check with where sdk returns 0 for existence and 1 for unavailable. I create a pull request for that additional check.

**Comment by rdmueller** [comment]
do you have a link pointing to the PR?

**Comment by uniqueck** [comment]
Later this evening I create this fix and create a pr

**Comment by uniqueck** [comment]
Where can I find the repository for the dtcw?

**Comment by rdmueller** [comment]
to make it easy downloadable, dtcw is located in https://github.com/docToolchain/docToolchain.github.io
this results in doctoolchain.github.io/dtcw as download-url

**Comment by uniqueck** [comment]
Ok I'm confused. 

If i try something like [[ "$(command -v sdk)" ]] in my terminal all is fine, but in the dtcw it is not working.
I have to investigate more time, to understand why my sdk command is not found.
If I open a bash shell and type sdk, it also work as expected.

**Comment by rdmueller** [comment]
Could it be that you've installed sdkman within zshell but not bash?

**Comment by uniqueck** [comment]
Yes indeed that is the case.

Ralf D. Müller ***@***.***> schrieb am Di., 7. Sept. 2021,
07:07:

**Comment by rdmueller** [comment]
how do we progress with this issue?

**Comment by uniqueck** [comment]
For me that is ok, but i think we have to investigate to find a solution that it is working no matter which shell is used.

**Comment by rdmueller** [comment]
This seems to be a general issue.
the script uses bash and when I start it from another shell, it might be that in the starting shell, a tool like sdkman or java is installed but not configured for bash.
Don't know if there is a solution for this...
