### ISSUE TITLE
Confluence new editor show hash at the end of the pages

### ISSUE THREAD

**Issue by sabatmonk** [docToolchain/docToolchain#627]
The new confluence editor strip display none and this makes the pages hash visible

I'm working on a workaround, where the hash will be white in the new editor so it will be "hidden" in the background

**Comment by rdmueller** [comment]
Great. Another solution could be to store the hash in the meta data. But then we would have to take care of compability

**Comment by PacoVK** [comment]
This has been fixed in 3.x. Hence we can close it
