### ISSUE TITLE
generateHTML copies images to wrong directory

### ISSUE THREAD

**Issue by nbyl** [docToolchain/docToolchain#648]
**Describe the bug**
When setting up an initial project with arc42, the HTML generator copies the images into a wrong target directory. This breaks the image loading in the resulting HTML page and the publishing to confluence.

**To Reproduce**
1. `curl -Lo dtcw doctoolchain.github.io/dtcw
chmod +x dtcw`
2. `./dtcw downloadTemplate`
3. Answer with `EN` for language and `plain` for template type.
4. `./dtcw generateHTML`

The resulting directory layout of `build` is:
```
build
build/html5
build/html5/arc42
build/html5/arc42/arc42.html
build/html5/output
build/html5/output/images
build/html5/output/images/arc42-logo.png
```

**Expected behavior**
The images directory should be directly inside `build/html5`. That is at least what the link inside the generated HTML points to.

**Configuration**
 - OS: MacOS
 - Relevant SDK Versions JDK 11

**Comment by nbyl** [comment]
From triaging the code, i found #632 fixed this already. Is there a new release on the roadmap which would fix this?

**Comment by rdmueller** [comment]
thanx for reporting this issue. Yes, #632 fixes this problem and I plan to release it today or tomorrow as 2.0.1

if you need it sooner, you can clone the repository to your $home/.doctoolchain/... folder

**Comment by rdmueller** [comment]
new version 2.0.1 has been released. Docker image is currently uploading

**Comment by rdmueller** [comment]
docker image is now also available.

You need to change the version used in your `dtcw` file to 2.0.1 in order to use it.

please re-open this issue if you still encounter problems
