### ISSUE TITLE
init-task

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#650]
we need an init-Task for the sdk-man install which copies all three wrapper and a config to the corrent folder.

**Comment by mh182** [comment]
I think we can close this issue.

**Comment by rdmueller** [comment]
Yes, let's close this.
But we should consider another init task - one which installs a CI/CD pipeline 😁

**Comment by mh182** [comment]
I do not understand what functionality you want to implement.

**Comment by rdmueller** [comment]
- Let dtcw check if it is running on a github or gitla. Repository
- add a github action or gitlab pipeline to deploy the mircosite to a github or gitlab page

**Comment by rdmueller** [comment]
Just an idea. Maybe it should be called something else
