### ISSUE TITLE
Upgrade to Gradle (wrapper) 7.5

### ISSUE THREAD

**Issue by ascheman** [docToolchain/docToolchain#662]
Gradle is only compatible to latest LTS JDK (17) with version 7.x. Therefore I suggest to upgrade to Gradle (wrapper) version 7.2.

**Comment by rdmueller** [comment]
@ascheman do you remember why we didn't merge your changes?

**Comment by rdmueller** [comment]
got it: the current asciidoc plugin is not compatible with Gradle 7.x .

**Comment by mh182** [comment]
We could upgrade to Gradle 8 after integration of #1098.

**Comment by PacoVK** [comment]
after #1098  still suffering from incompatibility. We cannot go further than 7.0.2 currently. see #1104

**Comment by mh182** [comment]
Changed the title to reflect the know how we researched with #1104 .

**Comment by mh182** [comment]
With PR #1108 we can upgrade to Gradle 7.5 which supports Java 17.

**Comment by mh182** [comment]
Upgraded to Gradle 7.5.1.
