### ISSUE TITLE
bug: publishToConfluence with unknown source language

### ISSUE THREAD

**Issue by aklemp** [docToolchain/docToolchain#683]
**Describe the bug**
AsciiDoc supports several code languages for highlighting, for example `Terraform`. Publishing such pages to Confluence displays an error.

**To Reproduce**
1. Create an AsciiDoc file containing a code snippet
```
[source,Terraform]
----
module "foo" {
  source = "bar"
}
----
```
2. Publish the page to Confluence.
3. The snippet is rendered but it contains an error message as well: "Error rendering macro 'code': Invalid value specified for parameter 'com.atlassian.confluence.ext.code.render.InvalidValueException'"

**Expected behavior**
If a language is not supported by Confluence, the language `text` should be set or left out completely to avoid the error message.

**Comment by rdmueller** [comment]
good point. Where can we find a list of supported languages?

ah! I guess here is the list: https://confluence.atlassian.com/doc/code-block-macro-139390.html

```
ActionScript
AppleScript
Bash
C#
C++
CSS
ColdFusion
Delphi
Diff
Erlang
Groovy
HTML and XML
Java
Java FX
JavaScript
PHP
Plain Text
PowerShell
Python
Ruby
SQL
Sass
Scala
Visual Basic
YAML
```

**Comment by aklemp** [comment]
Created a PR for this.

**Comment by PacoVK** [comment]
this issue is already solved, closing as complete :) thanks for contributing!
