### ISSUE TITLE
generateSite: navigation tree instead of navigation list on the left

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#692]
Given a structure like this:

```
src/docs/
├── ...
├── 30_tri
│   ├── 10_ipsum.adoc
│   └── 20_advanced
│       ├── 10_topic-A.adoc
│       └── 20_topic-B.adoc
├── ...

```

`generateSite` seems to ignore the fact that some pages were put in a sub-folder.
In the navigation tree on the left, everything is flat:

<img width="769" alt="docToolchain output of the generateSite command" src="https://user-images.githubusercontent.com/1222165/141083180-f483bfb6-05a7-4cbe-9111-a801695d91a5.png">

**Describe the solution you'd like**
I would like to see a tree of pages (instead of a list) where folders of the source files are considered.

Concretely in this example, I would have expected `topic-A` and `topic-B` to be under an `advanced` node:

<img width="295" alt="Screenshot 2021-11-10 at 10 04 31" src="https://user-images.githubusercontent.com/1222165/141083309-086434f7-faf9-49fd-b14b-b98c90d2c83f.png">

**Comment by rdmueller** [comment]
Yes! I also would love to see this feature 😀 
We will have soon an open source Hackergarten. I think this would perfectly fit...

**Comment by jmini** [comment]
@rdmueller sorry to come back on this a long time after this was posted. 

Do you have any idea/pointer how this would start?

**Comment by rdmueller** [comment]
there are two ways we can solve this:

### quick and dirty

in some projects, I used to create such a navigation just as list of links:

```
* xref:first.adoc[1. first]
** xref:second.adoc[1.1 second]
* xref:third.adoc[2. third]
```

with the right template, you can replace the standard menu with this manually curated list.

### automated

This is where the meta-attribute `:jbake-menu:` is set:
https://github.com/docToolchain/docToolchain/blob/ng/scripts/generateSite.gradle#L246

...and this is where the `:jbake-title:` is set:
https://github.com/docToolchain/docToolchain/blob/ng/scripts/generateSite.gradle#L287

both together make up the menu: `:jbake-menu:` is the menu entry on top of the page, `:jbake-title:` is the name of the link to the left.

I think we need something more struktured here... if we would have maybe another meta-attribute like `:jbake-deepmenu:` which gets the folder structure assigned, we could use it in

https://github.com/docToolchain/docToolchain/blob/ng/src/site/groovy/menu.groovy

To build up an array which is then used in 
https://github.com/docToolchain/docToolchain/blob/ng/src/site/templates/submenu.gsp

to render the link list.

### Bonus

and it would be great if we could create a javaScript wich implements a collapsable menu and scroll-spy

Do these thought help for a start?

Should we meet for pair programming?

**Comment by jmini** [comment]
What is great is that docsy (the theme used by docToolchain) has good support for hierarchical navigation:
https://example.docsy.dev/docs/

**Comment by jmini** [comment]
This is how the menu array looks like in my example project:
https://github.com/jmini/dtc-experiments/

```
[
    unu: [
            [title:Intro, order: 10, filename: null, uri: 10_unu/10_intro.html],
            [title:Content, order: 20, filename: null, uri: 10_unu/20_content.html]
    ], 
    tri: [
            [title:Ipsum, order: 10, filename: null, uri: 30_tri/10_ipsum.html],
            [title:Topic A, order: 10, filename: null, uri: 30_tri/20_advanced/10_topic-A.html],
            [title:Topic B, order: 20, filename: null, uri: 30_tri/20_advanced/20_topic-B.html]
    ],
    du: [
            [title:Lorem, order: 10, filename: null, uri: 20_du/10_lorem.html],
            [title:AsciiDoc, order: 20, filename: null, uri: 20_du/20_asciidoc.html],
            [title:Asciidoctor Diagrams, order: 30, filename: null, uri: 20_du/30_diagrams.html],
            [title:Draw.io Example, order: 40, filename: null, uri: 20_du/40_drawio.html]
    ], 
    -: [
            [title:search, order: 0, filename: null, uri:search.html]
    ]
]
```

So instead of a list/array of pages, we should have a tree structure with "children". Not sure yet where is the best way to do this.

The fun part is that my tool [`html-publish-helper`](https://jmini.github.io/html-publish-helper/) has a similar feature when building the navigation tree for the "complete site" approach.

**Comment by jmini** [comment]
I have modified [`menu.groovy`](https://github.com/docToolchain/docToolchain/blob/ng/src/site/groovy/menu.groovy) and [`submenu.gsp`](https://github.com/docToolchain/docToolchain/blob/ng/src/site/templates/submenu.gsp) to support a navigation tree instead of a list on the left.

<img width="338" alt="Screenshot 2022-06-29 at 22 32 08" src="https://user-images.githubusercontent.com/1222165/176540052-b32bf4be-e1f1-40a2-9f5b-8447b79b7592.png">

This is based on the folder structure:

```
src/docs/
├── ...
├── 30_tri
│   ├── 10_ipsum.adoc
│   ├── 20_advanced
│   │   ├── 10_topic-A.adoc
│   │   └── 20_topic-B.adoc
│   └── 30_test
│       ├── 10_one.adoc
│       ├── 20_two.adoc
│       ├── 30_three.adoc
│       └── index.adoc
├── ...
```

When an index page is present (like `30_tri/30_test/index.adoc` in my example) then the node corresponds to this index page (you can click on it and the title is taken from the page).

When the index page is absent (like there is no `30_tri/20_advanced/index.adoc` in my example) then the name of the folder is used, and you can not click on the node.

The change can be seen here:
https://github.com/jmini/dtc-experiments/commit/67330f4e0abfc922dd78a9c41ae78f05ce5baffa

---

About the contribution to docToolchain:

Should it be configurable?
(to preserve the case where somebody had subfolders still wants a list of pages instead of a tree of pages)
If yes where should this config be located and what should be the default?

An other prerequisite for the contribution is to validate the test approach for `menu.groovy` in PR #864 (because my change adds more test cases).

**Comment by jcunliffe1** [comment]
Isn't rearranging it into a flat structure to allow for keeping the list a fairly trivial thing? I don't see the need to make such things configurable. @rdmueller  Can we get this merged soon? Will cherry pick for now. Well done @jmini and thank you. :)

**Comment by jmini** [comment]
@jcunliffe1 thank you very much for the feedback.

I have also started to use the modified `menu.groovy` and `submenu.gsp` changes in some of our projects. This is a good way to beta-test the feature.

When you try it, feel free to share your feedback here. Maybe there are cases that are not covered yet.

**Comment by rdmueller** [comment]
@jcunliffe1 , yes, let's merge this and maybe I can get a new deployment out until the end of next week.

**Comment by jcunliffe1** [comment]
I have copied in the code from https://github.com/jmini/dtc-experiments/commit/67330f4e0abfc922dd78a9c41ae78f05ce5baffa and have a problem with the prefix not getting respected for ordering:

![image](https://user-images.githubusercontent.com/97282647/177713856-8d709e54-3181-45ea-9d97-f8ef3a9395d0.png)
![image](https://user-images.githubusercontent.com/97282647/177713930-2f04eacf-b67d-4bdf-8ef3-2cefe7beb800.png)

@jmini  shouldn't the submenu show first 10_dev-panel, then 20_front-end, then 30_back-end?

**Comment by jcunliffe1** [comment]
I doubled checked with content - there were a few errors in the titles, but fixing them made no difference. which makes sense, since the ordering should be taken only from the folder prefix precedence number, right?

**Comment by jcunliffe1** [comment]
btw I have the same problem in the main navigation:
![image](https://user-images.githubusercontent.com/97282647/177714990-86732a8c-ec7f-4bae-b6bc-3f213d4d0f15.png)
![image](https://user-images.githubusercontent.com/97282647/177715100-7cf8a642-c21a-4d48-83e0-e6a64079a578.png)

and haven't figured out how to rename arc42 with precedence prefix without breaking other stuff :)

**Comment by jmini** [comment]
@jcunliffe1 :

About the problem in the main navigation https://github.com/docToolchain/docToolchain/issues/692#issuecomment-1177185012, from what I see in the *current code*, this was never considered. I have tried to make it clear in PR https://github.com/docToolchain/docToolchain/pull/871 (check the update of `src/docs/015_tasks/03_task_generateSite.adoc`)

The way you influence the order and the display test of the the top level menu (the horizontal one) is with the `menu` config in `docToolchainConfig.groovy`.

Note that PR #871 is not changing the current implementation. Just documenting it better.

So your request would be a separated one, and has nothing to do with my change.

**Comment by jmini** [comment]
@jcunliffe1 :

About your problem with the ordering not being taken form the folder discussed in https://github.com/docToolchain/docToolchain/issues/692#issuecomment-1177183672

The problem is that the `index.adoc` has potentially a `:jbake-order:` attribute itself and when it i not the case it defaults to `0` (since the name is `index.adoc` and not `10_index.adoc` which would set it to 10).

This is why I wrote in the docs:

> In this case you might want to redeclare order value of the parent folder (`30` from the `30_delis` folder) in the index page using `:jbake-order: 30`.

Source https://github.com/jmini/docToolchain/blob/ec185ee3f14914d192d91ecd40988798e258c4f6/src/docs/015_tasks/03_task_generateSite.adoc#L132

But I agree that it would be way more natural to say that for `<path>/20_dev/index.adoc` when no `:jbake-order` is present, it should take the value from the parent folder. So `20` in the case of a folder named `20_dev`.

This would be more natural since the `index.adoc` page now correspond to the `20_dev` node in the navigation.

I will see what i can do for this.

**Comment by jmini** [comment]
@jcunliffe1 :

I have pushed a new version
https://github.com/jmini/dtc-experiments/commit/33b20a9f95f5744423f5a8b9cdeeceb42f4343a4

It solves:

*1)* An issue when the top level folder contains an Index page:

```
src/docs/
├── ...
├── 30_tri
│   ├── index.adoc
│   ├── 20_advanced.adoc
│   └── 30_test.adoc
├── ...
```

Right now it was lost.

---

*2)* An issue when there were only folders in the top level folder (no page):
```
src/docs/
├── ...
├── 10_foo
│   ├── 10_lorem
│   │   ├── 10_topic-A.adoc
│   │   └── 20_topic-B.adoc
│   └── 20_ipsum
│       ├── 10_one.adoc
│       ├── 20_two.adoc
│       └── 30_three.adoc
├── ...
```

Then the link in the top navigation was set to`<something>/null` which was a broken link, as discussed in https://github.com/docToolchain/docToolchain/issues/692#issuecomment-1178926901

---

@rdmueller can we merge https://github.com/docToolchain/docToolchain/pull/871 ? this is a prerequisite for this change anyway.

---

@jcunliffe1 : please update to the newest version and tell me if it works for you.

Maybe I will publish a new iteration if I manage to solve the `:jbake-order:` default value in the `index.adoc`.

**Comment by jmini** [comment]
@jcunliffe1 : please update to https://github.com/jmini/dtc-experiments/commit/21579e4930695bb75bea893dd848d0235812d1ce

I think this will be my final version. :-)

It fixes the problem with the index pages, as discussed in https://github.com/docToolchain/docToolchain/issues/692#issuecomment-1178926901

**Comment by jmini** [comment]
🎉 I have re-opened my PR: https://github.com/docToolchain/docToolchain/pull/870
