### ISSUE TITLE
generateSite drops inlined svg images

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#694]
**Describe the bug**

Svg images are not rendered correctly with `generateSite`

**To Reproduce**
Given this structure:

```
src/docs/
├── 20_du
│   └── 10_lorem.adoc
└── images
    └── svg
        └── lorem.svg
```

And the `10_lorem.adoc` file referencing the svg file:

```adoc
ifndef::imagesdir[:imagesdir: ../images]

== Lorem

//...

image::svg/lorem.svg[Lorem,300,opts=inline]
```

In the logs when I run `./dtcw local generateSite`, I already see:

```
> Task :bake
<stdin>: SVG does not exist or cannot be read: //images/svg/lorem.svg

```

And the image is missing in the output:

<img width="382" alt="Output of docToolchain generateSite" src="https://user-images.githubusercontent.com/1222165/141182038-75ae9b05-6027-48fb-9dc9-f0f05c20022a.png">

The html source code looks broken:

```html
<div class="imageblock">
  <div class="content">
    <span class="alt">Lorem</span>
  </div>
</div>
```

In the preview (using the Asciidoctor web browser extension), it looks correct:

<img width="378" alt="Preview with the Asciidoctor Browser extension" src="https://user-images.githubusercontent.com/1222165/141182066-23da4b09-3e32-479c-8320-bff3f8db142a.png">

Html source code:

```html
<div class="imageblock">
  <div class="content">
    <svg xmlns="http://www.w3.org/2000/svg" width="300">
      <rect x="50" y="20" rx="20" ry="20" width="120" height="120" style="fill:#489FF8;stroke:#EFBC40;stroke-width:5;opacity:1"></rect>
    </svg>
  </div>
</div>
```

**Expected behavior**
inline svg images are included on the page

**Configuration**
`./dtcw local --version`

```
dtcw - docToolchain wrapper V0.26
docToolchain V2.0.2
grep: /proc/version: No such file or directory
Java Version 8
docker available
home folder exists
force use of local install
use local homefolder install ~/.doctoolchain/

------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_202 (Azul Systems, Inc. 25.202-b05)
OS:           Mac OS X 10.15.2 x86_64
```

**Comment by jmini** [comment]
If I remove: `opts=inline`

Then the HTML is turned to:

```html
<div class="imageblock">
  <div class="content">
    <img src="..//images/svg/lorem.svg" alt="Lorem" width="300">
  </div>
</div>
```

And the image is displayed

**Comment by rdmueller** [comment]
can you please try to use `svg-type="inline"` instead of `opts="inline"`?

it could be this issue: https://github.com/asciidoctor/asciidoctor-diagram/issues/368

we have to upgrade our asciidoctor version asap.

**Comment by jmini** [comment]
It is working great with with `svg-type="inline"`.

Thank you a lot.

**Comment by rdmueller** [comment]
so let's close this for now and hope that the upgrade to asciidoctor 2.x will fix this in a more general way (https://github.com/docToolchain/docToolchain/issues/662)
