### ISSUE TITLE
exportToMarkdown docs are not referenced correctly

### ISSUE THREAD

**Issue by modularTaco** [docToolchain/docToolchain#697]
In http://doctoolchain.org/docToolchain/v2.0.x/015_tasks/03_task_exportMarkdown.html

```
Unresolved directive in <stdin> - include::/home/runner/work/docToolchain/docToolchain/build/exportMarkdownDocs.adoc[]
```
Screenshot:

![image](https://user-images.githubusercontent.com/37046961/141778914-11d345b1-14ce-4967-bee9-3ee0692bcd6c.png)

---
#page:015_tasks/03_task_exportMarkdown.adoc

**Comment by rdmueller** [comment]
thanx for reporting. fixed.
