### ISSUE TITLE
master to ng

### ISSUE THREAD

**Issue by Hellmy** [docToolchain/docToolchain#716]
**Describe the bug**
Current master improvments are not out of the box in ng

**To Reproduce**
The mavenUsername and mavenPassword are not part of ng branch

**Question**
What branches are the future? Where to focus on and how to strip off the old parts?

**Comment by rdmueller** [comment]
sorry, I havent's noticed that the mavenPassword was changed in the master branch.

The ng branch is the 2.0.x and default branch. it is the future.

I left the old master branch in order to not to break other installations.
But I think it is a good idea too think about how to advance and how to document this in a clear way.

Any ideas on that?

**Comment by Hellmy** [comment]
Hello,

Is there already a good migration guide from version 1 to 2? So the version 1 could be deprecated and also link to the migration guide and also have the deprecation warning.

Could the master also be merged back to version 2 or are there already too many changes?

Regards
Manuel 

Am 11. Dezember 2021 13:50:31 MEZ schrieb "Ralf D. Müller" ***@***.***>:

**Comment by Hellmy** [comment]
I saw the deprecation note on the master - good one. Perhaps only left would be the merge back to ng of some features and to have this in mind on every pull request?!

**Comment by rdmueller** [comment]
When 2.0.0 was released, master was merged back before. So, there shouldn't be too much difference at the moment.
OK. Github says 29 commits:

This branch is 29 commits ahead, 

I've created a draft PR to see what has to be merged. I guess I will do this manually

**Comment by rdmueller** [comment]
no, unfortunately, there is no real migration guide, but it would be a good idea.

let's write one!

the main difference is that doctoolchain now is insalled as command line tool with the wrapper dtcw. If we are lucky, that's all

**Comment by mh182** [comment]
I think this issue is stale and should be closed. 
A migration guide does not make sense anymore.
