### ISSUE TITLE
Missing .gitattributes

### ISSUE THREAD

**Issue by Hellmy** [docToolchain/docToolchain#720]
**Describe the bug**
Checking out and building a zip package can result in erros of the package as files sometimes are converted to crlf line endings...

**Expected behavior**
Building the zip file is possible everywhere

**Possible Solution**
Add a .gitattributes file 
```
*.sh		 eol=lf
*.bat		 eol=crlf
gradlew      eol=lf
doctoolchain eol=lf
dtcw         eol=lf
```

**Comment by rdmueller** [comment]
oh, that is a good idea! Will you create a PR?

**Comment by Hellmy** [comment]
Will do it tomorrow

**Comment by dwildmark** [comment]
This solution creates a dirty repo when checked out in linux. The gradle wrapper for windows is checked in as LF and when it is checked out it gets converted to CRLF, which means it will show up as an unstaged change in the git repository. This is very annoying when docToolchain is used as a git submodule.

**Comment by rdmueller** [comment]
Argh. Do you have a solution?

**Comment by dwildmark** [comment]
It might work to leave out the line
`*.bat		 eol=crlf`
and just have `gradlew.bat` checked in as CRLF, though I have not tested this fully.

**Comment by rdmueller** [comment]
So,

```
*.sh         eol=lf
gradlew.bat      eol=crlf
gradlew      eol=lf
doctoolchain eol=lf
dtcw         eol=lf
```

should work? let's give it a try!

**Comment by Hellmy** [comment]
Yeah that should be fine.

But shouldn't the bat files have a crlf like ending? So shouldn't better the file be changed? 

Am 16. März 2022 16:52:22 MEZ schrieb "Ralf D. Müller" ***@***.***>:

**Comment by hardyacht** [comment]
Will there be a fix? In our system as submodule it makes every build a dirty :/

**Comment by Hellmy** [comment]
I can take a look next week - just set me a reminder 

Am 25. April 2022 15:51:39 MESZ schrieb "hardy.a" ***@***.***>:
