### ISSUE TITLE
JDK_JAVA_OPTIONS with dtcw

### ISSUE THREAD

**Issue by Hellmy** [docToolchain/docToolchain#721]
**Describe the bug**
dtcw breaks when running java with JDK_JAVA_OPTIONS as the first line is the note with the JDK_JAVA_OPTIONS

**To Reproduce**
1. set JDK_JAVA_OPTIONS
2. start dtcw
the script aborts because the java version is not valid

**Expected behavior**
working fine

**Comment by rdmueller** [comment]
oops. Do you already have a fix?

**Comment by Hellmy** [comment]
I misread the logs - it works fine but the version is not correctly determined....

So low piority but not nice

**Comment by mh182** [comment]
Closing, since it works as supposed (` JDK_JAVA_OPTIONS` is used).
