### ISSUE TITLE
Docs: Feedback for 'generateDeck' 👎

### ISSUE THREAD

**Issue by ghilainm** [docToolchain/docToolchain#727]
Could you provide a bit more example on how to use the task, what are the prerequisites? Do we have to manually provide reveal.js binary? 

Thx for your inputs and your work ;) 

---
#page:015_tasks/03_task_generateDeck.adoc

**Comment by rdmueller** [comment]
Thanx for the feedback.
Have you tried it with the cli version or the docker one?
And yes, we will provide a tutorial for this asap

**Comment by ghilainm** [comment]
Hellow in the mean time I found out what to do by reverse engineering the task!

I had to do the gitsubmodule init
Configure input files properly
Move the generated presentation to the reveal.js directory

Would be nice if doc tool chain could use the latest asciidoctor reveal.js plugin.

edit: I just saw that the strategy to install doctoolchain has changed i ll give it a try!


Thanks for your answer!

**Comment by rdmueller** [comment]
> Would be nice if doc tool chain could use the latest asciidoctor reveal.js plugin.

yes, next step is to update all dependencies and keep them up to date.

**Comment by rdmueller** [comment]
> edit: I just saw that the strategy to install doctoolchain has changed i ll give it a try!

since we changed the strategym I haven't checked the generateDeck task. Feedback is highly welcome

**Comment by wonderbird** [comment]
Thank you @ghilainm for your comments. the `git submodule init` was the missing link for me :-)

I have written down the steps to create a presentation from scratch in PR https://github.com/docToolchain/docToolchain/pull/861

**Comment by mh182** [comment]
I close this issue since it was merged.
