### ISSUE TITLE
create adoc from confluence

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#73]
the goal is to create a task which takes a configured tree of confluence pages and converts it to asciidoc.

the use case I have in mind is the following: some people find it easier to create documentation in confluence. This is ok, but these parts of the docs are then not part of the toolchain and can't for instance easily be converted to PDF.
If we convert confluence back to asciidoc, we can feed it back into the toolchain.

**Comment by jakubjab** [comment]
I'm not sure what this issue is about, but I have created an extension for docToolchain to import a tree of Confluence pages into asciidoc, for the purpose of moving my documentation into code repository. But this was one-time migration really, and after the fact I didn't think it was worth the effort. I guess depends how much documentation one has.

**Comment by rdmueller** [comment]
thanx for your input. I've just updated the description. How did you convert the pages and which where the problems?

**Comment by jakubjab** [comment]
I have pushed my scripts to the branch:

https://github.com/jakubjab/docToolchain/blob/confluence-to-asciidoc/scripts/confluence2asciidoc.groovy

https://github.com/jakubjab/docToolchain/blob/confluence-to-asciidoc/scripts/ConfluenceExportConfig.groovy

They were connected to build.gradle the same way as other tasks, with "evaluate".
They are using pandoc to convert files, and tidy to clean them up.

Feel free to use as input, I'm not sure they are still running after recent changes.

**Comment by rdmueller** [comment]
wow. I need to spend more time on my own project :-(

Is it possible to turn this into a PR?

**Comment by rdmueller** [comment]
we are currently working on this to make it a documented part of docToolchain

**Comment by rdmueller** [comment]
I'll close this issue, because the referenced repository with the scripts is gone

**Comment by andacaydin** [comment]
This is exactly what I would have needed! Damn.

**Comment by rdmueller** [comment]
it is here: https://doctoolchain.org/docToolchain/v2.0.x/015_tasks/03_task_exportConfluence.html ! :-)
