### ISSUE TITLE
Docs: Feedback for 'Diagrams: Diagrams.net'

### ISSUE THREAD

**Issue by ambition-consulting** [docToolchain/docToolchain#737]
We should probably mention, that this requires the corresponding plugin from https://plugins.jetbrains.com/plugin/15635-diagrams-net-integration

---
#page: https://github.com/doctoolchain/doctoolchain/edit/ng/src/docs/020_tutorial/100_diagrams.net.adoc
#branch: ng

**Comment by rdmueller** [comment]
thanx for the feedback. I've added some more infos.

**Comment by mh182** [comment]
Can we close this issue?

**Comment by ambition-consulting** [comment]
yes, thanks.
