### ISSUE TITLE
Docker version is still trying to load dependencies from jcenter and fails

### ISSUE THREAD

**Issue by huima** [docToolchain/docToolchain#744]
**Describe the bug**

I downloaded the new wrapper and tried to generateHTML from the new template, which I also created with the new wrapper and docker version - rdmueller/doctoolchain:v2.0.3.

**To Reproduce**

`./dtcw generateHTML
fatal: not a git repository (or any of the parent directories): .git
dtcw - docToolchain wrapper V0.28
docToolchain V2.0.3
grep: /proc/version: No such file or directory
docker available
/usr/local/bin/docker
use docker installation
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.7.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
arc42/arc42.adoc

> Task :generateHTML

> Task :generateHTML FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateHTML'.
> Could not resolve all files for configuration ':asciidoctor'.
   > Could not download asciidoctorj-diagram-2.1.2.jar (org.asciidoctor:asciidoctorj-diagram:2.1.2)
      > Could not get resource 'https://jcenter.bintray.com/org/asciidoctor/asciidoctorj-diagram/2.1.2/asciidoctorj-diagram-2.1.2.jar'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`

**Expected behavior**

Task to run through successefully.

**Configuration**
 - docToolchain version 2.0.3
 - OS: OS X
 - JDK 11: openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

Grep does not find any references to jcenter in the configs or in the template, but somehow it is still tried.

A peculiar thing is that after I ran once with : ./dtcw generateHTML --stacktrace

It started to work consistently again, so potentially it was able to load the dependency and continued to work. Before that running those tasks failed consistently to some dependency which was not downloaded in time from jcenter.

**Comment by rdmueller** [comment]
thanx. I will check asap

**Comment by rdmueller** [comment]
hm. that is strange. But I noticed on twitter some people mentioning that jcenter had hickups.
my main problem with the docker container is that I didn't manage to create one which does not fetch any further dependencies from the net :-(

I just tried to reproduce the problem but didn't succeed. What's your current status?

**Comment by rdmueller** [comment]
and yes, all jcenter references have been removed. The docker image contains just a copy of this repository. I guess gradle has jcenter somehow as fallback hardcoded. But this also shouldn't be a problem - jcenter is still alive, but read-only: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by huima** [comment]
Yeah. It could be that if there is a some hiccup for whatever reason, it can fail - but few retries will make it work eventually.

**Comment by rdmueller** [comment]
afaik, all dependencies are now included with the current docker image, so this problem should be solved.
