### ISSUE TITLE
dtcw - cannot be run with cygwin / git bash on windows

### ISSUE THREAD

**Issue by bratkartoffel** [docToolchain/docToolchain#782]
**Is your feature request related to a problem? Please describe.**
The doctoolchain wrapper cannot be executed using git bash / cygwin on windows in combination with docker, as some paths are not correctly passed to docker.

1. the `${PWD}` is resolved against the mingw root, resulting in a path like `/d/devel/workspace/documentation`. This path cannot be resolved by docker.
2. `/bin/bash` as `--entrypoint` is clobbed by mingw whilst trying to convert it to some mingw path (e.g. `D:/devel/PortableGit/usr/bin/bash`)

**Describe the solution you'd like**
The wrapper needs some minor adjustments for mingw.

1. Instead of using `$PWD` directly, this value should be read differently when running in cygwin, e.g.:
```bash
if command -v cygpath &>/dev/null; then
  pwd=$(cygpath -w $PWD)
else
  pwd=$PWD
fi
```

2. Using `//bin/bash` as entrypoint (note the double slash at the beginning) causes mingw not to mess with the path and take it as it is. This change has no impact on other systems.

**Describe alternatives you've considered**
Running with WSL, but the warning about plantuml is also not nice as we use that.

**Additional context**
```patch
--- a/dtcw
+++ b/dtcw
@@ -201,7 +201,12 @@
          fi
           docker_cmd=$(which docker)
           echo $docker_cmd
-          command="$docker_cmd run -u $(id -u):$(id -g) --name doctoolchain${version} -e DTC_HEADLESS=1 -e DTC_SITETHEME -p 8042:8042 --rm -i --entrypoint /bin/bash -v '${PWD}:/project' rdmueller/doctoolchain:v${VERSION} -c \"doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS && exit\""
+          if command -v cygpath &>/dev/null; then
+              pwd=$(cygpath -w $PWD)
+          else
+              pwd=$PWD
+          fi
+          command="$docker_cmd run -u $(id -u):$(id -g) --name doctoolchain${version} -e DTC_HEADLESS=1 -e DTC_SITETHEME -p 8042:8042 --rm -i --entrypoint //bin/bash -v '${pwd}:/project' rdmueller/doctoolchain:v${VERSION} -c \"doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS && exit\""
           doJavaCheck=false
          echo "use docker installation"
       else
```

**Comment by rdmueller** [comment]
thanx for the feedback. Since WSL is available for windows as a good substitution for cygwin / git bash, I prefere that everybody uses WSL or powershell :-)

But I do understand your need. It looks like you are ready to send a PR? I would it be ok for you to do so?

Here is the source of `dtcw`: https://github.com/docToolchain/docToolchain.github.io

**Comment by bratkartoffel** [comment]
Thanks for looking into it.
Sure, hadn't found the repository of the script when posting this issue.
I'll file the PR by the end of the week.
