### ISSUE TITLE
gradle takes no proxy information

### ISSUE THREAD

**Issue by funkr** [docToolchain/docToolchain#79]
Hello Ralf,

I tried this stuff and stumbled up two things. 

1. The path to git must be configured in the path variable. (this was an easy fix but a check at beginning would have been helpful)

2. Gradle does not use the proxy which I have use on business laptop. 
I tried in gradle.properties:
systemProp.http.proxyHost=grz-proxy.avl.com
systemProp.http.proxyPort=8080

and on commandline 
-Dhttp.proxyHost=grz-proxy... -Dhttp.proxyPort=8080

Nothing worked. Any Idea?

Greetings Roman

**Comment by rdmueller** [comment]
have you already tried to set the proxy as described in this blog post?
https://rdmueller.github.io/enterprise-edition/

**Comment by rdmueller** [comment]
@funkr sorry, this issue is now open for a long time. 
I don't know how I could reproduce it. The environment where I operate docToolchain behind a proxy, it works for me with the information found at https://rdmueller.github.io/enterprise-edition/
Please re-open if this is still an issue.
