### ISSUE TITLE
proxy support for dctw 

### ISSUE THREAD

**Issue by janmaterne** [docToolchain/docToolchain#790]
**Is your feature request related to a problem? Please describe.**
Running dctw.ps1 behind a corporate proxy doesnt work as no artifacts could be downloaded.

**Describe the solution you'd like**
Enhance dtcw for handling proxy settings.

**Comment by rdmueller** [comment]
thanx!

**Comment by mh182** [comment]
Can we close this issue? It seems to be merged.

**Comment by rdmueller** [comment]
This was a change to dtcw.ps1. I think I have included in the rewrite, so lets close it
