### ISSUE TITLE
Multiple run of dtcw with docker is failing because of a container name conflict

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#829]
**Describe the bug**
Multiple run of docToolchain via docker is not supported on the same machine

**To Reproduce**
Have long run of docToolchain and start 2 of them in parallel.

**Current behavior**

Failing with:
```
./dtcw generateSite
dtcw - docToolchain wrapper V0.29
docToolchain V2.0.3
docker available
/usr/bin/docker
use docker installation
docker: Error response from daemon: Conflict. The container name "/doctoolchain" is already in use by container "3352c81b6369435e454b2343e3862cb5d14c151fad635322ec9b505909065270". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

**Expected behavior**
Is it really required to name the container to a fix name, couldn't be something like "doctoolchain+<currentTimeMillis>" or something random.

**Configuration**
 - docToolchain 2.0.3
 - OS: Linux

**Comment by rdmueller** [comment]
I wasn't aware of this. No, a fixed name is not required.

I guess we have to fix this line:

https://github.com/docToolchain/doctoolchain.github.io/blob/master/dtcw#L209

shall we add a timestamp? Or shall we remove the `-name` parameter?

**Comment by jmini** [comment]
If `-name` is removed you get a random name like "marvelous-lion".

I tend to agree with the author of this question:
https://www.reddit.com/r/docker/comments/ga5f5t/can_you_specify_a_prefix_for_a_random_docker_name/

And I think that having a `$(date +%s)` suffix is great to see which tool has spawned a container…

**Comment by rdmueller** [comment]
Sounds perfect. Would you mind to send a PR?
