### ISSUE TITLE
Transfer Repository to Organisation

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#83]
I think it is time to transfer this repository to its own organisation.
This would allow us to easily split it into several repositories.

what do you think? @bodewig @bodewig @MoePad @ahus1 @isidorotrevino 

https://help.github.com/articles/about-repository-transfers/

the target could be this one: https://github.com/docToolchain

It seems that all links and urls would be redirected...

**Comment by bodewig** [comment]
I agree it would make navigating several repos simpler.

**Comment by isidorotrevino** [comment]
Sounds good to me

**Comment by ahus1** [comment]
I have participated in a transfer before, and it worked quite well. But I don't have an opinion about the split of the repo.

**Comment by MoePad** [comment]
Sounds good to me, too, although I've no expierence with github organizations...

**Comment by rdmueller** [comment]
OK. I will transfer the repository asap. The docs say that all URLs will be redirected - so I expect no problems :-)

**Comment by rdmueller** [comment]
Done. all old urls are redirected
