### ISSUE TITLE
Docs: Feedback for 'previewSite'

### ISSUE THREAD

**Issue by christlang** [docToolchain/docToolchain#834]
arc42 template has previewPort = 8881
but docker-image rdmueller/doctoolchain:v2.0.5
exposes 8042

proposed change in docToolchainConfig.groofy

```
microsite.with {
    // ...
    previewPort = 8042
    // ...
```

---
#page: https://github.com/doctoolchain/doctoolchain/edit/ng/src/docs/015_tasks/03_task_previewSite.adoc
#branch: ng

**Comment by rdmueller** [comment]
thanx for this good feedback! just fixed it.
