### ISSUE TITLE
add changelog and docs for PR #833

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#835]
https://github.com/docToolchain/docToolchain/pull/833

@z0lberg would you like to do this or shall I take a look?

**Comment by z0lberg** [comment]
I can do this. May be I need some guide how to do this. Do you have it?

**Comment by rdmueller** [comment]
good point. Currently there is no guide. maybe we should create one?

**Comment by z0lberg** [comment]
Yes. Let me prepare the next pull request and we can start doing that.

**Comment by z0lberg** [comment]
Okay, I am having code for merging, what is the next steps?

**Comment by rdmueller** [comment]
as far as I know, this has been solved, hasn't it?
