### ISSUE TITLE
Unable to run generateSite because of a jcenter outage?

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#843]
**Describe the bug**
It is not possible to build the documentation when `jcenter` has an outage.

**To Reproduce**

1. Wait until jcenter has an outage :-) (I think it is possible to fake this)
2. Run `generateSite`

Log example: on 2022-05-09:
```
09.05 11:25:32  dtcw - docToolchain wrapper V0.29
09.05 11:25:32  docToolchain V2.0.3
09.05 11:25:32  docker available
09.05 11:25:32  /usr/bin/docker
09.05 11:25:32  use docker installation
09.05 11:25:34  To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.7.1/userguide/gradle_daemon.html.
09.05 11:25:35  Daemon will be stopped at the end of the build stopping after processing
09.05 11:25:39  
09.05 11:25:39  > Configure project :
09.05 11:25:39  pages/**/*.adoc
09.05 11:25:41  
09.05 11:25:41  > Task :generateSite
09.05 11:25:41  created
09.05 11:25:41  /project/build/microsite/tmp
09.05 11:25:41  copy internal theme /home/dtcuser/docToolchain/src/site
09.05 11:25:41  copy project theme /project/src/site
09.05 11:25:41  
09.05 11:25:41  > Task :copyImages
09.05 11:25:43  > Task :bake FAILED
09.05 11:25:43  
09.05 11:25:43  FAILURE: Build failed with an exception.
09.05 11:25:43  
09.05 11:25:43  * What went wrong:
09.05 11:25:43  Execution failed for task ':bake'.
09.05 11:25:43  > Could not resolve all files for configuration ':jbake'.
09.05 11:25:43     > Could not download flexmark-jira-converter-0.62.2.jar (com.vladsch.flexmark:flexmark-jira-converter:0.62.2)
09.05 11:25:43        > Could not get resource 'https://jcenter.bintray.com/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.jar'.
09.05 11:25:43           > Could not GET 'https://jcenter.bintray.com/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.jar'.
09.05 11:25:43              > org.apache.http.client.ClientProtocolException (no error message)
09.05 11:25:43  
09.05 11:25:43  * Try:
09.05 11:25:43  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
09.05 11:25:43  
09.05 11:25:43  * Get more help at https://help.gradle.org/
09.05 11:25:43  
09.05 11:25:43  BUILD FAILED in 9s
09.05 11:25:43  3 actionable tasks: 3 executed
```

**Expected behavior**

I am not sure, I have 2 ideas (open for discussions):

* Have some libraries already cached inside the docker image
* Have the possibility to indicate a jcenter/maven-central mirror per configuration.

**Configuration**
 - docToolchain 2.0.3
 - OS: Linux
 - Docker

**Comment by rdmueller** [comment]
yeah, this is a problem but it also should be resolved by now. But we still need testers.

docToolchain 2.0.5 should now include all dependencies within the container.
"should" because I am not 100% sure - docToolchain uses dependencies in gradle script plugins which might be only resolved when you use them.

Can you give 2.0.5 a try?

**Comment by Trueber** [comment]
This issue happened again today with 2.0.5 and 2.1.0
Log from 2.1.0:
`Execution failed for task ':generateHTML'.
 > Could not resolve all files for configuration ':asciidoctor'.
  > Could not download asciidoctorj-groovy-dsl-1.6.0.jar (org.asciidoctor:asciidoctorj-groovy-dsl:1.6.0)
   > Could not get resource 'https://jcenter.bintray.com/org/asciidoctor/asciidoctorj-groovy-dsl/1.6.0/asciidoctorj-groovy-dsl-1.6.0.jar'.
    > Could not GET 'https://jcenter.bintray.com/org/asciidoctor/asciidoctorj-groovy-dsl/1.6.0/asciidoctorj-groovy-dsl-1.6.0.jar'.
     > Read timed out`

**Comment by rdmueller** [comment]
I didn't experience this problem anymore, so I will close it for now. Please reopen if your still see room for improvement.
