### ISSUE TITLE
Adding custom asciidoctorj macro when generating the site?

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#848]
We would like to add some custom asciidoctorj macro present in our company maven repository (Nexus).

I looked at the logic in:

* [`scripts/AsciiDocBasics.gradle`](https://github.com/docToolchain/docToolchain/blob/ng/scripts/AsciiDocBasics.gradle)
* [`scripts/generateSite.gradle`](https://github.com/docToolchain/docToolchain/blob/ng/scripts/generateSite.gradle)

Probably `generateSite.gradle` is the relevant one.

I am not sure how this can be made, and maybe this is a JBake limitation.

I would appreciate some pointers.

**Comment by rdmueller** [comment]
Yes, `generateSite.gradle` is the relevant one.

To add your own asciidoc extension, we have to solve two problems:

- find out how to use extensions for jBake
- find a way how to extend docToolchain on a project basis

let's start with the first one. This looks like a good starting point: https://jorge.aguilera.soy/blog/2020/asciidoctor-jbake.html 
- at least if your macro extension is written in java

To give this a try, you need to modify the docToolchain sources.
If you use docToolchain locally installed, you will find the sources in `$HOME/.docToolchain/...`. If you use the docker install, switch to a local install by executing `./dtcw local tasks`.
When you have located the right folder, you can modify the sources there and experiment with it.

**Comment by jmini** [comment]
_Thank you very much for your quick feedback on this and sorry for the delay on my side._

---

Using an asciidoctor macro written in Java inside JBake is really straight forward.
I just did it here:
https://github.com/jmini/jbake-gradle-sample/commit/356275ad7755a29cc0074326813700248e7ddc06

Thank you very much for this.

---

I will now try to do the same inside the `docToolchain` sources. To make sure I understand how it works.

---

What is your vision for a case like this?

Ideally at project level, I would like to be able to specify:

* the macros I would like to use.
* the repository that it should get them from (together with the credentials -- some of our repo is private).
* probably also some asciidoctor configs (that should be passed to JBake when building) [in my simple example, I have configured it at asciidoctor document level]

If this is not possible, the only other thing I am thinking about is forking the docToolchain for our company and do a company-specific release. This somehow feels wrong, because maintaining a fork is never a good idea.

**Comment by rdmueller** [comment]
> Using an asciidoctor macro written in Java inside JBake is really straight forward.
> I just did it here:

wow - cool! This will enable nice add ons in the future.

> What is your vision for a case like this?

quite a good question. docToolchain primary helps to make things easier, but when it comes to adding additional features, there is still room for improvement.
I hope that we can find a good way how to add extensions like yours on a project basis.

if I understand your example correct, you only need a way how to add onother dependency, right? I think that can be done in gradle...

the part

```
    dependencies {
        classpath  'commons-configuration:commons-configuration:1.10'
        classpath  'fr.jmini.asciidoctorj:jira:1.1.0'
    }
```

should be just code. So something like

```
    dependencies {
        classpath  'commons-configuration:commons-configuration:1.10'
        if (config.jbake.plugins) {
          config.jbake.plugins.each { plugin ->
             classpath  plugin
          }
       }
    }
```

could already work
