### ISSUE TITLE
Toc on the right not displayed

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#852]
I have 2 project setup:

One is displaying the toc on the right:
<img width="299" alt="docToolchain site" src="https://user-images.githubusercontent.com/1222165/171565067-2eed14ed-563b-4993-8bb8-71bedde1b240.png">
source: https://github.com/jmini/dtc-experiments

The other one isn't:
<img width="328" alt="docToolchain site " src="https://user-images.githubusercontent.com/1222165/171565219-fae1fdae-155e-42b3-aa56-604021906449.png">

Same docToolchain version.
I already compared the `docToolchainConfig.groovy`

This is probably something really silly…

**Comment by rdmueller** [comment]
this is not an issue with the config. I might be an issue with the asciidoc or :jbake-meta-data: .
Do you have a link for the one which doesn't display the TOC?

**Comment by jmini** [comment]
Thank you for the quick response.

>  Do you have a link for the one which doesn't display the TOC?

No, this is company internal. Sorry.

---

I think I found it:

The project that does not work has a modified `src/site/templates/rightcolumn.gsp`

This is the relevant line:

https://github.com/docToolchain/docToolchain/blob/c089ad038651a058667e885d4db7f5328e8ade0c/src/site/templates/rightcolumn.gsp#L17

**Comment by rdmueller** [comment]
ah, yes. modification of the templates can be a problem. I also just noticed that the zoom factor of the browser can be an issue - if the theme thinks there is not enough space, it will skip the right column.
