### ISSUE TITLE
Make the links (Improve this doc, Create an issue) optional

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#853]
**Is your feature request related to a problem? Please describe.**
Sometimes you do not want the links:

* Improve this doc
* Create an issue

To be displayed:

<img width="299" alt="Screenshot of the links in question" src="https://user-images.githubusercontent.com/1222165/171600767-d42d60d6-c347-43c0-abe1-fc55c2df6483.png">

**Describe the solution you'd like**

The `docToolchainConfig.groovy` provides the possibility to configure the values:
https://github.com/docToolchain/docToolchain/blob/c0e3ceae51c786462d0340b8fb71eb97e39f2f3e/docToolchainConfig.groovy#L98-L104

That are used in the template:
https://github.com/docToolchain/docToolchain/blob/c0e3ceae51c786462d0340b8fb71eb97e39f2f3e/src/site/templates/rightcolumn.gsp#L7-L8
and here:
https://github.com/docToolchain/docToolchain/blob/c0e3ceae51c786462d0340b8fb71eb97e39f2f3e/src/site/templates/rightcolumn.gsp#L11-L12

Would it be possible to check if `config.site_gitRepoUrl` and `config.site_issueUrl` are not null and to display the links only in that case?

**Describe alternatives you've considered**
Overriding locally `rightcolumn.gsp`, but this is not easy to maintain over time.

**Additional context**

See https://github.com/docToolchain/docToolchain/issues/852

**Comment by jmini** [comment]
I was thinking something like this: https://github.com/jmini/docToolchain/commit/074c82519dcc3bf18bc1807058c8ce20013fb527

If you agree with this change, then I would like to document it and file a PR.

**Comment by rdmueller** [comment]
Thanx! This is a good idea and the implementation also look perfect.
