### ISSUE TITLE
dtcw effectively not running in non-interactive mode

### ISSUE THREAD

**Issue by ascheman** [docToolchain/docToolchain#867]
**Describe the bug**
When running `dtcw` in a non-interactive environment, it asks whether it should install doctoolchain to the home folder and stops (as there is no user to answer `yes`). 

**To Reproduce**
1. Start dtcw in your Jenkins
2. See the job completed with the last output as 
```
  Do you wish to install doctoolchain to /home/jenkins/.doctoolchain?
  1) Yes
  2) No
  #? 
```

**Expected behavior**
In non-interactive mode it should expect all responses as positive (or even not ask but just act).

**Comment by rdmueller** [comment]
three solutions:

1) export DTC_HEADLESS=true
this will omit the question

2) use the docker image
the docker image already contains docToolchain as command line tool and thus will not try to download it. It also already contains all java dependencies

3) use an environment where docker is installed
if docker is available in the non-interactive environment, dtcw will use docker and thus will not try to download docToolchain

Here is a CI/CD Demo which works for GitLab and GitHub: https://github.com/docToolchain/ci-cd-demo

hope this helps.

Now, where should we put this information to help others with the same question?

**Comment by ascheman** [comment]
1. Maybe DTC_HEADLESS should be set depending on the status of `tty -s` (BTW, its value seems not to be consistently used, sometime as ["true"](https://github.com/docToolchain/doctoolchain.github.io/blob/master/dtcw#L281), sometimes as ["1"](https://github.com/docToolchain/doctoolchain.github.io/blob/master/dtcw#L269))?
2. Using docker is not an option (as we are running already in a Jenkins Docker agent here, currently in a local Docker daemon, but probably in the future in EKS or Fargate).

**Comment by rdmueller** [comment]
1. yes, good idea. regarding "true" or "1", afaik, it only needs to be set
2. ok, then => 1. or your new option to automatically switch to headless.

**Comment by rdmueller** [comment]
we have already solved this, haven't we? Can we close this issue?

**Comment by mh182** [comment]
No, we can't close this. 

All three solutions do not work. Neither with `dtcw` 2.2.0, nor `dtcw` 2.2.1, nor with the version provided in #1077.

As long there is no `docToolchainConifg.groovy` in the directory, the underlying Gradle build will interactively ask for the creation of the file.

**Comment by rdmueller** [comment]
Hm. But I think this is ok. HEADLESS mode was mainly introduced to be able to run dtcw on a build system. There it is expected that a configuration is already available but dtcw ahould not as if the theme should be downloaded...
