### ISSUE TITLE
generateDeck: tutorial for revealjs should be updated

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#869]
thanx to @wonderbird , we now have a tutorial on how to use the generateDeck task.

see #861 for more details.

but there is more work to do on this:

the tutorial is based on the docs-as-co.de tutorial which is outdated - still works but outdated.

- [ ] ToDo: remove docs-as-co.de tutorial

the ./dtcw version of docToolchain does not come with reveal.js . The installer does not clone the corresponding repository. We should fix this

- [x] fix clone of  reveal.js repository for installer

since a few days, we don't need sdk man anymore to install java for docToolchain. a `./dtcw getJava` is enough

- [ ] update tutorial accordingly

**Comment by jmini** [comment]
Not sure if this is related but the test `skipped generation of slide deck` does not work on the `ng` branch (see https://github.com/docToolchain/docToolchain/pull/872#issuecomment-1179293716)

**Comment by rdmueller** [comment]
@jmini , yes this is related. the approach described in the tutorial is the old one, but works. 
the ng-branch needs to clone the reveal-js stuff to work. It is on my roadmap to check this.

**Comment by rdmueller** [comment]
[x] fix for local bash
[ ] fix for docker image
[x] fix for powershell / cmd

**Comment by mh182** [comment]
We probably have to adapt this again after #1098 is integrated.

**Comment by PacoVK** [comment]
#1098  removed the necessity to manually clone reveal.js. The scripts `clone.sh | ps1` were removed. Furthermore a small doc was introduced to `generateDocs` on how to configure revealJs decks. 
A revise of the existing how-to of #861  would be necessary
