### ISSUE TITLE
Netlify preview in the PR is not using the latest version

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#876]
**Describe the bug**
In PR #875 I have made a change to `scripts/generateSite.gradle` but from what I see, this version is not taken into account when looking at the preview.

**To Reproduce**
1. Open a PR with a change to `scripts/generateSite.gradle`
2. Click on the preview link: https://deploy-preview-875--dtc-docs-preview.netlify.app/

**Expected behavior**
In my opinion it should use all the files of the PR commits.

**Work around**

To test it, I have made following change locally:
```patch
diff --git a/dtcw b/dtcw
index 26c113f3..287a6068 100755
--- a/dtcw
+++ b/dtcw
@@ -9,7 +9,7 @@
 #...
 
 MAIN_CONFIG_FILE=docToolchainConfig.groovy
-VERSION=2.0.5
+VERSION=2.0.0-dev
 DISTRIBUTION_URL=https://github.com/docToolchain/docToolchain/releases/download/v${VERSION}/docToolchain-${VERSION}.zip
 export DTC_PROJECT_BRANCH=$(git branch --show-current)
 
diff --git a/scripts/generateSite.gradle b/scripts/generateSite.gradle
index 5dd780fc..a14c8a2f 100755
--- a/scripts/generateSite.gradle
+++ b/scripts/generateSite.gradle
@@ -61,7 +61,7 @@ task generateSite(
     description: 'generate a microsite using jBake.') {
     doLast {
         new File("${targetDir}/microsite/tmp").mkdirs()
-        println "created"
+        println "created XXX"
         println new File("${targetDir}/microsite/tmp/").canonicalPath
         //copy internal theme
         println "copy internal theme ${new File(projectDir, 'src/site').canonicalPath}"
```

And I also created a symbolic link between `docToolchain-2.0.0-dev` and my local clone of the `docToolchain` repo:
```
ln -s ~/Git/docToolchain ~/.doctoolchain/docToolchain-2.0.0-dev
```

See http://doctoolchain.org/docToolchain/v2.0.x/025_development/010_setup_dev_env.html

Then all my changes are taken into consideration.

**Additional context**

With commit https://github.com/jmini/docToolchain/commit/354cfb311158d02e68e607369c9726e0673ba724 I made the change to demonstrate the issue. I have opened the draft PR https://github.com/docToolchain/docToolchain/pull/877

When you look at the "Netlify 🔍 Latest deploy log" you see:
```
10:21:58 AM: created
```
https://app.netlify.com/sites/dtc-docs-preview/deploys/62cbdd2635638900089e6c20#L310

And not the expected:
```
10:21:58 AM: created XXX
```

**Comment by jmini** [comment]
@rdmueller is the Netlify deploy script something that can be modified?

**Comment by rdmueller** [comment]
@jmini , the netlify script is the following command:

```
./dtcw tasks && ./dtcw exportContributors && ./dtcw exportExcel && ./dtcw exportMarkdown && ./dtcw generateSite
```

The output start with

```
12:03:49 PM: $ ./dtcw tasks && ./dtcw exportContributors && ./dtcw exportExcel && ./dtcw exportMarkdown && ./dtcw generateSite
12:03:49 PM: Using headless mode since there is no (terminal) interaction possible
12:03:49 PM: dtcw - docToolchain wrapper V0.31
12:03:49 PM: docToolchain V2.0.5
12:03:49 PM: docToolchain not installed.
12:03:49 PM: sdkman not found
12:03:49 PM: installing doctoolchain
12:03:49 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
12:03:49 PM:                                  Dload  Upload   Total   Spent    Left  Speed
12:03:49 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
12:03:49 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
12:03:49 PM: 100 1783k  100 1783k    0     0  4631k      0 --:--:-- --:--:-- --:--:-- 4631k
12:03:49 PM: Archive:  /opt/buildhome/.doctoolchain/source.zip
12:03:49 PM:    creating: /opt/buildhome/.doctoolchain/./docToolchain-2.0.5/
12:03:49 PM:    creating: /opt/buildhome/.doctoolchain/./docToolchain-2.0.5/bin/
```

So, it takes the current sources from `/src/docs`, but uses the configured (old) version of docToolchain. In this case 2.0.5.

In order to use the current version to build the docs, I guess we have to

* copy the working folder to `$HOME/.doctoolchain/doctoolchain-dev`
* set the version inside of `dtcw` to `dev`

**Comment by rdmueller** [comment]
I hope my last change did fix this.

**Comment by jmini** [comment]
This looks good for me after your change c370955.

In PR #882 we see the expected log. See https://github.com/docToolchain/docToolchain/pull/882#issuecomment-1202027465 for more details.

I think the same issue exists for the publication to `gh-pages` using travis:
https://github.com/docToolchain/docToolchain/issues/884
