### ISSUE TITLE
PDF style per project

### ISSUE THREAD

**Issue by jakubjab** [docToolchain/docToolchain#88]
## Expected behavior and actual behavior.

Currently there is a single PDF style hardcoded in build.gradle, no way to configure it at runtime.
I would like to make PDF styles configurable per project, so that it's part of the contents, instead of being part of the docToolchain tool (which would remain as default).
See also #70 which is related.

## Steps to reproduce the problem.

N/A

## Specifications like the version of the project, operating system, or hardware.

N/A

**Comment by jakubjab** [comment]
I'm already working on that, might happen that #70 is also fixed as a side-effect.

**Comment by rdmueller** [comment]
hm. what is your solution strategy? I could use it right now...

**Comment by rdmueller** [comment]
I tried to set the `:pdf-style:` inline in my documents. It works for the first one but is set to "default" for the second

**Comment by jakubjab** [comment]
For having PDF style configurable with the contents, I have a fix to just take it from the same directory as contents. I'm also fixing some smaller issues with relative/absolute paths.
For having PDF style per document, I thought I had an idea, but I was wrong.
