### ISSUE TITLE
PublishToConfluence does not find images

### ISSUE THREAD

**Issue by MartinHock** [docToolchain/docToolchain#883]
**Describe the bug**
We have a confluence server where we want to publish to the arc42 template that in our case is named arc42.html
 but the task fails with this error 
with java.io.FileNotFoundException: /project/build/html5/arc42/.../images/01_2_iso-25010-topics-DE.png (No such file or directory

**To Reproduce**
1.Have a confluenc server that can be published to 
2.configure docToolchainConfig.groovy like the following

inputPath = 'src/docs';
pdfThemeDir = './src/docs/pdfTheme'

inputFiles = [
        
	          [file: 'arc42/arc42.adoc', formats: ['html','pdf','docbook','docx']],
	/** inputFiles **/
]

//folders in which asciidoc will find images.
//these will be copied as resources to ./images
//folders are relative to inputPath
imageDirs = ["${inputPath}/images",
   
	
	/** imageDirs **/
]

// these are directories (dirs) and files which Gradle monitors for a change
// in order to decide if the docs have to be re-build

taskInputsDirs = [
                   "${inputPath}",
                  "${inputPath}/images",
                 ]

taskInputsFiles = []

confluence.with {
    input = [
            [ file: "build/html5/arc42/arc42.html" ],
    ]

3. executee .dtcw publishToConfluence Tasks

**Expected behavior**
the publishToConfluence Task does not expect files to be at locations that do not exist like

 /project/build/html5/arc42/.../images/01_2_iso-25010-topics-DE.png (No such file or directory)

**Configuration**
 - docToolchain docker image  rdmueller/doctoolchain v2.05 with added panDoc binaries
 - OS: [e.g. Windows, Linux, ...] 2.05

**Comment by rdmueller** [comment]
hm. I wonder about the path to the image:

     java.io.FileNotFoundException: /project/build/html5/arc42/.../images/01_2_iso-25010-topics-DE.png

it is `arc42/.../images` - three-times `.`. I think two-times would result in the correct path.

docToolchain sets the `:imagesdir:` to `images` which should result in `/project/build/html5/images/01_2_iso-25010-topics-DE.png`.

Do you change the `:imagesdir:` in your asciidoc files?

**Comment by rdmueller** [comment]
ah! could it be that you have something like

    :imagesdir: ../images

in your files in order to display images in your editor preview?

if so, please change it to

    ifndef::imagesdir[:imagesdir: ../images]

This will only set the `imagesdir` only if it is not defined (ifndef) and otherwise keep it (when doctoolchain runs).

**Comment by rdmueller** [comment]
@MartinHock do you have feedback to my comments?

**Comment by windows97** [comment]
@rdmueller 
According to your statement

> docToolchain sets the `:imagesdir:` to `images` which should result in `/project/build/html5/images/01_2_iso-25010-topics-DE.png`.

one might encounter problems if 
`:imagesdir: != images `
and you don't use
`ifndef::imagesdir[:imagesdir: ./whatsoever]`.

I think it would be worth to add a hint at least in the template config.

**Comment by rdmueller** [comment]
good point. could you suggest a change as PR?

**Comment by windows97** [comment]
#1112
done

**Comment by PacoVK** [comment]
I guess we can close the issue as it seems to be resolved
