### ISSUE TITLE
dtcw: create "latest" version and "#commit#" version

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#892]
to activly work on doctoolchain and try out new versions, it makes sense to have a

- "latest" version which always does is git pull of the current repository
- "#commit#" version which checks out a certain version of the repository

**Comment by rdmueller** [comment]
@ascheman @jmini any thoughts or wishes?

**Comment by jmini** [comment]
I think I have always used `latest`.

I was not even aware that there is a different versioning for `dtcw`…

**Comment by rdmueller** [comment]
ah, sorry, not the version of dtcw but the version configured in dtcw for doctoolchain

**Comment by rdmueller** [comment]
the PR solves the `latest` version issue for bash. I guess I will drop the `#commit#` feature and I also don't know if we need this feature for powershell (but it would be nice to have same features for all systems)
