### ISSUE TITLE
generateSite: {projectRootDir} does not seems to be avaible

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#898]
It seems that I can't use `{projectRootDir}` with the `generateSite` task as it is the case for generateHTML [according to the docs](https://doctoolchain.org/docToolchain/v2.0.x/020_tutorial/030_generateHTML.html).

This seems useful to me when I try to include some resource that are outside of my `src` folder.

Since the pages are first copied from `<project root folder>/src/docs/30_tri/10_ipsum.adoc` to `<project root folder>/build/microsite/tmp/site/doc/30_tri/10_ipsum.adoc`, this breaks the location of included file if a relative path is used. So I would like to use something absolute with `{projectRootDir}`

To be concrete:

```adoc
Example:
[source, json]
----
include::{projectRootDir}/aJavaProject/src/test/resources/some.json[]
----
```

Is turned into in the output:

> Example:
> `Unresolved directive in <stdin> - include::/project/aJavaProject/src/test/resources/some.json[]`

Or did I miss something?

**Comment by jmini** [comment]
I just saw a similar issue: https://github.com/docToolchain/docToolchain/issues/660

**Comment by jmini** [comment]
This seems to work in my reproducer project. So I need to understand what is wrong in my closed-source project.

**Comment by jmini** [comment]
Crap I think `/project` comes from the fact that my CI-job is running docToolchain inside a container…

**Comment by rdmueller** [comment]
I just gave it a try - seems to work for me.
Is there still an issue for oyu with the `{projectRootDir}`?
