### ISSUE TITLE
dtcw local <any-task> (bash) executes :help instead of <any-task>

### ISSUE THREAD

**Issue by alwessel** [docToolchain/docToolchain#899]
The execution of bash "dtcw local any-task" executes the gradle :help task instead of 'any-task'.

**Steps to reproduce the behavior:**
1. docker run --rm -it --entrypoint /bin/bash adoptopenjdk/openjdk11
2. apt update && apt install unzip
3. export DTC_HEADLESS=true 
4. dtcw local tasks
5. See error

**Expected behavior:**

gradle :tasks should have been executed instead of :help.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/30557334/184217499-66cd20b5-8273-4014-a6e5-637ec394285c.png)

**Configuration**
 - docToolchain v2.0.5 
 - OS: Windows 10 (within docker WSL2)
 - Docker-Image: adoptopenjdk/openjdk11 image (0551af19da78) after install of unzip

**Additional context**

The bug is within the bash function install_local() that build the command string by accessing arg1 with $1 which is not possible within a bash function.

**Comment by rdmueller** [comment]
thanx for the PR. Can you please verify that it now works and close or comment this issue?

**Comment by alwessel** [comment]
Its fixed :) Thanks and keep up the great work. I really appreciate it your tooling.
