### ISSUE TITLE
Support create one document without new pages for each chapter

### ISSUE THREAD

**Issue by rehsack** [docToolchain/docToolchain#904]
When a architectural knowledge base in confluence is founded and people upload arc42 based documentation, the 2nd upload must fail since all documents create a sub-page named `Introduction and Goals`.  Currently, only suppressing level 3 sub-pages are prohibited by `createSubpages = false`.

**Describe the solution you'd like**

Change `createSubpages` from _boolean_ to _integer_ and define behavior as follows:
0: one document is created - no conflicts are possible during same headlines from template
1: one master document is created with each section is a separate page (`createSubpages = false`)
2: behavior like `createSubpages = true`
3: even one level more ...

**Describe alternatives you've considered**
Introduce a flag name `createToppages = false`.

**Comment by rdmueller** [comment]
The solution we used so far is to use the `pagePrefix` and `pageSuffix` parameters.

https://github.com/docToolchain/docToolchain/blob/ng/template_config/Config.groovy#L213

This way, you can prepend the project name for the arc42 docs.

Another new feature it the option `allInOnePage` which should only create _one_ page.

https://github.com/docToolchain/docToolchain/blob/ng/template_config/Config.groovy#L245

Could you please check if this might be a solution for you?

**Comment by rehsack** [comment]
The latter one is an excellent solution.
