### ISSUE TITLE
dtcw is not fetching the correct docker image for version 2.1.0

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#906]
**Describe the bug**
Since version 2.1.0 the docker image is published under [`doctoolchain/doctoolchain`](https://hub.docker.com/r/doctoolchain/doctoolchain/tags) on docker hub.

It used to be [`rdmueller/doctoolchain`](https://hub.docker.com/r/rdmueller/doctoolchain/tags) with previous versions.

The dtcw script is not aware of this see:
https://github.com/docToolchain/docToolchain/blob/eee5705f6445187307f5d792e067c49147d45f0a/dtcw#L333

**To Reproduce**
Set the VERSION in dtcw to `2.1.0` in this line:

https://github.com/docToolchain/docToolchain/blob/eee5705f6445187307f5d792e067c49147d45f0a/dtcw#L16

as I did with commit:
https://github.com/jmini/dtc-experiments/commit/b4dee0fabe86e4621d9444f581063f18c55484a5

There is an error as you can see here:

```

Run ./dtcw generateSite
Using headless mode since there is no (terminal) interaction possible
./dtcw: line 28: !true: command not found
dtcw - docToolchain wrapper V0.31
docToolchain V2.1.0
docker available
/usr/bin/docker
use docker installation
Unable to find image 'rdmueller/doctoolchain:v2.1.0' locally
docker: Error response from daemon: manifest for rdmueller/doctoolchain:v2.1.0 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Error: Process completed with exit code 125.
```

https://github.com/jmini/dtc-experiments/actions/runs/2914467603

**Expected behavior**

It should work with the new coordinates (or support both depending of the `VERSION` value).

**Comment by rdmueller** [comment]
I think we should make this a bit more configurable.
IMHO, dtcw should have a header in which I can configure
- the version
- the theme
- the docker image location (for proxy / caching repositories)

It should be possible to overwrite those configs with environment variables.

what do you think?

**Comment by jmini** [comment]
This sounds good (even if I am not really aware of what you mean with specifying "the theme" in that context).

Right now I am moving forward with very simple fix:
https://github.com/jmini/dtc-experiments/commit/b7d0c3b5f7c14386f2441111af1bac7f35f64944

**Comment by rdmueller** [comment]
"the theme" => you can create an external theme for the rendered site

**Comment by rdmueller** [comment]
this has just been fixed - please close if you can confirm
