### ISSUE TITLE
generateSite used inside the 2.1.0 docker image is failing because of class cast exception

### ISSUE THREAD

**Issue by jmini** [docToolchain/docToolchain#907]
**Describe the bug**
When I try to run `generateSite` using version  2.1.0 in docker, I get a gradle error during the `bake` 

**To Reproduce**
```
> Task :generateSite
created
/project/build/microsite/tmp
copy internal theme /home/dtcuser/docToolchain/src/site
copy project theme /project/src/site

> Task :copyImages NO-SOURCE
> Task :bake FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bake'.
> A failure occurred while executing org.jbake.gradle.impl.JBakeWorkAction
   > class org.apache.commons.configuration2.CompositeConfiguration cannot be cast to class org.apache.commons.configuration.Configuration (org.apache.commons.configuration2.CompositeConfiguration and org.apache.commons.configuration.Configuration are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @4b823975)
2 actionable tasks: 2 executed
```

See https://github.com/jmini/dtc-experiments/runs/7989427291

**Expected behavior**
It should work in docker at it work locally.

**Configuration**
 - docToolchain version 2.1.0
 - used in the context of github action

**Additional context**
In the same project running `./dtcw local generateSite` locally works perfectly.

**Comment by jmini** [comment]
Since "unnamed module" seems to be a Java 9+ thing I tried with Java 11 locally:

```
$ rm -r build/
$ ./dtcw local generateSite

./dtcw: line 28: !false: command not found
dtcw - docToolchain wrapper V0.31
docToolchain V2.1.0
grep: /proc/version: No such file or directory
docker available
home folder exists
force use of local install
use local homefolder install /user/home/.doctoolchain/
Java Version 11
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.9.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

> Task :generateSite
/user/home/Git/dtc-experiments/build/microsite/tmp
copy internal theme /user/home/.doctoolchain/docToolchain-2.1.0/src/site
copy project theme /user/home/Git/dtc-experiments/src/site

> Task :bake
Warning: Nashorn engine is planned to be removed from a future JDK release
Parsing skipped (missing type or status value in header meta data) for file /user/home/Git/dtc-experiments/build/microsite/tmp/site/doc/_init.adoc!
/user/home/Git/dtc-experiments/build/microsite/tmp/site/doc/_init.adoc has an invalid header, it has been ignored!

BUILD SUCCESSFUL in 24s
```

Still working…

**Comment by jmini** [comment]
I compared the output of:

* LOCAL: `./dtcw local dependencies`
* DOCKER: `./dtcw docker dependencies`

For the `jbake` configuration I notice a change of version of `org.jbake:jbake-core`:

```patch
@@ -1,10 +1,10 @@
-LOCAL
+DOCKER
 jbake
 +--- org.asciidoctor:asciidoctorj-diagram:2.0.2
 +--- io.pebbletemplates:pebble:3.1.2 -> 3.1.5
 |    +--- org.unbescape:unbescape:1.1.6.RELEASE
 |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
-+--- org.jbake:jbake-core:2.6.7
++--- org.jbake:jbake-core:2.7.0-rc.2
 |    +--- org.slf4j:slf4j-api:1.7.30
 |    +--- org.slf4j:jul-to-slf4j:1.7.30
 |    |    \--- org.slf4j:slf4j-api:1.7.30
@@ -15,9 +15,14 @@
 |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.30
 |    +--- ch.qos.logback:logback-core:1.2.3
 |    +--- commons-io:commons-io:2.8.0
-|    +--- commons-configuration:commons-configuration:1.10
-|    |    +--- commons-lang:commons-lang:2.6
-|    |    \--- commons-logging:commons-logging:1.1.1 -> 1.2
+|    +--- org.apache.commons:commons-configuration2:2.7
+|    |    +--- org.apache.commons:commons-lang3:3.9 -> 3.12.0
+|    |    +--- org.apache.commons:commons-text:1.8
+|    |    |    \--- org.apache.commons:commons-lang3:3.9 -> 3.12.0
+|    |    \--- commons-logging:commons-logging:1.2
+|    +--- commons-beanutils:commons-beanutils:1.9.4
+|    |    +--- commons-logging:commons-logging:1.2
+|    |    \--- commons-collections:commons-collections:3.2.2
 |    +--- org.apache.commons:commons-vfs2:2.7.0
 |    |    +--- commons-logging:commons-logging:1.2
 |    |    \--- org.apache.hadoop:hadoop-hdfs-client:3.3.0
@@ -219,6 +224,7 @@
 |    |    \--- com.vladsch.flexmark:flexmark-util-sequence:0.62.2 (*)
 |    +--- org.jsoup:jsoup:1.13.1
 |    +--- io.pebbletemplates:pebble:3.1.5 (*)
+|    +--- org.yaml:snakeyaml:1.28
 |    +--- org.eclipse.jetty:jetty-server:9.4.36.v20210114
 |    |    +--- javax.servlet:javax.servlet-api:3.1.0
 |    |    +--- org.eclipse.jetty:jetty-http:9.4.36.v20210114
@@ -226,7 +232,7 @@
 |    |    |    \--- org.eclipse.jetty:jetty-io:9.4.36.v20210114
 |    |    |         \--- org.eclipse.jetty:jetty-util:9.4.36.v20210114
 |    |    \--- org.eclipse.jetty:jetty-io:9.4.36.v20210114 (*)
-|    \--- args4j:args4j:2.33
+|    \--- info.picocli:picocli:4.6.1
 +--- org.asciidoctor:asciidoctorj:2.4.3 (*)
 +--- com.vladsch.flexmark:flexmark:0.62.2 (*)
 +--- com.vladsch.flexmark:flexmark-profile-pegdown:0.62.2 (*)
```

I think that this newer version is not compatible with the version of **commons-configuration** used in the task `grettyStarter`.

* My local installation is using `org.gretty:gretty-starter:3.0.8`
* The docker image is using `org.gretty:gretty-starter:3.0.6`

And both have a dependency to `commons-configuration:commons-configuration:1.10`

I guess this creates the incompatibility.

----

Now the question:

Where are the version defined?
Why is the docker image using ` org.jbake:jbake-core:2.7.0-rc.2` and my local installation `org.jbake:jbake-core:2.6.7`?
How can I change this....

@rdmueller or @ascheman maybe you can give me some pointers here...

In the code I see those versions:

https://github.com/docToolchain/docToolchain/blob/a8a3ca4ef7544922a7fd115739242a0dfbc4bc6f/build.gradle#L13

https://github.com/docToolchain/docToolchain/blob/a8a3ca4ef7544922a7fd115739242a0dfbc4bc6f/scripts/generateSite.gradle#L35-L44

But it looks like other versions are used.

**Comment by jmini** [comment]
At least I found some explanation:

The file `generateSite.gradle` inside the docker image contains `version = '2.7.0-rc.2'`

Run:

```
docker run -it --rm -a stdout --entrypoint cat doctoolchain/doctoolchain:v2.1.0 /home/dtcuser/docToolchain/scripts/generateSite.gradle
```
And you will get (I copy-pasted only the relevant parts):
```gradle

apply plugin: 'org.jbake.site'
apply plugin: 'org.gretty'

def color = { color, text ->
    def colors = [black: 30, red: 31, green: 32, yellow: 33, blue: 34, magenta: 35, cyan: 36, white: 37]
    return new String((char) 27) + "[${colors[color]}m${text}" + new String((char) 27) + "[0m"
}

jbake {
    version = '2.7.0-rc.2'

```

**Comment by rdmueller** [comment]
thanx for reporting this and sorry for the time this took you to analyze it. It helped me to find the problem quickly:

the docker files can be found here: https://github.com/docToolchain/docker-image

the last docker immaes where created manually and locally, then uploaded to the docker hub. This was because docker started to charge for the automatic build and I was not willing to invest into this.

So, I always updated the version used within the container manually and it worked.
@ascheman created an automated build for the jenkins docker image and I used this as a basis for the new 2.1.0 docker image but didn't realize that I haven't switched the docToolchain version.

So, I will now update the dockerfile and hopefully solve this problem this way.

**Comment by rdmueller** [comment]
docker run -it --rm -a stdout --entrypoint cat doctoolchain/doctoolchain:v2.1.0 /home/dtcuser/docToolchain/scripts/generateSite.gradle

=> 2.6.7

so, this should be fixed. But I noticed that the docker file will not use the given tag, but the current version.

**Comment by rdmueller** [comment]
ok, I see the problem - there is no tag v2.1.0 yet. So not really a problem :-)

if you are ok with the new image, please close this issue.

**Comment by rdmueller** [comment]
the docker image should be fine now. Please close this issue if you are happy with the results. Otherwise add a comment.

**Comment by rdmueller** [comment]
argh. the docker file builds but I get the following error:

```
* What went wrong:
Gradle could not start your build.
> Could not initialize native services.
   > Failed to load native library 'libnative-platform.so' for Linux amd64.
```

**Comment by jmini** [comment]
About this issue, what I mentioned on twitter:

> Not having the same files when using “local” and “docker” is really disturbing and not what I am expecting.
> For me when there is a tag in git, this corresponds to a release and the same code should be available in docker as well.

**Comment by jmini** [comment]
Your changes looks good to me:

* Tried in GitHub action: https://github.com/jmini/dtc-experiments/actions/runs/3021205055
* Tried locally (after having run `docker pull` to get a `Downloaded newer image for doctoolchain/doctoolchain:v2.1.0`)

**Comment by rdmueller** [comment]
the build error I got was due to a problem with dtcw => https://github.com/docToolchain/docToolchain/issues/914
