### ISSUE TITLE
Docs: Feedback for 'generatePDF'

### ISSUE THREAD

**Issue by houserockr** [docToolchain/docToolchain#915]
The examples shown here are obsolete.
The parameters for pdf-themes are now `pdf-themesdir` and `pdf-theme` rather than `pdf-stylesdir` and `pdf-style`.

---
#page: https://github.com/doctoolchain/doctoolchain/edit/ng/src/docs/015_tasks/03_task_generatePDF.adoc
#branch: ng

**Comment by rdmueller** [comment]
thanx for the feedback - I've updated the docs. Can you please verify it and then close this issue?

**Comment by houserockr** [comment]
Yep, looking great.
Thank you very much, Ralf!
