### ISSUE TITLE
previewSite throws PatternSyntaxException in version 2.1.0

### ISSUE THREAD

**Issue by chludwig-haufe** [docToolchain/docToolchain#920]
**Describe the bug**
I downloaded the `dtcw` wrapper (version 0.35) into an empty folder, downloaded the arc42 template, ran the `generateSite` task, and finally the `previewSite` task.

This throws an exception in the `:prepareInplaceWebApp` Gradle task:
~~~
Exception in thread "main" java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 0
?/logs/docToolchain-\d{4}-\d{2}-\d{2}_\d{2}.log
^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2029)
~~~

It's followed by the `:jettyRun` Gradle task, but when I point my browser to http://localhost:8042/, all I get is an empty response.

This seems to be a regression in docToolchain 2.1.0 (or it's dependencies): When I downgraded to version 2.0.5 (using the image `rdmueller/doctoolchain:v2.0.5`), the site was successfully rendered.

**To Reproduce**

1. `mkdir doctoolchain; cd doctoolchain/`
2. `curl -Lo dtcw doctoolchain.github.io/dtcw ; chmod u+x dtcw`
3. `./dtcw downloadTemplate` 

    Answers:
    - `y` for creation of default config
    - `EN` for selected language
    - `withhelp` for template option
5. `./dtcw generateSite`
6. `./dtcw generateSite`

Console output: [previewSite_console_output.txt](https://github.com/docToolchain/docToolchain/files/9549787/previewSite_console_output.txt)

**Expected behavior**
No exception and the site should be served by jetty on the configured endpoint. If I need to customize some configuration, then the docs should say so and the task should terminate with a meaningful error message.

**Configuration**
 - Docker Image `doctoolchain/doctoolchain:v2.1.0`
 - OS: macOS Big Sur on Intel MacBook Pro

**Comment by rdmueller** [comment]
Thanx for the detailed error report. I will take a look asap.

Btw: instead of using previewSite, you also should be able to open the files locally in your browser

**Comment by rdmueller** [comment]
interesting - seems to be only a problem with the docker image, not with the local installation

**Comment by rdmueller** [comment]
found the problem. I bumped 
    id 'org.gretty' version '3.0.8'

from 3.0.6.

I will now revert this so it will be fixed in the next release.
