### ISSUE TITLE
./dtcw local doesn't do a git clone to populate $HOME/.doctoolchain/docToolchain-${VERSION}

### ISSUE THREAD

**Issue by clarsen** [docToolchain/docToolchain#922]
https://github.com/docToolchain/docToolchain/blob/2842abffa598ce355902f70a213dae2631d2c136/dtcw#L254

I think you want this to be `if [ -d "$HOME/.doctoolchain/docToolchain-${VERSION}/.git" ]; then`
because the `mkdir -p $HOME/.doctoolchain/docToolchain-latest` above this will always result in `if [ -d "$HOME/.doctoolchain/docToolchain-${VERSION}/." ]; then` being true and unsuccessfully attempting a git pull inside an empty directory.

**Comment by rdmueller** [comment]
that is indeed a good point!

Would you like to send a pull request?

**Comment by rdmueller** [comment]
wait a moment... I just managed to read my own code...

the goal is to...

... just clone once if version is `latest` - you just use the latest version and that's it

... clone once and do pulls if version is `latestdev` - this way, you follow the current development

`latest` also uses http-protocol in order not to need to login.

Does this make sense?

**Comment by rdmueller** [comment]
you are right. there is something wrong. I currently try to fix this.

**Comment by rdmueller** [comment]
I fixed it in the way you suggested. Both version will always try to pull the latests version. `latestdev` will checkout via ssh an thus enable you to make changes and push them back

**Comment by clarsen** [comment]
@rdmueller sorry for not responding earlier.  Thanks!
