### ISSUE TITLE
Embedding SVG fails for generatePDF on WSL2 Debian

### ISSUE THREAD

**Issue by houserockr** [docToolchain/docToolchain#958]
**Describe the bug**
When I try to compile my docToolchain project in a Debian 11 WSL2 "container", svg images won't be embedded into the final PDF.

**To Reproduce**
```
$ dtcw generatePDF

dtcw - docToolchain wrapper V0.35
docToolchain V2.1.0
home folder exists

Bash is running on WSL
this might cause problems with plantUML
see https://doctoolchain.github.io/docToolchain/#wsl for more details

use local homefolder install /home/foo/.doctoolchain/
Java Version 11
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.9.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

> Task :generatePDF
Converting /home/foo/env/project/src/bar.adoc
could not embed image: /home/foo/env/project/images/image.svg; undefined method `dclone for "contains":String
```

**Expected behavior**
SVG images are embedded into PDF like they are on a "regular" Linux host for my project.

**Additional Info**
When I invoke `generatePDF -d` for debug output, I get the following from `JRubyAsciidoctor` right before the warning:

`2022-11-04T16:14:55.971+0100 [DEBUG] [org.asciidoctor.internal.JRubyAsciidoctor] asciidoctor -B /mnt/c/Users/foo/env/project/src -S UNSAFE -b pdf -a source-highlighter=highlightjs@ -a imagesdir=images@ -a toc=left@ -a icons=font@ -a javaVersion=11.0.16 -a currentDate=4. Nov 2022 -a allow-uri-read=true@ -a sectanchors=true@ -a targetDir=/mnt/c/Users/foo/env/project/build -a docDir=/mnt/c/Users/foo/env/project -a projectRootDir=/mnt/c/Users/foo/env/project@ -a plantUMLDir=/mnt/c/Users/foo/env/project/build/images -a data-uri=true -a imagesoutdir=/mnt/c/Users/foo/env/project/build/images -a projectdir=../../../../../../..home/foo/.doctoolchain/docToolchain-2.1.0 -a rootdir=../../../../../../..home/foo/.doctoolchain/docToolchain-2.1.0 -a project-name=docToolchain -a project-group -a project-version=unspecified /mnt/c/Users/foo/env/project/src/foobar.adoc`

**Configuration**
 - docToolchain version: 2.1.0
 - OS: Debian 11 WSL2 image/container on Windows 10 host
 - Java 11.0.16 (debian package openjdk-11-jdk)

**Comment by rdmueller** [comment]
That error sounds quite strange:

undefined method `dclone for "contains":String

Habe you already tried to replace the image with another one?

Habe you already vreated a minimalistic public project so that I can reproduce the problem?

**Comment by houserockr** [comment]
Yes, I agree, it's strange indeed and I couldn't really find anything helpful with google.

I just replaced the image with a firefox logo in SVG format. Generally, that works, so the problem is in fact related to the image itself OR the tool/component under the hood of DTC that renders SVG.

However, even the firefox logo gives me strange warnings, which leads me to believe that the tool/component for SVG under the hood might be outdated or buggy on my system:
`
problem encountered in image: /home/foo/env/project/images/firefox.svg; Unknown tag radialGradient; ignoring
`

Ok, one might consider `radialGradient` to be too exotic for pdf.

I cannot provide a public project or the image, due to confidentiality reasons, unfortunately.

Can I pinpoint and debug or update the component that renders SVG? `JRubyAsciidoctor` tells me it's a ruby module?

**Comment by houserockr** [comment]
I managed so solve this by cleaning up my svg graphic. `ctrl+a` in inkscape revealed some dubious paths and random pseudo objects that probably were intended to serve as margin/padding back in the day. Removed them and broke apart some of the paths. Then I c&p'd everything into a new file and saved that as non-inkscape svg. I apologize if I wasted anybody's time.
