### ISSUE TITLE
http-builder-0.7.2.pom no longer available

### ISSUE THREAD

**Issue by sbithinx** [docToolchain/docToolchain#960]
**Describe the bug**
The package http-builder (version 0.7.2) the docToolchain is using, is no longer available.

**Additional context**
`https://plugins.gradle.org/m2/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom`

```
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not find org.codehaus.groovy.modules.http-builder:http-builder:0.7.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         unspecified:unspecified:unspecified
```

```
    dependencies {
        //for the exportJiraIssues Task
        classpath 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.2'
        classpath 'org.apache.poi:poi-ooxml:4.1.1'
    }
```

**Comment by rdmueller** [comment]
WTF? There is even no trace of 0.7.2 anywhere. Seems like it never existed :-o

**Comment by rdmueller** [comment]
btw: thanx for bringing this to my attention

**Comment by rdmueller** [comment]
So, I guess this has to do with the fact that jcenter is not available. Or at least something like this.

jcenter should be read-only until forever. 

As a workaround for the moment, the docker images should contain all dependencies. It should be possible to use them instead of a local install. It should even be possible to extract the dependencies from there.

**Comment by rdmueller** [comment]
https://twitter.com/WajahatKarim/status/1589864360750768128

https://stackoverflow.com/questions/74258160/is-jcenter-down-permanently-31-oct

https://status.gradle.com/?utm_source=embed

**Comment by rdmueller** [comment]
strategy for the moment: wait and hope that jcenter will be back soon.
Until then, use the docker image

`./dtcw docker ...`

long term strategy: update all dependencies which are only available at jcenter

**Comment by rdmueller** [comment]
Problem resolved itself> https://github.com/docToolchain/docToolchain/actions/runs/3428105432

can you please confirm_

**Comment by sbithinx** [comment]
Yes, works again and thanks for the fast response.
