### ISSUE TITLE
generateSite: beforetoc is broken

### ISSUE THREAD

**Issue by rdmueller** [docToolchain/docToolchain#972]
with the introduction of the `magic-toc` in 2.1.0, the `beforetoc` logic is broken.

https://github.com/docToolchain/docToolchain/blob/ng/scripts/generateSite.gradle#L459

to reproduce this, change the `toclevels` of a document and render it. in 2.0.5, the toc on the left is rendered according to this setting, with 2.1.0, only two levels are rendered.

**Comment by mxmehl** [comment]
This seems to be fixed
