### ISSUE TITLE
Enable testing of dtcw

### ISSUE THREAD

**Issue by ascheman** [docToolchain/docToolchain#988]
As a developer and maintainer of dtcw I would like to get a test suite which allows to prove the functionality of `dtcw` under certain conditions, e.g.,

- Tools to download/install/run DTC are available/not available, i.e., `curl` (or `wget`), JDK, ...
- Several ways to run DTC (sdk, local, docker).

**Additional context**
When changing the wrapper I would like to run some local tests but at latest the CI server (GH Actions) should make sure that no regression occurs.

**Comment by mh182** [comment]
We can not use the docker container provided by [bats-core](https://github.com/bats-core/bats-core) since it is based on Alpine, which uses MUSL for libc. 

Downloading and installing a Java version into the container doesn't provide a executable java.
```
# In the test container
bash-5.2# ldd /root/.doctoolchain/jdk/bin/java
        /lib64/ld-linux-x86-64.so.2 (0x7f5033a07000)
        libz.so.1 => /lib/libz.so.1 (0x7f50337ea000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f5033a07000)
        libjli.so => /root/.doctoolchain/jdk/bin/../lib/jli/libjli.so (0x7f50335d9000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f5033a07000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f5033a07000)
Error relocating /root/.doctoolchain/jdk/bin/../lib/jli/libjli.so: __strdup: symbol not found
Error relocating /root/.doctoolchain/jdk/bin/../lib/jli/libjli.so: __rawmemchr: symbol not found

```

This means we have to create our own `dtcw` test container.

**Comment by rdmueller** [comment]
bats-core is interesting. I already had a running test system with https://www.testcontainers.org/ and Spock. I think I should search for it and add it to the project. Was running quite well...

**Comment by mh182** [comment]
Just to get this straight. The container image used to test `dtcw` (which happens to have bats installed) has to be a minimal Linux system because the image is used to test installation processes with `dtcw`.

So we can't use a container with installed Java ;-)

**Comment by rdmueller** [comment]
yes, these where my thought which led to the testcontainers approach. "for Java" only means that you have a library which can start and control containers from a java unit test. I already had an alpine image working with this approach.
