### ISSUE TITLE
exportEAP.vbs - EA 16.1 Enterprise Architect background process hangs (calling Exit not enough)

### ISSUE THREAD

**Issue by Zheng-Bote** [docToolchain/docToolchain#991]
**Describe the bug**
using dtc exportEAP, the EA 16.1 Enterprise Architect background process hangs. Calling Exit is not enough. 

**Additional context**
See also: 
https://sparxsystems.com/enterprise_architect_user_guide/16.0/add-ins___scripting/codesamples.html
Enterprise Architect Not Closing

**Solution**
exportEAP.vbs add below line 392
`      ' fix for EA 16.1 where Enterprise Architect background process hangs 
      On Error Resume Next
        EAapp.Repository.CloseFile()
        EAapp.Repository.Exit()
        EAapp.Repository = null
      ' end fix EA 16.1
`

**Comment by Zheng-Bote** [comment]
will be fixed with Pull Request #996

**Comment by rdmueller** [comment]
thanx! shall we close this now or wait until the next release where your fix will be included?

**Comment by Zheng-Bote** [comment]
well, I would like to recommending to keep it open until the next release with the fix is published. Otherwise EA 16 users with same problems will open the same issue again.
But you are the PO, of course I would also accept when you are closing this issue now.

**Comment by rdmueller** [comment]
the community owns the code, I only try to merge some PRs :-) so let's keep it open

**Comment by Zheng-Bote** [comment]
successfully solved in v2.2.0
