### ISSUE TITLE
Document on authorization confuses

### ISSUE THREAD

**Issue by simonmysun** [docToolchain/docToolchain#992]
Hi, I may have mistaken something but I see nowhere mentioned bearerToken in `03_task_publishToConfluence.adoc`[^03_task_publishToConfluence.adoc] and nowhere refered to APIToken in `asciidoc2confluence.groovy`[^asciidoc2confluence.groovy]. Additionally, I see that in the document of enterprise version[^confluence_enterprice_doc_personal_token], basic authorization should be base64 encoded `username:password`, while in the cloud version document[^confluence_cloud_basic_auth] it's base64 encoded `your_email@domain.com:your_user_api_token`. This is very confusing to me. I have confirmed that both of them are correct and don't work the other way around. Is it because the APIs have changed and any of the document is outdated? If the outdated documents turn out to be docToolchain's, shall I try to update?

[^03_task_publishToConfluence.adoc]: https://github.com/docToolchain/docToolchain/blob/fb8becb8dcc92e67bd01c5d7fb12ba35c8ac0193/src/docs/015_tasks/03_task_publishToConfluence.adoc "docToolchain/03_task_publishToConfluence.adoc at fb8becb8dcc92e67bd01c5d7fb12ba35c8ac0193 · docToolchain/docToolchain"
[^asciidoc2confluence.groovy]: https://github.com/docToolchain/docToolchain/blob/fb8becb8dcc92e67bd01c5d7fb12ba35c8ac0193/scripts/asciidoc2confluence.groovy "docToolchain/asciidoc2confluence.groovy at fb8becb8dcc92e67bd01c5d7fb12ba35c8ac0193 · docToolchain/docToolchain"
[^confluence_enterprice_doc_personal_token]: https://web.archive.org/web/20221229103704/https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html "Using Personal Access Tokens | Atlassian Support | Atlassian Documentation"
[^confluence_cloud_basic_auth]: https://web.archive.org/web/20220821111009/https://developer.atlassian.com/cloud/confluence/basic-auth-for-rest-apis/ "Basic auth for REST APIs"

This was mentioned in https://github.com/docToolchain/docToolchain/discussions/761#discussioncomment-4607412 and moved here.

**Comment by rdmueller** [comment]
Yes, this is confusing and there are even more ways to authenticate.

The cloud version and on premises version of confluence have diverged regarding the API which leads to more complexity.

Basically, it is always `<user-id>:<secret>` whatever this is. For the cloud version, `<email>:<password>` should also be valid.

So, if you could update the docs in such a way that they would be less confusing, I would be happy to merge your pull request!
