### ISSUE TITLE
Wrapper uses external main_config_file variable

### ISSUE THREAD

**Issue by RoettingerJ** [docToolchain/docToolchain#995]
Dear all, 
in the current implementation of the dtcw / dtcw.ps1 we do not see a solution for specifying a custom main configuration file with name and location other than docToolchainConfig.groovy in the root folder of a project.

So we have to adjust the hardcoded line 
`MAIN_CONFIG_FILE=docToolchainConfig.groovy` (dtcw line 15) 
to something like 
`MAIN_CONFIG_FILE=doc/src/docs/docToolchainConfig.groovy`

I would recommend to replace the current logic to something like ...
 
```
if [ "$MAIN_CONFIG_FILE" = "" ] ; then
  MAIN_CONFIG_FILE=docToolchainConfig.groovy
fi
```

... or do you see any other solution ?

Can also provide a PR for that.

**Comment by rdmueller** [comment]
this is a very good idea. would it make sense to use `$MAIN_CONFIG_FILE` as environment variable? Then I would name it `$DTC_MAIN_CONFIG_FILE`. A PR would be great!
